#+Description: 基于中央财经大学《审计学》第六版

* 第一章审计概论
:PROPERTIES:
:heading: 1
:collapsed: true
:END:
** 第一节审计的定义和特征
:PROPERTIES:
:heading: 2
:collapsed: true
:END:
*** 定义：六大方面。主体、客体、授权者、审计依据、审计的目的、审计的性质
*** 特征：独立、权威
** 第二节审计的产生和发展
:PROPERTIES:
:heading: 2
:END:
** 第三节审计的职能和作用
:PROPERTIES:
:heading: 2
:END:
职能：经济监督、经济评价、经济鉴证 作用：制约性、促进性
** 第四节审计的分类
:PROPERTIES:
:heading: 2
:collapsed: true
:END:
审计的基本分类是说明审计本质的分类，即按审计的内容和目的分类和按审计的主体分类。
*** 内容和目的：财政财务审计、财经法纪审计、经济效益审计
三类审计是有区别的，但又不能截然分开。一般来说，财政财务审计是审计的基础，财经法纪审计是审计的重要内容，经济效益审计是现代审计的根本目的，这三种审计存在于同一个审计过程之中，只有当审计进行到一定程度时才有侧重。
*** 主体：国家审计、内部审计和社会审计
社会审计与国家审计、内部审计所不同的是实行有偿服务，自收自支、自负盈亏、独立核算、依法纳税，具有法人资格，因此在业务上具有较强的独立性、客观性和公正性。
*** 使用的技术方法：账项基础审计、制度基础审计、风险导向审计
** 第五节注册会计师审计与其他审计的关系
:PROPERTIES:
:heading: 2
:END:
** 第六节注册会计师管理
:PROPERTIES:
:heading: 2
:END:
* 第二章 注册会计师执业准则体系与法律责任
:PROPERTIES:
:heading: 1
:collapsed: true
:END:
** 第一节中国注册会计师执业准则体系
:PROPERTIES:
:heading: 2
:END:
** 第二节注册会计师业务准则
:PROPERTIES:
:heading: 2
:collapsed: true
:END:
*** 鉴证业务的五要素：三方关系、鉴证对象和鉴证对象信息、标准、证据、鉴证报告
*** 鉴证业务中的三方关系：注册会计师对由责任方负责的鉴证对象或鉴证对象信息提出结论，以增强责任方之外的预期使用者对鉴证对象信息的信任程度。
***
** 第三节注册会计师的法律责任
:PROPERTIES:
:heading: 2
:END:
* 第三章 注册会计师职业道德规范
:PROPERTIES:
:heading: 1
:collapsed: true
:END:
** 第一节概述
:PROPERTIES:
:heading: 2
:END:
** 第二节职业道德基本原则
:PROPERTIES:
:heading: 2
:END:
诚信、独立、客观和公正、专业胜任能力和应有的关注、保密、良好的职业行为
** 第三节职业道德概念框架
:PROPERTIES:
:heading: 2
:END:
不利影响的因素包括自身利益、自我评价、过度推介、密切关系和外在压力
** 第四节提供专业服务的具体要求
:PROPERTIES:
:heading: 2
:collapsed: true
:END:
*** 专业服务是指注册会计师提供的需要会计或相关技能的服务，包括会计、审计、税务、管理咨询和财务管理等服务。
*** 在提供专业服务的过程中，可能存在许多对职业道德基本原则产生不利影响的情形，包括*专业服务委托、利益冲突、应客户要求提供第二次意见、收费、专业服务营销、礼品和款待、保管客户资产、对客观和公正原则的要求*
** 第五节审计和审阅业务对独立性的要求
:PROPERTIES:
:heading: 2
:END:
** 第六节其他鉴证业务与审计、审阅业务之间对独立性要求的差异
:PROPERTIES:
:heading: 2
:END:
* 第四章业务质量控制
:PROPERTIES:
:heading: 1
:collapsed: true
:END:
** 第一节 质量控制制度的目的和要素
:PROPERTIES:
:heading: 2
:END:
1 ）对业务质量承担的领导责任；（ 2 ）相关职业道德要求；（ 3）客户关系和具体业务的接受与保持；（ 4 ）人力资源；（ 5 ）业务执行；（ 6）监控。
** 第二节 对业务质量承担的领导责任
:PROPERTIES:
:heading: 2
:END:
** 第三节 职业道德规范
:PROPERTIES:
:heading: 2
:END:
** 第四节 客户关系和具体业务的接受与保持
:PROPERTIES:
:heading: 2
:END:
** 第五节 人力资源
:PROPERTIES:
:heading: 2
:END:
** 第六节 业务执行
:PROPERTIES:
:heading: 2
:collapsed: true
:END:
*** 项目质量控制复核
:PROPERTIES:
:collapsed: true
:END:
**** 含义与总体要求
项目质量控制复核，是指会计师事务所挑选不参与该业务的人员，在出具报告前，对项目组作出的重大判断和在准备报告时形成的结论作出客观评价的过程。
**** 项目质量控制复核与项目组内部复核，内容和目的等有相似性，主要区别：
:PROPERTIES:
:collapsed: true
:END:
***** 1.复核的主体不同。项目组复核是项目组内部进行的复核，包括项目合伙人实施的复核。项目质量控制复核则是会计师事务所挑选不参与该业务的人员，独立地对特定业务实施的复核。后者的独立性和客观性通常高于前者。
***** 2.复核的对象不同。对每项业务都应当实施项目组内部复核；而会计师事务所只对特定业务才实施独立的项目质量控制复核。
***** 3.复核的要求不同。对每项业务实施项目组内部复核的内容比较宽泛；会计师事务所对特定业务实施项目质量控制复核的重点，是客观评价项目组作出的重大判断和在准备报告时形成的结论。
** 第七节 监控
:PROPERTIES:
:heading: 2
:collapsed: true
:END:
*** 一、监控的含义和目的
监控是指对会计师事务所质量控制制度进行持续考虑和评价的过程，包括定期选取已完成的业务进行检查，以使会计师事务所能够合理保证其质量控制制度正在有效运行。
*** 二、监控内容
监控的内容包括质量控制制度设计的适当性和运行的有效性。
*** 三、实施检查
会计师事务所应当周期性地选取已完成的业务进行检查，周期最长不得超过年。在每个周期内，应对每个项目合伙人的业务至少选取1项进行检查。
* 第五章 财务报表审计的目标和一般原则
:PROPERTIES:
:heading: 1
:collapsed: true
:END:
** 第一节财务报表审计的目标
:PROPERTIES:
:heading: 2
:collapsed: true
:END:
审计目标是指在一定的历史环境下，人们通过审计实践活动所期望达到的理想境地或最终结果。它包括财务报表审计的总目标以及各类交易、账户余额、列报相关的具体审计目标两个层次。
*** 总目标：注册会计师通过执行审计工作，对财务报表的合法性、公允性发表审计意见。
***
** 第二节财务报表审计的双方责任
:PROPERTIES:
:heading: 2
:collapsed: true
:END:
*** *被审计单位管理层和治理层的责任：*保证财务报表的合法性、公允性（回顾审计总体目标）、维护内控制度等
*** *注册会计师等责任：*1、遵守职业道德规范；2、遵守质量控制准则；3、遵守审计准则。
** 第三节财务报表审计中的若干一般原则与重要理念
:PROPERTIES:
:heading: 2
:collapsed: true
:END:
包括审计范围、职业判断、职业怀疑态度、合理保证、财务报表审计的固有限制、审计风险以及重要性
*** *财务报表的审计范围*是指为实现财务报表审计目标，注册会计师根据审计准则和职业判断实施的恰当的*_审计程序的总和_*。
*** *审计中的职业判断*是指注册会计师在审计准则的框架下，运用专业知识和经验在备选方案中作出决策。
*** *职业怀疑态度*是指注册会计师以质疑的思维方式评价所获取审计证据的有效性，并对相互矛盾的审计证据，以及引起对文件记录或管理层和治理层提供的信息的可靠性产生怀疑的审计证据保持警觉
*** *合理保证*要求注册会计师通过不断修正的、系统的执业过程，获取充分、适当的证据，对财务报表整体发表审计意见，它提供的是一种高水平但非 100 ％的保证。
*** *审计风险*是指财务报表存在重大错报而注册会计师发表不恰当审计意见的可能性。
:PROPERTIES:
:collapsed: true
:END:
合理保证与审计风险互为补数，即合理保证与审计风险之和等于
100％。如果注册会计师将审计风险降至可接受的低水平，则对财务报表不存在重大错报获取了合理保证。
**** 审计风险=重大错报风险×检查风险（ AR = MMR xDR)
** 第四节基本审计流程
:PROPERTIES:
:heading: 2
:END:
接受业务委托、计划审计工作、实施风险评估程序、实施控制测试和实质性程序、完成审计工作和编制审计报告
* 第六章审计业务约定书与计划审计工作
:PROPERTIES:
:heading: 1
:collapsed: true
:END:
〖本章学习纲要〗 掌握审计业务约定书的含义、总体要求及其内容
掌握计划审计工作的含义和总体要求 理解初步业务活动的目的及其内容
理解总体审计策略和具体审计计划的含义及其主要内容
** 第一节审计业务约定书
:PROPERTIES:
:heading: 2
:collapsed: true
:END:
审计业务约定书是指会计师事务所与被审计单位签订的，用以记录和确认审计业务的委托与受托关系、审计目标和范围、双方的责任以及报告的格式等事项的书面协议。
*** 审计业务约定书的内容：审计业务约定书的必备条款、应当考虑增加的其他条款，以及实施集团财务报表审计时的特殊考虑。
*** 连续审计中的考虑：重新签订审计业务约定书：（ 1 ）有迹象表明被审计单位误解审计目标和范围；（ 2 ）需要修改约定条款或增加特别条款；（ 3 ）高级管理人员、董事会或所有权结构近期发生变动；（ 4 ）被审计单位业务的性质或规模发生重大变化；（ 5 ）法律法规的规定；（ 6 ）管理层编制财务报表采用的会计准则和相关会计制度发生变化。
** 第二节计划审计工作
:PROPERTIES:
:heading: 2
:collapsed: true
:END:
*** 计划审计工作的总体要求
**** 计划审计工作是指注册会计师为了完成年度财务报表的审计业务，达到预期的审计目标，在具体执行审计程序之前对审计工作所做的合理规划和安排，即制定审计的计划。
计划审计工作包括针对审计业务制定总体审计策略和具体审计计划，以将审计风险降至可接受的低水平。
**** 初步业务活动的内容：1 ，针对保持客户关系和具体审计业务实施相应的质量控制程序。2 ，评价遵守职业道德规范的情况，包括评价独立性。3 ，及时签订或修改审计业务约定书。
发生在计划审计工作前
**** 总体审计计划
**** 具体审计计划：具体审计计划是依据总体审计策略制定的，对实施总体审计策略所需要的审计程序的性质、时间和范围等所做的详细规划与说明。应当包括风险评估程序、计划实施的进一步审计程序和其他审计程序。
* 第七章审计证据与审计工作底稿
:PROPERTIES:
:heading: 1
:collapsed: true
:END:
〖本章学习纲要〗
掌握审计证据的含义及来源、理解审计证据的性质理解获取审计证据的审计程序
掌握审计工作底稿的含义和性质、理解编制审计工作底稿的目的和控制程序了解审计工作底稿的格式、内容和范围了解审计工作底稿的归档
** 第一节审计证据
:PROPERTIES:
:collapsed: true
:END:
注册会计师为了得出审计结论、形成审计意见而使用的所有信息，包括财务报表依据的会计记录中含有的信息和其他信息。
*** 充分性和适当性是审计证据的两个基本特征。二者缺一不可，审计证据的适当性影响审计证据的充分性。数量不能弥补质量。
:PROPERTIES:
:collapsed: true
:END:
**** 审计证据的充分性是？
:PROPERTIES:
:collapsed: true
:END:
对审计证据数量的衡量，它是指审计证据的数量要足以支持注册会计师的审计意见。
***** 审计证据的充分性受哪些因素的影响？
样本量、重大错报风险、审计证据质量
**** 审计证据的适当性是？
:PROPERTIES:
:collapsed: true
:END:
对审计证据质量的衡量，即审计证据在支持审计意见所依据的结论方面具有相关性和可靠性。相关性和可靠性是审计证据适当性的核心内容，只有既相关又可靠的审计证据才是高质量的。
***** 审计证据的相关性。审计证据的相关性是指用作审计证据的信息与审计程序的目的和所考虑的相关认定之间的逻辑联系。用作审计证据的信息的相关性可能受测试方向的影响。
***** 审计证据的可靠性。审计证据的可靠性是指审计证据的可信程度。审计证据的可靠性受其来源和性质的影响，并取决于获取审计证据的具体环境。
*** 获取审计证据的程序？（后续章节内容）
:PROPERTIES:
:collapsed: true
:END:
审计程序是指注册会计师在审计过程中的某个时间，对将要获取的某类审计证据如何进行收集的详细指令。
**** 按目的划分：风险评估程序、控制测试、实质性程序
**** 按获取手段划分：检查、观察、询问、函证、重新计算、重新执行、分析程序
** 第二节审计工作底稿
:PROPERTIES:
:collapsed: true
:END:
审计工作底稿，是指注册会计师对制定的审计计划、实施的审计程序、获取的相关审计证据，以及得出的审计结论做出的记录。审计工作底稿是审计证据的载体，是注册会计师在审计过程中形成的审计工作记录和获取的资料。它形成于审计过程，也反映整个审计过程。
*** 审计工作底稿归档后的变动
:PROPERTIES:
:collapsed: true
:END:
**** 修改或增加审计工作底稿时的情形：（ 1 ）注册会计师已实施了必要的审计程序，取得了充分、适当的审计证据并得出了恰当的审计结论，但*审计工作底稿的记录不够充分*；（ 2 ）审计报告日后，发现例外情况要求注册会计师实施新的或追加审计程序，或导致注册会计师得出新的结论。例外情况主要是指审计报告日后发现与已审财务信息相关，且在审计报告日已经存在的事实。该事实如果被注册会计师在审计报告日前获知，可能影响审计报告。例外事项可能在审计报告日后发现，也可能在财务报表报出日后发现。
**** 变动审计工作底稿时的记录要求：（ 1 ）遇到的例外情况；（ 2 ）实施的新的或追加的审计程序，获取的审计证据，得出的结论，以及对审计报告的影响；（ 3 ）对审计工作底稿作出相应变动的时间和人员，以及复核的时间和人员。
* 第八章审计抽样
:PROPERTIES:
:heading: 1
:collapsed: true
:END:
〖本章学习纲要〗 理解审计抽样、抽样风险及其对审计工作的影响
理解审计抽样步骤的运用 理解非统计抽样及其运用
理解传统变量抽样的运用
理解审计抽样在控制测试和实质性测试中的运用 理解概率比例规模抽样法（ PPS 抽样）
** 第一节审计抽样概述
:PROPERTIES:
:collapsed: true
:END:
审计抽样是指注册会计师对某类交易或账户余额中低于百分之百的项目实施审计程序，使所有抽样单元都有被选取的机会，为注册会计师针对整个总体得出结论提供合理基础。注册会计师在实施审计程序时，从审计对象总体中选取一定数量的样本进行测试，并根据测试结果，推断审计对象总体特征的一种方法。
*** 审计抽样应当具备三个基本特征：（ 1 ）对某类交易或账户余额中低于百分之百的项目实施审计程序；（ 2 ）所有抽样单元都有被选取的机会；（ 3 ）审计测试的目的是评价该账户余额或交易类型的某一特征。
*** 抽样风险和非抽样风险
:PROPERTIES:
:collapsed: true
:END:
**** 抽样风险就是抽出的样本不能代表总体的可能性，即注册会计师根据样本得出的结论，可能不同于如果对整个总体实施与样本同样的审计程序得出的结论的风险。
:PROPERTIES:
:collapsed: true
:END:
只要有抽样就存在抽样风险，抽样风险与样本量呈反向关系。控制抽样风险的唯一途径就是控制样本规模。抽样风险可以量化，只能控制，不能消除。
***** 控制测试中的抽样风险：信赖过度风险和信赖不足风险。
***** 细节测试两类抽样风险：误受风险和误拒风险
**** 非抽样风险是指由于某些与样本规模无关的因素而导致注册会计师得出错误结论的可能性。
*** 统计抽样和非统计抽样：
:PROPERTIES:
:collapsed: true
:END:
统计抽样是指同时具备下列特征的抽样方法：（ 1 ）随机选取样本；（ 2
）运用概率论评价样本结果，包括计量抽样风险。不同时具备上述两个特征的抽样方法为非统计抽样。
**** 统计抽样
:PROPERTIES:
:collapsed: true
:END:
按审计抽样所了解总体特征的不同，统计抽样的方法主要有属性抽样与变量抽样。
*****
***** 属性抽样是一种用来对总体中某一事件发生率得出结论的统计抽样方法。
属性抽样在审计中最常用的用途是测试某一控制的偏差率，以支持注册会计师评估的控制有效性。在属性抽样中，设定控制的每一次发生或偏离都被赋予同样的权重，而不管交易金额的大小。
***** 变量抽样是一种用来对总体金额得出结论的统计抽样方法。
变量抽样通常回答下列问题：金额是多少？账户是否存在错报？变量抽样在审计中的主要用途是进行实质性细节测试，以确定记录金额是否合理。
** 第二节审计抽样的基本流程
:PROPERTIES:
:collapsed: true
:END:
三个阶段进行：
第一阶段是样本设计阶段，旨在根据测试的目标和抽样总体，制定选取样本的计划。
第二阶段是选取样本阶段，旨在按照适当的方法从相应的抽样总体中选取所需的样本。
第三阶段是评价样本结果阶段，旨在根据对误差的性质和原因的分析，将样本结果推至总体，形成对总体的结论。
*** 样本设计阶段
:PROPERTIES:
:collapsed: true
:END:
**** 确定测试目标
**** 定义总体与抽样单元
:PROPERTIES:
:collapsed: true
:END:
***** 总体。总体可以包括构成某类交易或账户余额的所有项目，也可以只包括某类交易或账户余额中的部分项目。注册会计师应当确保总体的*适当性和完整性。*
**** 定义误差构成条件
注册会计师定义误差构成条件时要考虑审计程序的目标。在控制测试中，误差是指控制偏差；在细节测试中，误差是指错报。
**** 确定审计程序
*** 样本选取阶段
:PROPERTIES:
:collapsed: true
:END:
**** 确定样本规模
:PROPERTIES:
:collapsed: true
:END:
*****
**** 选取样本
:PROPERTIES:
:collapsed: true
:END:
*****
**** 对样本实施审计程序
*** 评价样本结果阶段
:PROPERTIES:
:collapsed: true
:END:
**** 分析样本误差
**** 推断总体误差
**** 形成审计结论
:PROPERTIES:
:collapsed: true
:END:
***** 推断误差+已发现的误差=推断总体误差
** 第三节审计抽样在控制测试中的应用
** 第四节审计抽样在实质性细节测试中的应用
:PROPERTIES:
:collapsed: true
:END:
*** 传统变量抽样
:PROPERTIES:
:collapsed: true
:END:
**** 1. 均值估计抽样。均值估计抽样是指通过抽样审查确定样本的平均值，再根据样本平均值推断总体的平均值和总值的一种变量抽样方法。
样本平均值：样本实际金额/样本规模 总体金额估计值样本平均值×总体规模
推断的总体错报=古计的总体实际金额_总体账面金额
**** 2 ．差额估计抽样。差额估计抽样是以样本实际金额与账面金额的平均差额来估计总体实际金额与账面金额的平均差额，然后再以这个平均差额乘以总体规模，从而求出总体的实际金额与账面金额的差额（即总体错报）的一种方法。
平均错报。样本实际金额与账面金额的差额÷样本规模推断的总体错报=平均错报×总体规模
**** 3 ，比率估计抽样。比率估计抽样是指以样本的实际金额与账面金额之间的比率关系来估计总体实际金额与账面金额之间的比率关系，然后再以这个比率去乘总体的账面金额，从而求出估计的总体实际金额的一种抽样方法。
比率=样本审定金额÷样本账面金额估计的总体实际金额。总体账面金额×比率推断的总体错报=估计的总体实际金额一总体账面金额l2632h66
*** 概率比例规模抽样（ probability-ploportional-to-size sampling ， PPS 抽样）
:PROPERTIES:
:collapsed: true
:END:
**** PPS 抽样的概念。 PPS 抽样是一种运用*属性抽样原理*对货印金额而不是对发生率得出结论的统计抽样方法。 PPS 抽样以货币单元作为抽样单元，有时也被称为金额加权抽样、货币单元抽样、累计货币金额抽样，以及综合属性变量抽样等。在该方法下总体中的每个货币单元被选中的机会相同，所以总体中某一项目被选中的概率等于该项目的金额与总体金额的比率。项目金额越大，被选中的概率就越大。但实际上注册会计师并不是对总体中的货币单元实施检查，而是对包含被选取货币单元的余额或交易实施检查。注册会计师检查的余额或交易被称为逻辑单元或实物单元。 PPS 抽样有助于注册会计师将审计重点放在较大的余额或交易。
**** 注册会计师进行抽样必须满足两个条件：第一，总体的错报率很低（低于lo ％），且总体规模在 2000 以上。第二，总体中任一项目的错报不能超过该项目的账]面金额。
**** PPS 抽样的优点包括下列 6 个方面：o ）抽样二般比传统变量抽样更易于使用。山于 PPS 抽样以属性抽样原理为基础，注册会计师可以很方便地计算样本规模，手工或使用量表评价样本结果。样本的选取可以在计算机程序或计算器的协助下进行。（ 2 ） pps 抽样可以如同大海捞针一样发现极少量的大额错报，原因在于它通过将少量的大额实物单元拆成数量众多、金额很小的货币单元，从而赋予大额项目更多的机会被选人样本。（ 3 ） PPS 抽样的样本规模无须考虑被审计金额的预计变异性。传统变量抽样的样本规模是在总体项目共有特征的变异性或标准差的基础上计算的。 PPS 抽样在确定所需的样本规模时不需要直接考虑货币金额的标准差。（ 4 ） PPS 抽样中项目被选取的概率与其货币金额大小成比例，因而生成的样本自动分层。如果使用传统变量抽样，注册会计师通常需要对总体进行分层，以减小样本规模。在 PPS 抽样中，如果项目金额超过选样间距， PPS 系统选样自动识别所有单个重大项目。（ 5 ）如果注册会计师预计错报不存在或很小， PPS 抽样的样本规模通常比传统变量抽样方法更小。（ 6 ） PPS 抽样的样本更容易设计，且可在能够获得完整的总体之前开始选取样本。
**** PPS 抽样的缺点包括下列 6 个方面：o ） pps 抽样要求总体每一实物单元的错报金额不能超出其账面金额。（ 2 ）在 PPS 抽样中，被低估的实物单元被选取的概率更低， PPS 抽样不适用于测试低估。如果注册会计师在 PPS 抽样的样本中发现低估，在评价样本时需要特别考虑。（ 3 ）对零余额或负余额的选取需要在设计时特别考虑。（ 4 ）当总体中错报数量增加时， PPS 抽样所需的样本规模也会增加。在这些情、下， PPS 抽样的样本规模可能大于传统变量抽样所需的规模。（ 5 ）当发现错报时，如果风险水平一定， PPS 抽样在评价样本时可能高估抽样险的影响，从而导致注册会计师更可能拒绝一个可接受的总体账面金额。（ 6 ）在 pps 抽样中注册会计师通常需要逐个累计总体金额。但如果相关的会讠数据以电子形式储存，就不会额外增加大量的审计成本。o625l2gl
** 思考题，7 ·控制测试中的样本结果评价是什么？8 ，细节测试中的样本结果评价是什么？g ，属性抽样的样本设计、样本选取和样本结果评价是什么？ll. PPS 抽样的样本规模确定与样本选取是什么？
* 第九章 了解被审计单位并评估重大错报风险
:PROPERTIES:
:heading: 1
:collapsed: true
:END:
〖本章学习纲要〗 掌握了解被审计单位及其环境的重要性，掌握具体了解途径
掌握内部控制及相关要素的含义 掌握了解内部控制的含义及了解的具体内容
掌握报表层次和认定层次重大错报风险的含义
了解与被审计单位管理层及治理层的沟通的主要内容
** 第一节概述
:PROPERTIES:
:collapsed: true
:END:
*** 了解被审计单位及其环境是*必要程序*
*** 风险评估程序：注册会计师了解被审计单位及其环境，目的是为了识别和评估财务报表重大错报风险。为了解被审计单位及其环境而实施的程序称为“风险评估程序”。
:PROPERTIES:
:collapsed: true
:END:
可采取的风险评估程序：询问被审计单位管理层和内部其他相关人员、实施分析程序、观察和检查。
**** 询问被审计单位管理层和内部其他相关人员
**** 实施分析程序。
分析程序是指注册会计师通过研究不同财务数据之间以及财务数据与非财务数据之间的内在关系，对财务信息作出评价。分析程序还包括调查识别出的、与其他相关信息不一致或与预期数据严重偏离的波动和关系。
**** 观察和检查。
** 第二节了解被审计单位及其环境
:PROPERTIES:
:collapsed: true
:END:
注册会计师应当从下列方面了解被审计单位及其环境：（ 1
）行业状况、法律环境与监管环境以及其他外部因素；（ 2
）被审计单位的性质；（ 3 ）被审计单位对会计政策的选择和运用；（ 4
）被审计单位的目标、战略以及可能导致重大错报风险的相关经营风险；（ 5
）被审计单位财务业绩的衡量和评价；（ 6 ）被审计单位的内部控制。
*** 良好的*治理结构*可以对被审计单位的经营和财务运作实施有效的监督，从而降低财务报表发生重大错报的风险。注册会计师应当了解被审计单位的治理结构，例如董事会的构成情况、董事会内部是否有独立董事；治理结构中是否设有审计委员会或监事会及其运作情况。注册会计师应当考虑治理层是否能够在独立于管理层的情况下对被审计单位事务（包括财务报告）作出客观判断。
** 第三节了解被审计单位的内部控制
:PROPERTIES:
:collapsed: true
:END:
*** 一、内部控制的内涵和要素
:PROPERTIES:
:collapsed: true
:END:
**** 内部控制是被审计单位为了合理保证财务报告的可靠性、经营的效率和效果以及对法律法规的遵守，由治理层、管理层和其他人员设计与执行的政策及程序。
**** 内部控制包括下列要素：（ 1) 控制环境；（ 2 ）风险评估过程；（ 3 ）与财务报告相关的信息系统与沟通； （4）控制活动；（ 5 ）对控制的监督。
*** 二、与审计相关的控制。注册会计师需要了解和评价的内部控制只是与财务报表审计相关的内部控制，并非被审计单位所有的内部控制。
为实现财务报告可靠性目标设计和实施的控制、其他与审计相关的控制
*** 三、对内部控制了解的深度
:PROPERTIES:
:collapsed: true
:END:
对内部控制了解的深度，是指在了解被审计单位及其环境时对内部控制了解的程度。包括评价控制的设计，并确定其是否得到执行，但不包括对控制是否得到一贯执行的测试。
**** （一）评价控制的设计（二）获取控制设计和执行的审计证据（三）了解内部控制的步骤（四）了解内部控制与测试控制运行有效性的关系
*** 四、内部控制的人工和自动化成分。
内部控制的人工控制和自动化控制各有哪些特征？适用范围如何？分别存在哪些风险？
*** 五、内部控制的局限性
*** 六、控制环境
:PROPERTIES:
:collapsed: true
:END:
**** （一）控制环境的含义
控制环境包括治理职能和管理职能，以及治理层和管理层对内部控制及其重要性的态度、认识和措施。
**** （二）对诚信和道德价值观念的沟通与落实；（三）对胜任能力的重视；（四）治理层的参与程度；（五）管理层的理念和经营风格；（六）组织结构及职权与责任的分配；（七）人力资源政策与实务
*** 七、被审计单位的风险评估过程
*** 八、信息系统与沟通
*** 九、控制活动
:PROPERTIES:
:collapsed: true
:END:
**** 控制活动是指有助于确保管理层的指令得以执行的政策和程序，包括授权、业绩评价、信息处理、实物控制和职责分离等相关的活动。
**** 对被审计单位主要是了解一般控制活动，考虑的主要因素包括：
（1）对被审计单位的主要经营活动是否都有必要的控制政策和程序；
（2）管理层在预算、利润和其他财务和经营业绩方面是否都有清晰的目标，在被审计单位内部，是否对这些目标加以清晰的记录和沟通，并且积极地对其进行监控；
（3）是否存在计划和报告系统，以识别与目标业绩的差异，并向适当层次的管理层报告该差异；
（4）是否由适当层次的管理层对差异进行调查，并及时采取适当的纠正措施； （
5
）不同人员的职责应在何种程度上相分离，以降低舞弊和不当行为发生的]风险；
（ 6 ）会计系统中的数据是否与实物资产定期核对； （ 7
）是否建立了适当的保护措施，以防止未经授权接触文件、记录和资产； （ 8
）是否存在信息安全职能部门负责监控信息安全政策和程序。
*** 十、对控制的监督
:PROPERTIES:
:collapsed: true
:END:
**** （一）对控制的监督的含义
对控制的监督是指被审计单位评价内部控制在一段时间内运行有效性的过程，该过程包括及时评价控制的设计和运行，以及根据情况的变化采取必要的纠正措施。
** 第四节评估重大错报风险
:PROPERTIES:
:collapsed: true
:END:
*** 一、识别和评估购务报表层次以及认定层次的重大错报风险
:PROPERTIES:
:collapsed: true
:END:
**** （一）识别和评估重大错报风险的审计程序
1. 在了解被审计单位及其环境的整个过程中识别风险，并考虑各类交易、账户余额、列报。2
   ，结合对拟测试的相关控制的考虑，将识别的风险与认定层次可能发生错报的领域相联系。3
   ．评估识别出的风险，并评估其是否更广泛地与财务报表整体相关，进而潜在地影响多次认定。4。考虑发生错报的可能性（包括发生多项错报的可能性），以及潜在错报的重大程度是否足以导致重大错报。
*** 什么是特别风险？哪些事项容易形成特别风险？思如何理解报表层次和认定层次的重大错报风险？
*** 重大错报风、别风險
** 第五节沟通与记录
** ll. 注册会计师是否需要与被审计单位管理层和治理层沟通在了解和测试内部控制过程中发现的被审计单位内部控制存在的重大缺陷？
* 第十章针对评估的重大错报风险实施的程序
:PROPERTIES:
:heading: 1
:collapsed: true
:END:
〖本章学习纲要〗 掌握针对财务报表层次重大错报风险采取的总体应对措施
掌握针对认定层次重大错报风险采取的进一步审计程序的含义、性质、和范围
掌握控制测试的含义、性质、时间和范围
掌握实质性程序的含义、性质、时间和范围 理解发现某项错报后的处理方法时回
** 第一节针对财务报表层次重大错报风险的总体应对措施
:PROPERTIES:
:collapsed: true
:END:
*** 可采取的总体应对措施
1. 向项目组强调在收集和评价审计证据过程中保持职业怀疑态度的必要性。2．分派更有经验或具有特殊技能的审计人员，或利用专家的工作。3
   ，提供更多的督导。4
   ．在选择进一步审计程序时，应当注意使某些程序不被管理层预见或事先了解。5
   ．对拟实施审计程序的性质、时间和范围作出总体修改。
*** 应对措施对进一步审计程序方案产生的影响
拟实施进一步审计程序的总体方案包括实质性方案和综合性方案。其中，实质性方案是指注册会计师实施的进一步审计程序以实质性程序为主；综合性方案是指注册会计师在实施进一步审计程序时，将控制测试与实质性程序结合使用。当评估的财务报表层次重大错报风险属于高风险水平（并相应采取更强调审计程序不可预见性、重视调整审计程序的性质、时间和范围等总体应对措施）时，拟实施进一步审计程序的总体方案往往更倾向于实质性方案。
** 第二节 针对认定层次重大错报风险的进一步审计程序
:PROPERTIES:
:collapsed: true
:END:
*** 什么是进一步审计程序？
进一步审计程序相对风险评估程序而言，是指注册会计师针对评估的各类交易、账户余额、列报（包括披露，下同）认定层次重大错报风险实施的审计程序，包括控制测试和实质性程序。
*** 如何理解进一步审计程序的性质、时间和范围？
:PROPERTIES:
:collapsed: true
:END:
注册会计师应当针对所评估的认定层次重大错报风险来设计和实施进一步审计程序，包括审计程序的性质、时间和范围。注册会计师设计和实施的进一步审计程序的性质、时间和范围，应当与评估的认定层次重大错报风险具备明确的对应关系。注册会计师实施的审计程序具有目的性和针对性，有的放矢地配置审计资源，提高审计效率和效果。
**** 进一步审计程序的性质，是指进一步审计程序的目的和类型。其中，进一步审计程序的目的包括通过实施控制测试以确定内部控制运行的有效性，通过实施实质性程序以发现认定层次的重大错报；进一步审计程序的类型包括*检查、观察、询问、函证、重新计算、重新执行和分析程序。*
**** 进一步审计程序的时间是指注册会计师何时实施进一步审计程序，或审计证据适用的期间或时点。
**** 进一步审计程序的范围是指实施进一步审计程序的数量，包括抽取的样本量，对某项控制活动的观察次数等。
** 第三节控制测试
:PROPERTIES:
:collapsed: true
:END:
什么是内部控制测试？何时必须实施控制测试？如何理解内部控制测试的性质、时间和范围？内部控制测试和了解内部控制有何异同点？
*** 控制测试是指测试控制运行的有效性，这一概念需要与“了解内部控制”进行区分。“了解内部控制”包含两层含义：一是评价控制的设计；二是确定控制是否得到执行。测试控制运行的有效性与确定控制是否得到执行所需获取的审计证据是不同的。
*** 作为进一步审计程序的类型之一，控制测试*并非在任何情况下都需要实施*。当存在下列情形之一时，注册会计师应当实施控制测试：（ 1 ）在评估认定层次重大错报风险时，预期控制的运行是有效的；（ 2 ）仅实施实质性程序不足以提供认定层次充分、适当的审计证据。
*** 如何理解内部控制测试的性质、时间和范围？
:PROPERTIES:
:collapsed: true
:END:
**** 控制测试的性质是指控制测试所使用的审计程序的类型及其组合。
:PROPERTIES:
:collapsed: true
:END:
了解内部控制和控制测试都包括的程序：包括询问、观察、检查和穿行测试、控制测试还包括重新执行。
***** 穿行测试：
**** 如前所述，控制测试的时间包含两层含义：一是何时实施控制测试；二是测试所针对的控制适用的时点或期间。注册会计师应当根据控制测试的目的确定控制测试的时间，并确定拟信赖的相关控制的时点或期间。
**** 对于控制测试的范围，其含义主要是指某项控制活动的测试次数。
** 第四节实质性程序
:PROPERTIES:
:collapsed: true
:END:
什么是实质性程序？如何理解实质性程序的性质、时间和范围？什么是会计分录测试？注册会计师应如何设计和实施会计分录测试？
*** 实质性程序是指注册会计师针对评估的重大错报风险实施的直接用以发现认定层次重大错报的审计程序。实质性程序包括对各类交易、账户余额、列报的细节测试以及实质性分析程序。
*** 实质性程序的性质，是指实质性程序的类型及其组合。实质性程序的两种基本类型包括细节测试和实质性分析程序。
:PROPERTIES:
:collapsed: true
:END:
**** 细节测试是对各类交易、账户余额、列报的具体细节进行测试，目的在于直接识别财务报表认定是否存在错报。
**** 实质性分析程序从技术特征上仍然是分析程序，主要是通过研究数据间关系评价信息，只是将该技术方法用作实质性程序，即用以识别各类交易、账户余额、列报及相关认定是否存在错报。
**** 细节测试适用于对各类交易、账户余额、列报认定的测试，尤其是对存在或发生、计价认定的测试；对在一段时期内存在可预期关系的大量交易，注册会计师可以考虑实施实质性分析程序。
*** 会计分录测试，是指注册会计师针对被审计单位日常会计核算过程中做出的会计分录，以及编制财务报表过程作出的其他调整实施的测试。
:PROPERTIES:
:collapsed: true
:END:
**** 会计分录测试的目的，是为了应对被审计单位管理层凌驾于控制之上的风险。
**** 会计分录测试的对象是与被审计财务报表相关的所有会计分录和其他调整，包括编制合并报表时做出的调整分录和抵销分录。这可以分为三种类型：标准会计分录。非标准会计分录。其他调整。‘
**** 注册会计师对会计分录测试的准备。
（ 1
）向参与财务报告过程的人员询问与处理会计分录和其他调整相关的不恰当或异常的活动；（
2 ）选择在报告期末做出的会计分录和其他调整；（ 3
）考虑是否有必要测试整个会计期间的会计分录和其他调整。
**** 会计分录测试的具体步骤。
（ 1
）了解被审计单位的财务报告流程，以及针对会计分录和其他调整已实施的控制，必要时，测试相关控制的运行有效性；（
2 ）确定待测试会计分录和其他调整的总体，并测试总体的完整性；（ 3
）从总体中选取待测试的会计分录及其他调整；（ 4
）测试选取的会计分录及其他调整，并记录测试结果。
** 第五节审计证据的评价与记录
* 第十一章财务报表审计中对舞弊的考虑
:PROPERTIES:
:heading: 1
:collapsed: true
:END:
理解注册会计师在财务报表审计中对舞弊的考虑责任 理解舞弊的特征
理解舞弊对财务报表审计产生的困难
理解对舞弊导致的财务报表重大错报风险的评估和应对思路
理解发现某项错报后的处理方法
** 第一节概述
** 第二节舞弊的特征
** 第三节管理层、治理层的责任和注册会计师的责任
** 第四节审计的固有限制与职业怀疑态度
** 第五节舞弊导致的重大错报风险的识别与评估
** 第六节应对舞弊导致的重大错报风险
** 第七节评价审计证据
** 第八节与管理层、治理层和监管机构的沟通
** 第九节无法继续执行审计业务时的考虑
* 第十二章函证
:PROPERTIES:
:heading: 1
:collapsed: true
:END:
〖本章学习纲要〗 理解函证的含义 掌握函证决策的内容 掌握询证函设计的要点
掌握函证的控制和评价
** 第一节函证的含义与决策
:PROPERTIES:
:collapsed: true
:END:
1. 函证程序可以用于哪些报表项目？应向哪些第三方函证？2
   ．进行函证决策时审计人员应考虑哪些因素？
*** 函证是指注册会计师直接从第三方〈被询证者）获取书面答复作为审计证据的过程。
函证的主体是注册会计师，但是询证函通常以被审计单位的名义编制和发出，函证的对象是拥有相关信息的第三方，函证的目的是通过向函证对象提出书面请求，要求提供影响财务报表认定的特定项目的信息。
函证包括相互联系的两个步骤：一是向拥有相关信息的第三方提出书面请求并获得回函；二是在得到第三方对有关信息和现存状况的声明后注册会计师须进行跟进和评价。
*** 函证的决策是指围绕是否进行函证和如何函证所进行的一系列的审计判断。
:PROPERTIES:
:collapsed: true
:END:
函证决策的内容包括函证决策考虑的因素、函证程序实施的范围、函证的时间、函证的内容以及管理层要求不实施函证时的处理。
**** 函证决策考虑的因素：评估的认定层次重大错报风险、实施其他审计程序获取的审计证据如何将检查风险降至可接受的水平。
**** 范围应当考虑：评估的认定层次重大错报风险、实施控制测试的结果
****
** 第二节询证函的设计
:PROPERTIES:
:collapsed: true
:END:
*** 询证函设计的一般原则
注册会计师应当根据特定审计目标设计询证函。询证函的设计服从于审计目标的需要。
*** 设计询证函需要考虑的因素
函证的方式、识别出的重大错报风险、询证函的版面设计和表述方式、以往审计或类似业务的经验、沟通的方式、管理层对被询证者的授权或是否鼓励被询证者向注册会计师回函、预期的被询证者确认或提供信息的能力
*** 积极的函证方式
积极的函证方式又称肯定式函证，是指注册会计师要求被询证者直接向注册会计师回复，表明是否同意询证函所列示的信息，或填列所要求的信息的一种询证方式。
*** 消极的函证方式
:PROPERTIES:
:collapsed: true
:END:
消极的函证方式又称否定式函证，是指注册会计师要求被询证者仅在不同意询证函列示信息时才直接向注册会计师回复的一种询证方式。
**** 当同时存在下列情况时，注册会计师可考虑采用消极的函证方式：（ 1 ）重大错报风险评估为低水平；〈 2 ）涉及大量余额较小的账户；（ 3 ）预期不存在大量的错误；（ 4 ）没有理由相信被询证者不认真对待函证。
*** 询证函的内容和格式
** 第三节函证的实施与评价
:PROPERTIES:
:collapsed: true
:END:
3 ，审计人员应如何进行函证过程的控制？4
，审计人员应如何评价函证证据的充分性和适当性？
*** 审计准则规定，注册会计师应当采取下列措施对函证实施过程进行控制：
1. 将被询证者的名称、地址与被审计单位有关记录核对；2．将询证函中列示的账户余额或其他信息与被审计单位有关资料核对；3．在询证函中指明直接向接受审计业务委托的会计师事务所回函；4．询证函经被审计单位盖章后，由注册会计师直接发出；5．将发出询证函的情况形成审计工作记录；6．将收到的回函形成审计工作记录，并汇总统计函证结果
***
* 第十三章存货监盘
:PROPERTIES:
:heading: 1
:collapsed: true
:END:
〖本章学习纲要〗 理解存货监盘的含义。
明确在存货监盘中被审计单位管理层和注册会计师的责任
掌握编制存货监盘计划时的考虑因素和相应审计程序
掌握存货监盘计划的主要内容
掌握存货监盘程序的具体步骤，注意实施存货监盘程序应特别关注的问题，了解盘点结束时的后续工作
掌握存货监盘结果对审计报告的影响
** 第一节存货监盘概述
:PROPERTIES:
:collapsed: true
:END:
存货监盘是指注册会计师现场观察被审计单位存货的盘点，并对已盘点的存货进行适当检查。存货监盘是一项复合程序，是观察程序和检查程序的结合运用。
*** 存货监盘的目的是获取有关存货数量和状况的审计证据。存货监盘针对的主要是存货的存在性认定、完整性认定和所有权认定，存货数量的准确性直接影响到这三个认定。
*** 按照审计准则的规定，定期盘点存货、合理确定存货的数量和状况是*被审计单位管理层的责任*；实施存货监盘，获取有关期末存货数量和状况的充分、适当的审计证据是*注册会计师的责任*。
** 第二节存货监盘计划
:PROPERTIES:
:collapsed: true
:END:
*** 编制存货监盘计划时的考虑因素和相应审计程序
（一）了解存货的内容、性质、各存货项目的重要程度及存放场所
（二）了解与存货相关的内部控制
（三）评估与存货相关的重大错报风险和重要性
（四）查阅以前年度的存货监盘工作底稿 （五）实地察看存货的存放场所
（六）利用专家或其他注册会计师的工作
（七）复核或与管理层讨论其存货盘点计划
*** 存货监盘计划的主要内容
包括下列主要内容：（ 1 ）存货监盘的目标、范围及时间安排；（ 2
）存货监盘的要点及关注事项；（ 3 ）参加存货监盘人员的分工；（ 4
）检查存货的范围。
** 第三节存货监盘程序
:PROPERTIES:
:collapsed: true
:END:
*** 在存货盘点现场实施监盘时，注册会计师应当实施下列审计程序：（ 1 ）评价管理层用以记录和控制存货盘点结果的指令和程序；（ 2 ）观察管理层制定的盘点程序的执行情况；（ 3 ）检查存货；（ 4 ）执行抽盘。
*** 在存货监盘程序中，无论是观察程序还是检查程序，注册会计师都*应当特别关注存货的移动情况、存货的状况以及存货的截止情况。*
:PROPERTIES:
:collapsed: true
:END:
**** 特殊存货与可采用的应对
:PROPERTIES:
:collapsed: true
:END:
*****
*** 注册会计师在存货盘点结束时的后续工作
通常包括再次观察现场并检查盘点表单、 复核盘点结果汇总记录、
关注盘点日与资产负债表日之间存货的变动情况、
存货盘点结果与永续盘存记录之间出现重大差异的处理、
盘点方式及其结果无效时的处理等。
*** 在存货监盘过程中，可能由哪些原因导致无法实施存货监盘？这时注册会计|师应当实施哪些替代程序？
** 第四节存货监盘结果对审计报告的影响
:PROPERTIES:
:collapsed: true
:END:
一般必须区分考虑审计范围受到限制、被审计单位拒绝调整以及首次接受委托三种情形。
*** 审计范围受到限制
如果虽影响重大，但不至于出具无法表示意见的审计报告，则应当出具保留意见的审计报告；如果审计范围受到限制可能产生的影响非常重大而广泛，以至于无法对财务报表发表审计意见，注册会计师应当出具无法表示意见的审计报告。
*** 被审计单位拒绝调整
如果虽影响重大，但不至于出具否定意见的审计报告，则应当出具保留意见的审计报告；如果拒绝调整事项影响重大而广泛，导致被审计单位财务报表不能在所有重大方面公允地反映被审计单位的财务状况、经营成果和现金流量，注册会计师应当出具否定意见的审计报告。
*** 首次接受委托
如果首次接受委托，按照审计准则的要求实施审计程序后，仍未能获取有关本期期初存货余额的充分、适当的审计证据，注册会计师应当考虑出具保留意见或无法表示意见的审计报告。
* 第十四章 分析程序
:PROPERTIES:
:heading: 1
:collapsed: true
:END:
【本章学习纲要】 掌握分析程序的含义 了解分析程序的性质
掌握分析程序的目的 理解分析程序的应用原则与要求
** 第一节概述
:PROPERTIES:
:heading: 2
:collapsed: true
:END:
*** 分析程序是指注册会计师通过研究不同财务数据之间以及财务数据与非财务数据之间的内在关系，对财务信息作出评价。
:PROPERTIES:
:collapsed: true
:END:
分析程序还包括必要时对识别出的、与其他相关信息不一致或与预期值差异重大的波动和关系进行调查。
**** *趋势分析法*主要是通过对比两期或连续数期的财务或非财务数据，确定其增减变动的方向、数额或幅度，以掌握有关数据的变动趋势或发现异常的变动。
**** *比率分析法*主要是结合其他有关信息，将同一报表内部或不同报表间的相关项目联系起来，通过计算比率，反映数据之间的关系，用以评价被审计单位的财务信息。
*** 分析程序的目的
（一）用作风险评估程序，以了解被审计单位及其环境；（二）用作实质性程序，以提高审计工作的效率；（三）在审计结束或临近结束时对财务报表进行总体复核
** 第二节分析程序的应用原则与要求
:PROPERTIES:
:heading: 2
:collapsed: true
:END:
*** 用作风险评估程序时的分析程序的原则和要求：强制要求
在运用分析程序时，注册会计师应重点关注关键的账户余额、趋势和财务比率关系等方面，对其形成一个合理的预期，并与被审计单位记录的金额、依据记录金额计算的比率或趋势相比较。
*** 用作实质性程序时的分析程序的原则和要求：非必须，某些项目不适用，不能替代细节测试
:PROPERTIES:
:collapsed: true
:END:
**** 简述实质性分析程序运用的步骤
:PROPERTIES:
:collapsed: true
:END:
包括以下几个步骤：（ 1
）识别需要运用分析程序的账户余额或交易；（2）确定期望值；（ 3
）确定可接受的差异额；（ 4 ）识别需要进一步调查的差异；（ 5
）调查异常数据关系；（ 6 ）评估分析程序的结果。
***** 可接受差异
可接受的差异额是指已记录金额与预期值之间的差额，注册会计师认为该差额无须进一步的调查。
*** 用作总体复核的分析程序的原则和要求：强制要求
* 第十五章审计报告
:PROPERTIES:
:heading: 1
:collapsed: true
:END:
** 第一节审计报告概述
** 第二节审计报告的基本内容
** 第三节无保留意见的审计报告
** 第四节在审计报告中沟通关键审计事项
** 第五节非无保留意见审计报告
** 第六节在审计报告中增加强调事项段和其他事项段
* 第十六章内部控制审计
:PROPERTIES:
:heading: 1
:collapsed: true
:END:
** 第一节内部控制审计概述
** 第二节业务约定书与计划审计工作
** 第三节实施审计工作
** 第四节连续审计与集团审计的特殊考虑
** 第五节内部控制缺陷的评价
** 第六节完成审计工作与出具内部控制审计报告
** 第七节对整合审计的进一步考虑
** 第八节项目质量控制复核与审计工作记录
* 第十七章注册会计师的其他业务
:PROPERTIES:
:heading: 1
:collapsed: true
:END:
** 第一节注册会计师的特殊审计领域
:PROPERTIES:
:collapsed: true
:END:
*** 特殊目的审计业务，是指注册会计师接受委托，对下列财务信息进行审计并出具审计报告的业务：l. 按照企业会计准则和相关会计制度以外的其他基础（以下简称特殊基础）编制的财务报表。特殊基础通常包括下列基础：计税基础、收付实现制基础、监管机构的报告要求。2 ．财务报表的组成部分，包括财务报表特定项目、特定账户或特定账户的特定内容。注册会计师可能接受委托对财务报表的一个或多个组成部分发表审计意见。3 ，合同的遵守情况。注册会计师可能接受委托对被审计单位合同中有关财务会计条款的遵守情况发表审计意见。如对贷款合同遵守情况发表审计意见。4．简要财务报表。注册会计师可能接受委托对被审计单位依据已审计财务报表编制的简要财务报表发表审计意见。
*** 验资，是指注册会计师依法接受委托，对被审验单位注册资本的实收情况或注册资本及实收资本的变更情况进行审验，并出具验资报告。
** 第二节审阅业务和其他鉴证业务
:PROPERTIES:
:collapsed: true
:END:
*** 财务报表审阅的目标，是注册会计师在实施审阅程序的基础上，说明是否注意到某些事项，使其相信财务报表没有按照适用的会计准则的规定编制，未能在所有重大方面公允反映被审阅单位的财务状况、经营成果和现金流量。
*** 预测性财务信息是指被审核单位依据对未来可能发生的事项或采取的行动的假设而编制的财务信息。
** 重要术语：特殊目的审计业务、验资、财务报表审阅、预测性财务信息、审核报告
** 思考题：1 ，如何理解特殊目的审计业务的总体要求和发表审计意见的要求？对特殊目的审计业务出具的审计报告与对财务报表审计出具的审计报告有什么不同？