* * [[[https://www.thepaper.cn/newsDetail_forward_14590173][游戏论·文化的逻辑︱当代电子游戏“国潮”的四十年流变_思想市场_澎湃新闻-The Paper]]
:PROPERTIES:
:heading: true
:collapsed: true
:labels: [[Games]]
:date-published: [[2021/09/25]]
:END:
** * ### 高亮
collapsed:: true
*** * 
id:: 715fb57f-1920-43ab-a66e-fcccbc976641
#+BEGIN_QUOTE


#+END_QUOTE
* * [[[https://utgd.net/article/20107][一种低技术的阅读批注思路 - #UNTAG]]
:PROPERTIES:
:heading: true
:collapsed: true
:author: Minja
:labels: [[PKM]]
:date-published: [[2023/12/06]]
:END:
** * ### 高亮
collapsed:: true
*** * 
id:: f87f0361-3f5c-4020-bd55-19a351ea99e9
#+BEGIN_QUOTE
阅读活动的私人化，常常陷入对工具的过度崇拜，就像古代奴隶主失饪不食、割不正不食、不得其酱不食一样，笔墨稍有不顺，阅读器略有卡顿，则弃之不用。如此读书，惟读者自己损失大矣。

#+END_QUOTE
*** * 
id:: 20b7de3f-7cd6-4fd2-a01a-99b07499786c
#+BEGIN_QUOTE
几乎所有阅读器都能够满足阅读需要，真正要调整的，不是工具，而是使用标注工具的习惯。

#+END_QUOTE
*** * 
id:: 0faa3fd6-81d1-4c65-9b72-07fba178e469
#+BEGIN_QUOTE
沉心阅读之人，则以笔为武器，剑及履及之处，削下真知灼识，吞之为自己血肉——而批注时的刀光剑影，则无需见于将来。

#+END_QUOTE
*** * 
id:: 3cca7b6a-654b-486a-a50e-4f5be2e1a2e7
#+BEGIN_QUOTE
* 红色，主语，关键词；
* 蓝色，谓语，理论；
* 黄色，宾语，案例；
* 紫色，强调

#+END_QUOTE
*** * 
id:: b2782797-9905-45cb-b26c-b6923c2bc3c8
#+BEGIN_QUOTE
阅读判决书，可划出事实、法律、说理和判决结果；琢磨推理小说，可区分证词、证据和推论；研读方法论著作，又需注意历史事实、作者观点和批评对象……不同情景，几种基础颜色均能应对。重要的不是选出一套颜色，而是留意自己涉猎的内容类型，然后量身打造几套标注方案。

#+END_QUOTE
*** * 
id:: 1c1ed695-6d47-4952-8d36-07cb0b9fb979
#+BEGIN_QUOTE
* 高亮线：主语，关键词；
* 下划线：谓语，理论；
* 波浪线：宾语，案例。

#+END_QUOTE
*** * 
id:: 2710f685-0f4e-4779-9898-2f557d4f7043
#+BEGIN_QUOTE
需要强调与亟待处理之处，则尽可能融入任务管理工具（即便只是抄到便签上），总之不将后续需要整理的段落留在原始文件中。

#+END_QUOTE
*** * 
id:: 556fe5ff-5b6f-4bba-b5be-e42b16898607
#+BEGIN_QUOTE
下划线边缘直接标明段落属性，就能区分语义。如有存档需要，则随后再依据标注提示，把划线部分誊到电脑上。

#+END_QUOTE
*** * 
id:: 68b23c47-d229-447f-b9a3-752be3f63d45
#+BEGIN_QUOTE
若愿意同时使用高亮划线与文字标注，则可绕过高亮之顽疾：无法搜索。

#+END_QUOTE
*** * 
id:: f8f88c0e-4678-4b0e-bcf4-b01ff4dc1767
#+BEGIN_QUOTE
之所以选取 `FCT` 这等晦涩拼写，并非给自己没事找事，而是为与原文区分，不得已选用英文中几不可能出现的拼写组合。

#+END_QUOTE
* * [[[https://utgd.net/article/20459][如何利用纸笔笔记：将其视为阅读笔记的先遣队 - #UNTAG]]
:PROPERTIES:
:heading: true
:collapsed: true
:author: Minja
:labels: [[PKM]]
:date-published: [[2023/11/07]]
:END:
** * ### 高亮
collapsed:: true
*** * 
id:: 7b7aa153-70a3-4db2-ae53-8d129cff68e5
#+BEGIN_QUOTE
原研哉曾指出，电脑解放了纸，让设计师可以更关注纸张本身的物理属性，而不必在承载图文信息上和电脑一较高下
 #[[VPT]] 
#+END_QUOTE
*** * 
id:: 308df3cc-0bfd-4771-9882-5980943cf589
#+BEGIN_QUOTE
软件成了第二大脑，负责存储；而**纸笔从存储的巨大压力中解放出来**，回归快速捕捉与初步加工的原始用途。

#+END_QUOTE
*** * 
id:: f4a16759-10a3-4b5c-9fc9-d4369d4e6560
#+BEGIN_QUOTE
从先遣队或者游击队的隐喻出发，管见以为，最合适的书写介质是**未经装订的纸片**，比如可以轻松放进口袋的索引卡（Index Card）、可贴在墙上的便利贴[\[1\]](#fn1)，或者将普通A4纸对折裁开后得到的纸片（具体对折几次，端视你用来记录哪类内容）。
 #[[VPT]] 
#+END_QUOTE
*** * 
id:: 8476ea15-6d75-434d-81ab-5a0680211226
#+BEGIN_QUOTE
纸片上的大纲笔记，并非其他笔记的清单，而是**手头所读材料的索引**。

#+END_QUOTE
*** * 
id:: 9d61b928-6640-40cc-82c4-92370e69d08a
#+BEGIN_QUOTE
具体到操作细节上，我使用两种方式的编码指出。一种是单纯**页码加位置**，比如第42页从上往下数第三段，编码就是`42C`，要是自然段太多，那就从下往上数，比如用`42（-1）`表示第四十二页最后一段。

#+END_QUOTE
* * [[[https://utgd.net/article/20409][Osprey 工具收纳包｜URBAN TOOL - #UNTAG]]
:PROPERTIES:
:heading: true
:collapsed: true
:author: Minja
:labels: [[GDS]]
:date-published: [[2023/12/06]]
:END:
** * ### 高亮
collapsed:: true
*** * 
id:: ea5938ef-03a3-4810-85fb-9c0ac517a0f4
#+BEGIN_QUOTE
工程师J· E·戈登曾指出，这种以厚重为可靠的设计思路并不可取，最终往往既笨重又不牢靠。

#+END_QUOTE
* [[[https://utgd.net/article/20510/][Calibre 巴别图书馆计划（六）：用书目降低阅读负担 - #UNTAG]]
:PROPERTIES:
:heading: true
:collapsed: true
:author: Minja
:labels: [[RSS]][[PKM]]
:date-published: [[2023/12/06]]
:END:
** ### 高亮
:PROPERTIES:
:collapsed: true
:END:
*** :PROPERTIES:
:END:
#+BEGIN_QUOTE
盖图书馆断非书堆，不是找一个文件夹、往里面塞满一堆书籍就大功告成。是否备有作者、出版社、发表年份等信息？能不能跟随阅读进度，给书籍打上自定义的标签？可不可以快速组织一个书单，牵出一串相关书籍？这些都是图书馆的本职功能，而移动端目前不能，在相当长一段时间里估计力有未逮。

#+END_QUOTE
*** :PROPERTIES:
:END:
#+BEGIN_QUOTE
自图书入库之时，阅读便随之开始，他必须了解图书所属的领域，知道作者的年代背景，最好还了解一些发行商和出版年份。读书人的目录，不仅服务于找到某本具体的书，更应引导接下来的书籍利用。功夫在于把书读厚读薄之间，而不只是把书排列整齐——这里的阅读是广义的，不只是为学术进行的阅读，也包括放松但不放纵的阅读，比如一个推理小说爱好者，也需要知道流派、手法、结构甚至诡计类型。就连漫画也值得认真对待，可以辅以书目，而非抓到什么资源就胡乱咽下去。

#+END_QUOTE
*** :PROPERTIES:
:END:
#+BEGIN_QUOTE
面对手机屏幕，表格的思维定势应当刨除，清单才是更适合竖长屏幕的格式；而基础的清单又不足以容纳丰富的书籍信息，理想的工具应当是带层级的清单或大纲——任务管理工具就此进入视野。

#+END_QUOTE
*** 思考：为什么靠谱的目录必须要通读？
:PROPERTIES:
:END:
#+BEGIN_QUOTE
编辑目录并非一蹴而就，而是要随着阅读不断深入，或者说没有阅读，尤其是通读，那就没有靠谱的目录。

#+END_QUOTE
*** 开始思想活动前的准备与雕塑油画皆相类：原料、工具。
:PROPERTIES:
:END:
#+BEGIN_QUOTE
盖读书并非囫囵吞枣，甚至需要刻意与原稿原件保持一定距离（这里的原件也包括电子文档）。出门在外，更重要的是检索馆藏条目，而非一头扎进书堆。讨论一个新课题，或者分析一个疑难案件，第一件事情不是马上钻进书堆，而是先从随身携带的书目中调出可能有用的条目，摸索可能的方向。
 #[[PKM]] 
#+END_QUOTE
*** 开始一场思想活动前，总要为自己准备好写写画画的工具，最好再来若干本参考资料随时以资查阅。好比制作雕塑的原料与工具。
:PROPERTIES:
:END:
#+BEGIN_QUOTE
出门在外，更重要的是检索馆藏条目，而非一头扎进书堆。讨论一个新课题，或者分析一个疑难案件，第一件事情不是马上钻进书堆，而是先从随身携带的书目中调出可能有用的条目，摸索可能的方向。
 #[[PKM]] 
#+END_QUOTE
*** :PROPERTIES:
:END:
#+BEGIN_QUOTE
制作目录，其中项目都应来自亲手编制\[^我拒绝使用豆瓣书籍信息插件，坚持手动录入并校对数据。\]，拿出来的文献多少有点把握，交谈的时候便能对答如流，而不是毫无底气、全靠数量诈别人——苟若太依赖书库，总是大手一挥，以为数据库够大就必然质量喜人，其结果往往比百度搜索的第一页好不了太多。

#+END_QUOTE
* [[[https://utgd.net/article/20459][如何利用纸笔笔记：将其视为阅读笔记的先遣队 - #UNTAG]]
:PROPERTIES:
:heading: true
:collapsed: true
:author: Minja
:labels: [[PKM]]
:date-published: [[2023/11/07]]
:END:
** ### 高亮
:PROPERTIES:
:collapsed: true
:END:
*** :PROPERTIES:
:END:
#+BEGIN_QUOTE
原研哉曾指出，电脑解放了纸，让设计师可以更关注纸张本身的物理属性，而不必在承载图文信息上和电脑一较高下

#+END_QUOTE
*** :PROPERTIES:
:END:
#+BEGIN_QUOTE
软件成了第二大脑，负责存储；而**纸笔从存储的巨大压力中解放出来**，回归快速捕捉与初步加工的原始用途。

#+END_QUOTE
*** :PROPERTIES:
:END:
#+BEGIN_QUOTE
纸片上的大纲笔记，并非其他笔记的清单，而是**手头所读材料的索引**。

#+END_QUOTE
* [[[https://necromanov.wordpress.com/2023/10/23/%E9%80%89%E6%8B%A9%E7%9A%84%E8%83%9C%E5%88%A9%EF%BC%9A%E5%8D%9A%E5%BE%B73%EF%BC%8C%E6%98%9F%E7%A9%BA%E4%B8%8E%E8%A7%86%E9%A2%91%E4%BC%A0%E6%92%AD%E6%97%B6%E4%BB%A3%E7%9A%84rpg%E8%AE%BE%E8%AE%A1/][选择的胜利：博德3，星空与视频传播时代的RPG设计 | 旗舰评论——战略航空军元帅的旗舰]]
:PROPERTIES:
:heading: true
:collapsed: true
:author: 发表于
:labels: [[Games]][[RSS]]
:date-published: [[2023/10/23]]
:END:
** ### 高亮
:PROPERTIES:
:collapsed: true
:END:
*** :PROPERTIES:
:END:
#+BEGIN_QUOTE
核心玩家喜欢的那些元素：宏大复杂的世界观和对话任务树，还有高度自由充满脑洞的玩法和复杂的系统。

#+END_QUOTE
*** :PROPERTIES:
:END:
#+BEGIN_QUOTE
正如游戏行业的任何时候一样。人们追逐的流行概念如梦幻泡影，而坚守的核心玩法价值则在技术背景的飞速变幻之中，成为了新时代所召唤的选民。

#+END_QUOTE
*** :PROPERTIES:
:END:
#+BEGIN_QUOTE
在这个视频和直播决定命运的新时代里，正确的游戏设计将会是什么样的——而博德3与星空，Todd与Swen，Bethesda与Larian多年来的兴衰，恰巧是当下讨论这一问题最好的分析对象。

#+END_QUOTE
*** :PROPERTIES:
:END:
#+BEGIN_QUOTE
“小众品类爆卖”才是游戏行业真正成功的秘诀，“跟风当下流行”反而不是。MOBA可追溯到即时策略游戏的MOD，BR可追溯到ARMA3，生存可追溯到DayZ，沙盒可追溯到矮人要塞，撤离可追溯到塔科夫，现代开放世界可追溯到莎木，没有一个不是“小众核心”到相当程度的起源。

#+END_QUOTE
*** :PROPERTIES:
:END:
#+BEGIN_QUOTE
CRPG这一个品类的奇妙历史，你都能感觉到在这其中的讽刺性：这个品类的游戏很多其实根本就不“小众核心”。它销量低的假象，完全是由核心玩家们的定义造成的——当一家CRPG公司的游戏大卖之后，他大卖的那些游戏就会被玩家们开除CRPG籍！

上古卷轴1和2可以是CRPG，上古卷轴4和5当然就不是；辐射1和2可以是CRPG，辐射3、4当然就不是；龙腾世纪1可以是CRPG，质量效应3当然就不是；巫师1可以是CRPG，但巫师3和赛博朋克2077当然就不是。同样，这个规律放在神界原罪和博得之门3上也是有效的：当玩家们发现博得之门3大卖了以后，类似“Tactical RPG”、“Turn-based Strategy”这些“小众”品类标签的票数权重大减，被大家冷酷的抛弃了……

#+END_QUOTE
*** :PROPERTIES:
:END:
#+BEGIN_QUOTE
整个第一章的每一场战斗、每一个小任务，几乎都有这样密集的选择和毫无顾忌的分支设计，完全不在乎玩家杀掉的角色是否有10万字后续对话，或者他们的决策是否会导致占全游戏几分之一的重要NPC全军覆没。

#+END_QUOTE
*** :PROPERTIES:
:END:
#+BEGIN_QUOTE
如果在十年前，我可能会认为，这样大胆而多变的选择设计是有一定危险性的。这一方面会极大增加内容工作量，同时也不一定能讨到好：错误的选项可能意味着对玩家连续几十个小时的惩罚，也意味着团队花费了无数个小时做出的内容会被玩家完全错过，更可能因为任务状况互相覆盖产生数不清的Bug（如果你尝试过博德3的知名BUG“善良明萨拉路线”，就会明白这些任务判定条件互相影响造成的Bug是多么复杂）。

#+END_QUOTE
*** :PROPERTIES:
:END:
#+BEGIN_QUOTE
在这样的传播环境中，玩家们是能够互相交流，从而意识到这些选择背后的工作量的。当一个任务拥有多个甚至是不合常理的选择时，玩家们就真的会体会到“啊，这个游戏的内容量真的非常丰富”。甚至就连只看直播的云玩家，很多也能体会到这些选择背后内容量的厉害。

#+END_QUOTE
*** :PROPERTIES:
:END:
#+BEGIN_QUOTE
每一个有意义的选择设计，价值都可能相当于数十万美元的宣发投放和口碑。做有意义的选择、做值得传播的故事不再是可有可无、锦上添花的投入了，它将是2020年代性价比最高的成本投入点之一，是未来十年游戏行业最重要的内容竞争重点。

#+END_QUOTE
*** :PROPERTIES:
:END:
#+BEGIN_QUOTE
一个好的设计框架本身，必须要能容纳多种多样的解决方式，设计师才能面对这些解决方式设计出有趣的选择，同时满足“有传播性”和“不套路”的需求。

#+END_QUOTE
*** :PROPERTIES:
:END:
#+BEGIN_QUOTE
RPG在历史上留下了无数成功和失败的设计经验，其中只有五个主要玩法策略，历经历史考验留存至今：战斗、交易、交涉、潜行（偷窃）和解谜。

#+END_QUOTE
*** :PROPERTIES:
:END:
#+BEGIN_QUOTE
框架搞定了，接下来就进入第二个更难的要点：基于设计框架来创造富有变化性的选择。如果只是每个敌人都可以偷窃，每个非敌对的战斗都可以交涉，每个战斗都可以上元素反应，这不过是另外一种套路化的罐头而已，玩家很快就会腻了。好游戏和不好的游戏，甚至一个游戏内好的设计和不那么好的设计，都体现在这一层面。

#+END_QUOTE
* [[[https://mp.weixin.qq.com/s/n9YxgrFOTj30nD_Sk4ov9w][艺术史的漫游者：散漫式的阅读和笔记工具—E-ink 阅读器]]
:PROPERTIES:
:heading: true
:collapsed: true
:author: 艺术史的图书馆
:date-published: [[2019/05/05]]
:END:
** ### 高亮
:PROPERTIES:
:collapsed: true
:END:
*** :PROPERTIES:
:END:
#+BEGIN_QUOTE
要真正利用这些材料，不断地阅读和笔记就成为必要。但这种阅读不是正襟危坐式的，而是散漫式的，在任何一个合适的地方，尤其是放松的状态下，而不是deadline下的论文写作式的阅读。最新的脑科学证明：大脑原本的设计就是不可能以集中思考的状态工作，而是处在散漫的状态\[https://www.wired.co.uk/article/brain-distraction-procrastination-science\]。

#+END_QUOTE
*** :PROPERTIES:
:END:
#+BEGIN_QUOTE
何为散漫式阅读？

就是没有目的性的，打开一本书，放下，再打开另一本。其实这很像图书馆式的阅读，就是通过现代科技，把地理位置扩大了。

#+END_QUOTE
* [[[https://mp.weixin.qq.com/s/HnGqiBOTeK0N28QjmFSb5Q][数字人文时代的个人数据库之三：pdf优化工具和OCR工具的选择]]
:PROPERTIES:
:heading: true
:collapsed: true
:author: 艺术史的图书馆
:date-published: [[2019/05/04]]
:END:
** ### 高亮
:PROPERTIES:
:collapsed: true
:END:
*** :PROPERTIES:
:END:
#+BEGIN_QUOTE
#### **OCR 工具的选择**

OCR其实是最麻烦的一个环节，同时又是最重要的。

我用的软件主要有三个：Adobe Acrobat pro XI 、Adobe Acrobat pro DC和ABBYY。Adobe有两个，主要是经验上来说XI效果还好些，但有时候识别错误率偏高，DC 对扫描质量较高的文件友好，但时不时抽风，ABBYY号称很厉害，识别上还不错，就是导出会导致文件质量变差且文件较大。心累。

中文OCR，中文比较简单，因为我基本不检索中文的东西，OCR只是为了高亮，做笔记等。一般用Adobe XI的Exact这种模式就可以，尤其是Boox Max 2 可以对页面进行锐化、加黑之后，就没必要预先处理了。但如果想获得好的效果，用clearscan，对于一些偏淡字体的文件，需要用PS或Comic Enhancer Pro这样的软件将预先导出的图像文件进行黑白化处理。
 #[[PDF]] 
#+END_QUOTE
*** 个人应该有多少藏书？
:PROPERTIES:
:END:
#+BEGIN_QUOTE
10、100、4000、2万、30万，这是一系列图书数量的数据，10本著作大约可以比较有把握地掌握一个研究主题，100本可以差不多地勾勒出一个研究方向的框架，4000本可以满足一个学者的研究需求和一个私人图书馆的藏书开端，2万本则达到了私人藏书较为完美的状态，30万是一个专门学科的藏书的公共图书馆的量。
 #[[PKM]] 
#+END_QUOTE
* [[[https://utgd.net/article/20459][如何利用纸笔笔记：将其视为阅读笔记的先遣队 - #UNTAG]]
:PROPERTIES:
:heading: true
:collapsed: true
:author: Minja
:labels: [[PKM]]
:date-published: [[2023/11/07]]
:END:
** ### 高亮
:PROPERTIES:
:collapsed: true
:END:
*** :PROPERTIES:
:END:
#+BEGIN_QUOTE
原研哉曾指出，电脑解放了纸，让设计师可以更关注纸张本身的物理属性，而不必在承载图文信息上和电脑一较高下

#+END_QUOTE
*** :PROPERTIES:
:END:
#+BEGIN_QUOTE
软件成了第二大脑，负责存储；而**纸笔从存储的巨大压力中解放出来**，回归快速捕捉与初步加工的原始用途。

#+END_QUOTE
*** :PROPERTIES:
:END:
#+BEGIN_QUOTE
纸片上的大纲笔记，并非其他笔记的清单，而是**手头所读材料的索引**。

#+END_QUOTE
* [[[https://utgd.net/article/20520/][为什么我更喜欢用 Apple Watch 的数字表盘 - #UNTAG]]
:PROPERTIES:
:heading: true
:collapsed: true
:author: 文刀漢三
:labels: [[RSS]]
:date-published: [[2023/11/24]]
:END:
** ### 高亮
:PROPERTIES:
:collapsed: true
:END:
*** :PROPERTIES:
:END:
#+BEGIN_QUOTE
iOS 经历过从拟物到扁平的转变，事实上我认为“扁平”这个词语是不够贴切的，iOS 7 是放弃了对实体世界一板一眼的模仿，转向在数字世界创造一种新的显示样式和交互形式。它不再拟真实的物，而是创建一种新的质。

#+END_QUOTE
* [[[https://utgd.net/article/20488/][如何查看 iPhone、iPad 的充电循环次数 - #UNTAG]]
:PROPERTIES:
:heading: true
:collapsed: true
:author: 文刀漢三
:labels: [[RSS]]
:date-published: [[2023/11/02]]
:END:
** ### 高亮
:PROPERTIES:
:collapsed: true
:END:
*** :PROPERTIES:
:END:
#+BEGIN_QUOTE
macOS 老牌软件 iMazing。不需要付费购买，使用它的免费试用版即可。连上 iPhone 或 iPad，点击右方的“i”按钮，往下滑动，就可以看到“电池充电周期”，即充电循环次数。

#+END_QUOTE
* [[[https://necromanov.wordpress.com/2010/09/01/victoria2/][维多利亚2（Victoria2）：历史的逻辑 | 旗舰评论——战略航空军元帅的旗舰]]
:PROPERTIES:
:heading: true
:collapsed: true
:author: Necromanov
:labels: [[Games]]
:date-published: [[2010/09/01]]
:END:
** ### 高亮
:PROPERTIES:
:collapsed: true
:END:
*** :PROPERTIES:
:END:
#+BEGIN_QUOTE
维多利亚2（Victoria2，以下缩写为VIC2）旨在描述从1836年到1935年，从不列颠的正午到大萧条的落日的整个历史。它上承同公司的欧陆风暴3（Europa Universalis 3，以下缩写为EU3），下接钢铁雄心3（Hearts of Iron 3，以下缩写为HOI3），描述了我们的世界是怎样从由王公贵族管理的世界变成由民族国家统治的世界的。

#+END_QUOTE
*** :PROPERTIES:
:END:
#+BEGIN_QUOTE
设计思路就是这些游戏的“历史观”，他们的机制正体现了制作者们对历史的想法。

#+END_QUOTE
*** :PROPERTIES:
:END:
#+BEGIN_QUOTE
“英雄史观”。光荣的思路是“历史就是数值”，而数值的核心就是“英雄”们。

#+END_QUOTE
*** :PROPERTIES:
:END:
#+BEGIN_QUOTE
所有的事件也是“依赖于数值”而进行的，玩家所要做的就是尽量达成事件的前提条件，然后等待着收获报偿。

#+END_QUOTE
*** :PROPERTIES:
:END:
#+BEGIN_QUOTE
本质上那些数值同历史是无关的，只是游戏设计者的设定而已，而且他们只是根据自己的资料来定数值，英雄就是英雄，不做任何解释。

#+END_QUOTE
*** :PROPERTIES:
:END:
#+BEGIN_QUOTE
“制度史观”，主题是“历史就是规则”，上层建筑决定下层基础。

#+END_QUOTE
*** 这是最好玩的一个类别——但是也最不历史。
:PROPERTIES:
:END:
你的中国很可能没有长城，而是去抢了金字塔。游戏不会告诉你任何“为什么中国要建立长城而不是金字塔”  
的原因，也不会探讨“为什么德国的特色兵种要到装甲时代才出现”的理由。这些内容是“设计上的解释”，而不是“逻辑上的解释”。  
玩家想要建立长城是因为设计师说“这个奇迹可以让野蛮人不进入你的国境之内”，而不是因为他玩的是中国，同漫长的草原边境接壤，自己身后又有肥沃的土地。
#+BEGIN_QUOTE
历史只是游戏设计师们用来构建规则的小点缀，是他们用来写文档的灵感，却不是他们追求的目标。

#+END_QUOTE
*** :PROPERTIES:
:END:
#+BEGIN_QUOTE
基于“历史决定论”而产生的“历史就是事件”。

#+END_QUOTE
*** :PROPERTIES:
:END:
#+BEGIN_QUOTE
“事件驱动史观”同样不是真正的历史逻辑，它本质上只是一种不断检查历史状态的保险器。

#+END_QUOTE
* [[[https://necromanov.wordpress.com/2016/05/24/stellaris/][群星（Stellaris）：当文明遇到历史逻辑 | 旗舰评论——战略航空军元帅的旗舰]]
:PROPERTIES:
:heading: true
:collapsed: true
:author: Necromanov
:labels: [[Games]]
:date-published: [[2016/05/24]]
:END:
** ### 高亮
:PROPERTIES:
:collapsed: true
:END:
*** :PROPERTIES:
:END:
#+BEGIN_QUOTE
席德·梅尔的文明是游戏设计史上一个极为特殊的作品。它从桌游中吸取养分，却做出了完全不同于传统桌游的体验，它所开创的品类就是4X游戏。这个类型被游戏设计师Alan Emrich用四个Ex开头的英文单词定义为“4X”：探索（_Explore_）、扩张（_Expand_）、开发（_Exploit_）、征服（_Exterminate_）。

#+END_QUOTE
*** :PROPERTIES:
:END:
#+BEGIN_QUOTE
即时战略游戏也有“探索、扩张、开发、征服”（有兴趣的读者可以自己观察这四个要素是怎么构成即时战略游戏，甚至英雄联盟这样的MOBA游戏的核心循环的），但即时战略游戏绝不会让人有这种“赶紧我要再建个基地研发个科技”的感觉。

#+END_QUOTE
*** :PROPERTIES:
:END:
#+BEGIN_QUOTE
几乎所有的德式桌游（没错，有一个巨大的桌游分类叫做德式桌游，德意志的桌游世界第一），都有类似的多种资源不同循环机制的设计，大多数并不能做到“再来一回合”的快感。德式桌游的核心乐趣是“估值”，但这种估值负担太重了，重到了玩完一把大家脑内的计算能力都过载的程度。只有那些数学系的高手能沉迷于德式估值当中，我们这些一般人绝对不可能像玩文明一样，一晚又一晚持续进行德式桌游。

#+END_QUOTE
*** :PROPERTIES:
:END:
#+BEGIN_QUOTE
文明类游戏的核心乐趣已经呼之欲出：将多样化的行动和精密的估值结合起来。那就是我们在玩这种战略游戏时，反复操作并获得快感的核心内容：决策。

文明发明，而被群星及其他4X游戏所继承那个核心设计乐趣，是“决策”，以及随之而来的“决策的结果反馈”。

#+END_QUOTE
* [[[https://necromanov.wordpress.com/2017/01/20/female_market/][女性市场的初啼：为什么阴阳师会有这么多女性玩家？ | 旗舰评论——战略航空军元帅的旗舰]]
:PROPERTIES:
:heading: true
:collapsed: true
:author: Necromanov
:labels: [[Games]]
:date-published: [[2017/01/20]]
:END:
** ### 高亮
:PROPERTIES:
:collapsed: true
:END:
*** :PROPERTIES:
:END:
#+BEGIN_QUOTE
就算一款游戏看起来再讨女性玩家喜欢，如果生在一个“中国主流女性用户”不感兴趣、没听说过的平台上，它也无法获得大量的女性用户；在这样的平台上，不可能存在真正的“面向中国女性用户的女性向游戏”。

#+END_QUOTE
*** :PROPERTIES:
:END:
#+BEGIN_QUOTE
对于中国来说，“女性游戏市场”直到2015年才开始成为一个主要市场。而在中国女性开始成为游戏的主要市场后，仅仅用了一年半时间，她们就成功地将阴阳师推到了整个游戏市场的顶端

#+END_QUOTE
*** :PROPERTIES:
:END:
#+BEGIN_QUOTE
传奇通过攻陷网吧用户解决了付费渠道问题，成为第一个主流游戏；征途通过免费游戏模式，掌握住中国贫富差距迅速增大的机会，将中国游戏的主流用户重新定义为“先富起来的人”，极大提高了全行业的预期收入

#+END_QUOTE
*** :PROPERTIES:
:END:
#+BEGIN_QUOTE
在他们的研究中，证明了家庭财富和结婚概率的相关性，以及中国高性别比率地区未婚男性和未婚女性家庭储蓄率的相对变化：正如我们的常识一般，未婚男性家庭为了结婚，他们的储蓄率更高、消费率更低。

#+END_QUOTE
*** :PROPERTIES:
:END:
#+BEGIN_QUOTE
当女性的消费能力在市场中占比越来越大、男性的消费能力受到储蓄率压迫时，面向男性市场进行经营就会变得越来越困难；而储蓄率更低、消费意愿更强的女性用户会开始统治娱乐市场。

#+END_QUOTE