* 企业会计准则──基本准则

基本准则（2014年修订）

（2006年2月15日财政部令第33号公布，自2007年1月1日起施行。2014年7月23日根据《财政部关于修改<企业会计准则──基本准则>的决定》修改）

** 第一章 总 则

第一条　为了规范企业会计确认、计量和报告行为，保证会计信息质量，根据《中华人民共和国会计法》和其他有关法律、行政法规，制定本准则。

第二条　本准则适用于在中华人民共和国境内设立的企业（包括公司，下同）。

第三条　企业会计准则包括基本准则和具体准则，具体准则的制定应当遵循本准则。

第四条　企业应当编制财务会计报告（又称财务报告，下同）。财务会计报告的目标是向财务会计报告使用者提供与企业财务状况、经营成果和现金流量等有关的会计信息，反映企业管理层受托责任履行情况，有助于财务会计报告使用者作出经济决策。财务会计报告使用者包括投资者、债权人、政府及其有关部门和社会公众等。

第五条　企业应当对其本身发生的交易或者事项进行会计确认、计量和报告。

第六条　企业会计确认、计量和报告应当以持续经营为前提。

第七条　企业应当划分会计期间，分期结算账目和编制财务会计报告。会计期间分为年度和中期。中期是指短于一个完整的会计年度的报告期间。

第八条　企业会计应当以货币计量。

第九条　企业应当以权责发生制为基础进行会计确认、计量和报告。

第十条　企业应当按照交易或者事项的经济特征确定会计要素。会计要素包括资产、负债、所有者权益、收入、费用和利润。

第十一条　企业应当采用借贷记账法记账。

** 第二章 会计信息质量要求

第十二条　企业应当以实际发生的交易或者事项为依据进行会计确认、计量和报告，如实反映符合确认和计量要求的各项会计要素及其他相关信息，保证会计信息真实可靠、内容完整。

第十三条　企业提供的会计信息应当与财务会计报告使用者的经济决策需要相关，有助于财务会计报告使用者对企业过去、现在或者未来的情况作出评价或者预测。

第十四条　企业提供的会计信息应当清晰明了，便于财务会计报告使用者理解和使用。

第十五条　企业提供的会计信息应当具有可比性。同一企业不同时期发生的相同或者相似的交易或者事项，应当采用一致的会计政策，不得随意变更。确需变更的，应当在附注中说明。不同企业发生的相同或者相似的交易或者事项，应当采用规定的会计政策，确保会计信息口径一致、相互可比。

第十六条　企业应当按照交易或者事项的经济实质进行会计确认、计量和报告，不应仅以交易或者事项的法律形式为依据。

第十七条　企业提供的会计信息应当反映与企业财务状况、经营成果和现金流量等有关的所有重要交易或者事项。

第十八条　企业对交易或者事项进行会计确认、计量和报告应当保持应有的谨慎，不应高估资产或者收益、低估负债或者费用。

第十九条　企业对于已经发生的交易或者事项，应当及时进行会计确认、计量和报告，不得提前或者延后。

** 第三章 资 产

第二十条　资产是指企业过去的交易或者事项形成的、由企业拥有或者控制的、预期会给企业带来经济利益的资源。

- 前款所指的企业过去的交易或者事项包括购买、生产、建造行为或其他交易或者事项。预期在未来发生的交易或者事项不形成资产。
- 由企业拥有或者控制，是指企业享有某项资源的所有权，或者虽然不享有某项资源的所有权，但该资源能被企业所控制。
- 预期会给企业带来经济利益，是指直接或者间接导致现金和现金等价物流入企业的潜力。

第二十一条　符合本准则第二十条规定的资产定义的资源，在同时满足以下条件时，确认为资产：

（一）与该资源有关的经济利益很可能流入企业；

（二）该资源的成本或者价值能够可靠地计量。

第二十二条　符合资产定义和资产确认条件的项目，应当列入资产负债表；符合资产定义、但不符合资产确认条件的项目，不应当列入资产负债表。

** 第四章 负 债

第二十三条　负债是指企业过去的交易或者事项形成的、预期会导致经济利益流出企业的现时义务。现时义务是指企业在现行条件下已承担的义务。未来发生的交易或者事项形成的义务，不属于现时义务，不应当确认为负债。

第二十四条　符合本准则第二十三条规定的负债定义的义务，在同时满足以下条件时，确认为负债：

（一）与该义务有关的经济利益很可能流出企业；

（二）未来流出的经济利益的金额能够可靠地计量。

第二十五条　符合负债定义和负债确认条件的项目，应当列入资产负债表；符合负债定义、但不符合负债确认条件的项目，不应当列入资产负债表。

** 第五章 所有者权益

第二十六条　所有者权益是指企业资产扣除负债后由所有者享有的剩余权益。公司的所有者权益又称为股东权益。

第二十七条　所有者权益的来源包括所有者投入的资本、直接计入所有者权益的利得和损失、留存收益等。

- 直接计入所有者权益的利得和损失，是指不应计入当期损益、会导致所有者权益发生增减变动的、与所有者投入资本或者向所有者分配利润无关的利得或者损失。
- 利得是指由企业非日常活动所形成的、会导致所有者权益增加的、与所有者投入资本无关的经济利益的流入。
- 损失是指由企业非日常活动所发生的、会导致所有者权益减少的、与向所有者分配利润无关的经济利益的流出。

第二十八条　所有者权益金额取决于资产和负债的计量。

第二十九条　所有者权益项目应当列入资产负债表。

** 第六章 收 入

第三十条　收入是指企业在日常活动中形成的、会导致所有者权益增加的、与所有者投入资本无关的经济利益的总流入。

第三十一条　收入只有在经济利益很可能流入从而导致企业资产增加或者负债减少、且经济利益的流入额能够可靠计量时才能予以确认。

第三十二条　符合收入定义和收入确认条件的项目，应当列入利润表。

** 第七章 费 用

第三十三条　费用是指企业在日常活动中发生的、会导致所有者权益减少的、与向所有者分配利润无关的经济利益的总流出。

第三十四条　费用只有在经济利益很可能流出从而导致企业资产减少或者负债增加、且经济利益的流出额能够可靠计量时才能予以确认。

第三十五条　企业为生产产品、提供劳务等发生的可归属于产品成本、劳务成本等的费用，应当在确认产品销售收入、劳务收入等时，将已销售产品、已提供劳务的成本等计入当期损益。企业发生的支出不产生经济利益的，或者即使能够产生经济利益但不符合或者不再符合资产确认条件的，应当在发生时确认为费用，计入当期损益。企业发生的交易或者事项导致其承担了一项负债而又不确认为一项资产的，应当在发生时确认为费用，计入当期损益。

第三十六条　符合费用定义和费用确认条件的项目，应当列入利润表。

** 第八章 利 润

第三十七条　利润是指企业在一定会计期间的经营成果。利润包括收入减去费用后的净额、直接计入当期利润的利得和损失等。

第三十八条　直接计入当期利润的利得和损失，是指应当计入当期损益、会导致所有者权益发生增减变动的、与所有者投入资本或者向所有者分配利润无关的利得或者损失。

第三十九条　利润金额取决于收入和费用、直接计入当期利润的利得和损失金额的计量。

第四十条　利润项目应当列入利润表。

** 第九章 会计计量

第四十一条　企业在将符合确认条件的会计要素登记入账并列报于会计报表及其附注（又称财务报表，下同）时，应当按照规定的会计计量属性进行计量，确定其金额。

第四十二条　会计计量属性主要包括：

（一）历史成本。在历史成本计量下，资产按照购置时支付的现金或者现金等价物的金额，或者按照购置资产时所付出的对价的公允价值计量。负债按照因承担现时义务而实际收到的款项或者资产的金额，或者承担现时义务的合同金额，或者按照日常活动中为偿还负债预期需要支付的现金或者现金等价物的金额计量。

（二）重置成本。在重置成本计量下，资产按照现在购买相同或者相似资产所需支付的现金或者现金等价物的金额计量。负债按照现在偿付该项债务所需支付的现金或者现金等价物的金额计量。

（三）可变现净值。在可变现净值计量下，资产按照其正常对外销售所能收到现金或者现金等价物的金额扣减该资产至完工时估计将要发生的成本、估计的销售费用以及相关税费后的金额计量。

（四）现值。在现值计量下，资产按照预计从其持续使用和终处置中所产生的未来净现金流入量的折现金额计量。负债按照预计期限内需要偿还的未来净现金流出量的折现金额计量。

（五）公允价值。在公允价值计量下，资产和负债按照市场参与者在计量日发生的有序交易中，出售资产所能收到或者转移负债所需支付的价格计量。

第四十三条　企业在对会计要素进行计量时，一般应当采用历史成本，采用重置成本、可变现净值、现值、公允价值计量的，应当保证所确定的会计要素金额能够取得并可靠计量。

** 第十章 财务会计报告

第四十四条　财务会计报告是指企业对外提供的反映企业某一特定日期的财务状况和某一会计期间的经营成果、现金流量等会计信息的文件。财务会计报告包括会计报表及其附注和其他应当在财务会计报告中披露的相关信息和资料。会计报表至少应当包括资产负债表、利润表、现金流量表等报表。小企业编制的会计报表可以不包括现金流量表。

第四十五条　资产负债表是指反映企业在某一特定日期的财务状况的会计报表。

第四十六条　利润表是指反映企业在一定会计期间的经营成果的会计报表。

第四十七条　现金流量表是指反映企业在一定会计期间的现金和现金等价物流入和流出的会计报表。

第四十八条　附注是指对在会计报表中列示项目所作的进一步说明，以及对未能在这些报表中列示项目的说明等。

** 第十一章 附 则

第四十九条　本准则由财政部负责解释。

第五十条　本准则自2007年1月1日起施行。
* 企业会计准则第1号──存货
** 第一章 总则
*** 第一条　为了规范存货的确认、计量和相关信息的披露，根据《企业会计准则──基本准则》，制定本准则。
*** 第二条　下列各项适用其他相关会计准则：
**** （一）消耗性生物资产，适用《企业会计准则第5号──生物资产》。
**** （二）通过建造合同归集的存货成本，适用《企业会计准则第15号──建造合同》。
** 第二章 确认
*** 第三条　存货，是指企业在日常活动中持有以备出售的产成品或商品、处在生产过程中的在产品、在生产过程或提供劳务过程中耗用的材料和物料等。
*** 第四条　存货同时满足下列条件的，才能予以确认：
**** （一）与该存货有关的经济利益很可能流入企业；
**** （二）该存货的成本能够可靠地计量。
** 第三章 计量
*** 第五条　存货应当按照成本进行初始计量。存货成本包括采购成本、加工成本和其他成本。
*** 第六条　存货的采购成本，包括购买价款、相关税费、运输费、装卸费、保险费以及其他可归属于存货采购成本的费用。
*** 第七条　存货的加工成本，包括直接人工以及按照一定方法分配的制造费用。制造费用，是指企业为生产产品和提供劳务而发生的各项间接费用。企业应当根据制造费用的性质，合理地选择制造费用分配方法。在同一生产过程中，同时生产两种或两种以上的产品，并且每种产品的加工成本不能直接区分的，其加工成本应当按照合理的方法在各种产品之间进行分配。
*** 第八条　存货的其他成本，是指除采购成本、加工成本以外的，使存货达到目前场所和状态所发生的其他支出。
*** 第九条　下列费用应当在发生时确认为当期损益，不计入存货成本：
**** （一）非正常消耗的直接材料、直接人工和制造费用。
**** （二）仓储费用（不包括在生产过程中为达到下一个生产阶段所必需的费用）。
**** （三）不能归属于使存货达到目前场所和状态的其他支出。
*** 第十条　应计入存货成本的借款费用，按照《企业会计准则第17号──借款费用》处理。
*** 第十一条　投资者投入存货的成本，应当按照投资合同或协议约定的价值确定，但合同或协议约定价值不公允的除外。
*** 第十二条　收获时农产品的成本、非货币性资产交换、债务重组和企业合并取得的存货的成本，应当分别按照《企业会计准则第5号──生物资产》、《企业会计准则第7号──非货币性资产交换》、《企业会计准则第12号──债务重组》和《企业会计准则第20号──企业合并》确定。
*** 第十三条　企业提供劳务的，所发生的从事劳务提供人员的直接人工和其他直接费用以及可归属的间接费用，计入存货成本。
*** 第十四条　企业应当采用先进先出法、加权平均法或者个别计价法确定发出存货的实际成本。对于性质和用途相似的存货，应当采用相同的成本计算方法确定发出存货的成本。对于不能替代使用的存货、为特定项目专门购入或制造的存货以及提供的劳务，通常采用个别计价法确定发出存货的成本。对于已售存货，应当将其成本结转为当期损益，相应的存货跌价准备也应当予以结转。
*** 第十五条　资产负债表日，存货应当按照成本与可变现净值孰低计量。存货成本高于其可变现净值的，应当计提存货跌价准备，计入当期损益。可变现净值，是指在日常活动中，存货的估计售价减去至完工时估计将要发生的成本、估计的销售费用以及相关税费后的金额。
*** 第十六条　企业确定存货的可变现净值，应当以取得的确凿证据为基础，并且考虑持有存货的目的、资产负债表日后事项的影响等因素。为生产而持有的材料等，用其生产的产成品的可变现净值高于成本的，该材料仍然应当按照成本计量；材料价格的下降表明产成品的可变现净值低于成本的，该材料应当按照可变现净值计量。
*** 第十七条　为执行销售合同或者劳务合同而持有的存货，其可变现净值应当以合同价格为基础计算。企业持有存货的数量多于销售合同订购数量的，超出部分的存货的可变现净值应当以一般销售价格为基础计算。
*** 第十八条　企业通常应当按照单个存货项目计提存货跌价准备。对于数量繁多、单价较低的存货，可以按照存货类别计提存货跌价准备。与在同一地区生产和销售的产品系列相关、具有相同或类似终用途或目的，且难以与其他项目分开计量的存货，可以合并计提存货跌价准备。
*** 第十九条　资产负债表日，企业应当确定存货的可变现净值。以前减记存货价值的影响因素已经消失的，减记的金额应当予以恢复，并在原已计提的存货跌价准备金额内转回，转回的金额计入当期损益。
*** 第二十条　企业应当采用一次转销法或者五五摊销法对低值易耗品和包装物进行摊销，计入相关资产的成本或者当期损益。
*** 第二十一条　企业发生的存货毁损，应当将处置收入扣除账面价值和相关税费后的金额计入当期损益。存货的账面价值是存货成本扣减累计跌价准备后的金额。存货盘亏造成的损失，应当计入当期损益。
** 第四章 披露
*** 第二十二条　企业应当在附注中披露与存货有关的下列信息：
**** （一）各类存货的期初和期末账面价值。
**** （二）确定发出存货成本所采用的方法。
**** （三）存货可变现净值的确定依据，存货跌价准备的计提方法，当期计提的存货跌价准备的金额，当期转回的存货跌价准备的金额，以及计提和转回的有关情况。
**** （四）用于担保的存货账面价值。
* 企业会计准则第2号──长期股权投资

（2014年修订）

** 第一章 总 则

第一条　为了规范长期股权投资的确认、计量，根据《企业会计准则──基本准则》，制定本准则。

第二条　本准则所称长期股权投资，是指投资方对被投资单位实施控制、重大影响的权益性投资，以及对其合营企业的权益性投资。在确定能否对被投资单位实施控制时，投资方应当按照《企业会计准则第33号──合并财务报表》的有关规定进行判断。投资方能够对被投资单位实施控制的，被投资单位为其子公司。投资方属于《企业会计准则第33号──合并财务报表》规定的投资性主体且子公司不纳入合并财务报表的情况除外。

重大影响，是指投资方对被投资单位的财务和经营政策有参与决策的权力，但并不能够控制或者与其他方一起共同控制这些政策的制定。在确定能否对被投资单位施加重大影响时，应当考虑投资方和其他方持有的被投资单位当期可转换公司债券、当期可执行认股权证等潜在表决权因素。投资方能够对被投资单位施加重大影响的，被投资单位为其联营企业。在确定被投资单位是否为合营企业时，应当按照《企业会计准则第40号──合营安排》的有关规定进行判断。

第三条　下列各项适用其他相关会计准则：

（一）外币长期股权投资的折算，适用《企业会计准则第19号──外币折算》。

（二）风险投资机构、共同基金以及类似主体持有的、在初始确认时按照《企业会计准则第22号──金融工具确认和计量》的规定以公允价值计量且其变动计入当期损益的金融资产，投资性主体对不纳入合并财务报表的子公司的权益性投资，以及本准则未予规范的其他权益性投资，适用《企业会计准则第22号──金融工具确认和计量》。

第四条　长期股权投资的披露，适用《企业会计准则第41号──在其他主体中权益的披露》。

** 第二章 初始计量

第五条　企业合并形成的长期股权投资，应当按照下列规定确定其初始投资成本：

（一）同一控制下的企业合并，合并方以支付现金、转让非现金资产或承担债务方式作为合并对价的，应当在合并日按照被合并方所有者权益在终控制方合并财务报表中的账面价值的份额作为长期股权投资的初始投资成本。\\

  长期股权投资初始投资成本与支付的现金、转让的非现金资产以及所承担债务账面价值之间的差额，应当调整资本公积；资本公积不足冲减的，调整留存收益。\\
  合并方以发行权益性证券作为合并对价的，应当在合并日按照被合并方所有者权益在终控制方合并财务报表中的账面价值的份额作为长期股权投资的初始投资成本。按照发行股份的面值总额作为股本，长期股权投资初始投资成本与所发行股份面值总额之间的差额，应当调整资本公积；资本公积不足冲减的，调整留存收益。
（二）非同一控制下的企业合并，购买方在购买日应当按照《企业会计准则第20号──企业合并》的有关规定确定的合并成本作为长期股权投资的初始投资成本。合并方或购买方为企业合并发生的审计、法律服务、评估咨询等中介费用以及其他相关管理费用，应当于发生时计入当期损益。

第六条　除企业合并形成的长期股权投资以外，其他方式取得的长期股权投资，应当按照下列规定确定其初始投资成本：

（一）以支付现金取得的长期股权投资，应当按照实际支付的购买价款作为初始投资成本。初始投资成本包括与取得长期股权投资直接相关的费用、税金及其他必要支出。

（二）以发行权益性证券取得的长期股权投资，应当按照发行权益性证券的公允价值作为初始投资成本。与发行权益性证券直接相关的费用，应当按照《企业会计准则第37号──金融工具列报》的有关规定确定。

（三）通过非货币性资产交换取得的长期股权投资，其初始投资成本应当按照《企业会计准则第7号──非货币性资产交换》的有关规定确定。

（四）通过债务重组取得的长期股权投资，其初始投资成本应当按照《企业会计准则第12号──债务重组》的有关规定确定。

** 第三章 后续计量

第七条　投资方能够对被投资单位实施控制的长期股权投资应当采用成本法核算。

第八条　采用成本法核算的长期股权投资应当按照初始投资成本计价。追加或收回投资应当调整长期股权投资的成本。被投资单位宣告分派的现金股利或利润，应当确认为当期投资收益。

第九条　投资方对联营企业和合营企业的长期股权投资，应当按照本准则第十条至第十三条规定，采用权益法核算。投资方对联营企业的权益性投资，其中一部分通过风险投资机构、共同基金、信托公司或包括投连险基金在内的类似主体间接持有的，无论以上主体是否对这部分投资具有重大影响，投资方都可以按照《企业会计准则第22号──金融工具确认和计量》的有关规定，对间接持有的该部分投资选择以公允价值计量且其变动计入损益，并对其余部分采用权益法核算。

第十条　长期股权投资的初始投资成本大于投资时应享有被投资单位可辨认净资产公允价值份额的，不调整长期股权投资的初始投资成本；长期股权投资的初始投资成本小于投资时应享有被投资单位可辨认净资产公允价值份额的，其差额应当计入当期损益，同时调整长期股权投资的成本。被投资单位可辨认净资产的公允价值，应当比照《企业会计准则第20号──企业合并》的有关规定确定。

第十一条　投资方取得长期股权投资后，应当按照应享有或应分担的被投资单位实现的净损益和其他综合收益的份额，分别确认投资收益和其他综合收益，同时调整长期股权投资的账面价值；投资方按照被投资单位宣告分派的利润或现金股利计算应享有的部分，相应减少长期股权投资的账面价值；投资方对于被投资单位除净损益、其他综合收益和利润分配以外所有者权益的其他变动，应当调整长期股权投资的账面价值并计入所有者权益。

投资方在确认应享有被投资单位净损益的份额时，应当以取得投资时被投资单位可辨认净资产的公允价值为基础，对被投资单位的净利润进行调整后确认。被投资单位采用的会计政策及会计期间与投资方不一致的，应当按照投资方的会计政策及会计期间对被投资单位的财务报表进行调整，并据以确认投资收益和其他综合收益等。

第十二条　投资方确认被投资单位发生的净亏损，应当以长期股权投资的账面价值以及其他实质上构成对被投资单位净投资的长期权益减记至零为限，投资方负有承担额外损失义务的除外。被投资单位以后实现净利润的，投资方在其收益分享额弥补未确认的亏损分担额后，恢复确认收益分享额。

第十三条　投资方计算确认应享有或应分担被投资单位的净损益时，与联营企业、合营企业之间发生的未实现内部交易损益按照应享有的比例计算归属于投资方的部分，应当予以抵销，在此基础上确认投资收益。投资方与被投资单位发生的未实现内部交易损失，按照《企业会计准则第8号──资产减值》等的有关规定属于资产减值损失的，应当全额确认。

第十四条　投资方因追加投资等原因能够对被投资单位施加重大影响或实施共同控制但不构成控制的，应当按照《企业会计准则第22号──金融工具确认和计量》确定的原持有的股权投资的公允价值加上新增投资成本之和，作为改按权益法核算的初始投资成本。原持有的股权投资分类为可供出售金融资产的，其公允价值与账面价值之间的差额，以及原计入其他综合收益的累计公允价值变动应当转入改按权益法核算的当期损益。投资方因追加投资等原因能够对非同一控制下的被投资单位实施控制的，在编制个别财务报表时，应当按照原持有的股权投资账面价值加上新增投资成本之和，作为改按成本法核算的初始投资成本。购买日之前持有的股权投资因采用权益法核算而确认的其他综合收益，应当在处置该项投资时采用与被投资单位直接处置相关资产或负债相同的基础进行会计处理。购买日之前持有的股权投资按照《企业会计准则第22号──金融工具确认和计量》的有关规定进行会计处理的，原计入其他综合收益的累计公允价值变动应当在改按成本法核算时转入当期损益。在编制合并财务报表时，应当按照《企业会计准则第33号──合并财务报表》的有关规定进行会计处理。

第十五条　投资方因处置部分股权投资等原因丧失了对被投资单位的共同控制或重大影响的，处置后的剩余股权应当改按《企业会计准则第22号──金融工具确认和计量》核算，其在丧失共同控制或重大影响之日的公允价值与账面价值之间的差额计入当期损益。原股权投资因采用权益法核算而确认的其他综合收益，应当在终止采用权益法核算时采用与被投资单位直接处置相关资产或负债相同的基础进行会计处理。投资方因处置部分权益性投资等原因丧失了对被投资单位的控制的，在编制个别财务报表时，处置后的剩余股权能够对被投资单位实施共同控制或施加重大影响的，应当改按权益法核算，并对该剩余股权视同自取得时即采用权益法核算进行调整；处置后的剩余股权不能对被投资单位实施共同控制或施加重大影响的，应当改按《企业会计准则第22号──金融工具确认和计量》的有关规定进行会计处理，其在丧失控制之日的公允价值与账面价值间的差额计入当期损益。在编制合并财务报表时，应当按照《企业会计准则第33号──合并财务报表》的有关规定进行会计处理。

第十六条　对联营企业或合营企业的权益性投资全部或部分分类为持有待售资产的，投资方应当按照《企业会计准则第4号──固定资产》的有关规定处理，对于未划分为持有待售资产的剩余权益性投资，应当采用权益法进行会计处理。已划分为持有待售的对联营企业或合营企业的权益性投资，不再符合持有待售资产分类条件的，应当从被分类为持有待售资产之日起采用权益法进行追溯调整。分类为持有待售期间的财务报表应当作相应调整。

第十七条　处置长期股权投资，其账面价值与实际取得价款之间的差额，应当计入当期损益。采用权益法核算的长期股权投资，在处置该项投资时，采用与被投资单位直接处置相关资产或负债相同的基础，按相应比例对原计入其他综合收益的部分进行会计处理。

第十八条　投资方应当关注长期股权投资的账面价值是否大于享有被投资单位所有者权益账面价值的份额等类似情况。出现类似情况时，投资方应当按照《企业会计准则第8号──资产减值》对长期股权投资进行减值测试，可收回金额低于长期股权投资账面价值的，应当计提减值准备。

** 第四章 衔接规定

第十九条　在本准则施行日之前已经执行企业会计准则的企业，应当按照本准则进行追溯调整，追溯调整不切实可行的除外。

** 第五章 附 则

第二十条　本准则自2014年7月1日起施行。

* 企业会计准则第3号──投资性房地产

（2006）财会[2006]3号

** 第一章 总则

第一条　为了规范投资性房地产的确认、计量和相关信息的披露，根据《企业会计准则──基本准则》，制定本准则。

第二条　投资性房地产，是指为赚取租金或资本增值，或两者兼有而持有的房地产。投资性房地产应当能够单独计量和出售。

第三条　本准则规范下列投资性房地产：

（一）已出租的土地使用权。

（二）持有并准备增值后转让的土地使用权。

（三）已出租的建筑物。

第四条　下列各项不属于投资性房地产：

（一）自用房地产，即为生产商品、提供劳务或者经营管理而持有的房地产。

（二）作为存货的房地产。

第五条　下列各项适用其他相关会计准则：

（一）企业代建的房地产，适用《企业会计准则第15号──建造合同》。

（二）投资性房地产的租金收入和售后租回，适用《企业会计准则第21号──租赁》。

** 第二章 确认和初始计量

第六条　投资性房地产同时满足下列条件的，才能予以确认：

（一）与该投资性房地产有关的经济利益很可能流入企业；

（二）该投资性房地产的成本能够可靠地计量。

第七条　投资性房地产应当按照成本进行初始计量。

（一）外购投资性房地产的成本，包括购买价款、相关税费和可直接归属于该资产的其他支出。

（二）自行建造投资性房地产的成本，由建造该项资产达到预定可使用状态前所发生的必要支出构成。

（三）以其他方式取得的投资性房地产的成本，按照相关会计准则的规定确定。

第八条　与投资性房地产有关的后续支出，满足本准则第六条规定的确认条件的，应当计入投资性房地产成本；不满足本准则第六条规定的确认条件的，应当在发生时计入当期损益。

** 第三章 后续计量

第九条　企业应当在资产负债表日采用成本模式对投资性房地产进行后续计量，但本准则第十条规定的除外。采用成本模式计量的建筑物的后续计量，适用《企业会计准则第4号──固定资产》。采用成本模式计量的土地使用权的后续计量，适用《企业会计准则第6号──无形资产》。

第十条　有确凿证据表明投资性房地产的公允价值能够持续可靠取得的，可以对投资性房地产采用公允价值模式进行后续计量。采用公允价值模式计量的，应当同时满足下列条件：

（一）投资性房地产所在地有活跃的房地产交易市场；

（二）企业能够从房地产交易市场上取得同类或类似房地产的市场价格及其他相关信息，从而对投资性房地产的公允价值作出合理的估计。

第十一条　采用公允价值模式计量的，不对投资性房地产计提折旧或进行摊销，应当以资产负债表日投资性房地产的公允价值为基础调整其账面价值，公允价值与原账面价值之间的差额计入当期损益。

第十二条　企业对投资性房地产的计量模式一经确定，不得随意变更。成本模式转为公允价值模式的，应当作为会计政策变更，按照《企业会计准则第28号──会计政策、会计估计变更和差错更正》处理。已采用公允价值模式计量的投资性房地产，不得从公允价值模式转为成本模式。

** 第四章 转换

第十三条　企业有确凿证据表明房地产用途发生改变，满足下列条件之一的，应当将投资性房地产转换为其他资产或者将其他资产转换为投资性房地产：

（一）投资性房地产开始自用。

（二）作为存货的房地产，改为出租。

（三）自用土地使用权停止自用，用于赚取租金或资本增值。

（四）自用建筑物停止自用，改为出租。

第十四条　在成本模式下，应当将房地产转换前的账面价值作为转换后的入账价值。

第十五条　采用公允价值模式计量的投资性房地产转换为自用房地产时，应当以其转换当日的公允价值作为自用房地产的账面价值，公允价值与原账面价值的差额计入当期损益。

第十六条　自用房地产或存货转换为采用公允价值模式计量的投资性房地产时，投资性房地产按照转换当日的公允价值计价，转换当日的公允价值小于原账面价值的，其差额计入当期损益；转换当日的公允价值大于原账面价值的，其差额计入所有者权益。

** 第五章 处置

第十七条　当投资性房地产被处置，或者永久退出使用且预计不能从其处置中取得经济利益时，应当终止确认该项投资性房地产。

第十八条　企业出售、转让、报废投资性房地产或者发生投资性房地产毁损，应当将处置收入扣除其账面价值和相关税费后的金额计入当期损益。

** 第六章 披露

第十九条　企业应当在附注中披露与投资性房地产有关的下列信息：

（一）投资性房地产的种类、金额和计量模式。

（二）采用成本模式的，投资性房地产的折旧或摊销，以及减值准备的计提情况。

（三）采用公允价值模式的，公允价值的确定依据和方法，以及公允价值变动对损益的影响。

（四）房地产转换情况、理由，以及对损益或所有者权益的影响。

（五）当期处置的投资性房地产及其对损益的影响。

* 企04 固定资产

（2006）财会[2006]3号

** 第一章 总则

第一条　为了规范固定资产的确认、计量和相关信息的披露，根据《企业会计准则──基本准则》，制定本准则。

第二条　下列各项适用其他相关会计准则：

（一）作为投资性房地产的建筑物，适用《企业会计准则第3号──投资性房地产》。

（二）生产性生物资产，适用《企业会计准则第5号──生物资产》。

** 第二章 确认

第三条　固定资产，是指同时具有下列特征的有形资产：

（一）为生产商品、提供劳务、出租或经营管理而持有的；

（二）使用寿命超过一个会计年度。使用寿命，是指企业使用固定资产的预计期间，或者该固定资产所能生产产品或提供劳务的数量。

第四条　固定资产同时满足下列条件的，才能予以确认：

（一）与该固定资产有关的经济利益很可能流入企业；

（二）该固定资产的成本能够可靠地计量。

第五条　固定资产的各组成部分具有不同使用寿命或者以不同方式为企业提供经济利益，适用不同折旧率或折旧方法的，应当分别将各组成部分确认为单项固定资产。

第六条　与固定资产有关的后续支出，符合本准则第四条规定的确认条件的，应当计入固定资产成本；不符合本准则第四条规定的确认条件的，应当在发生时计入当期损益。

** 第三章 初始计量

第七条　固定资产应当按照成本进行初始计量。

第八条　外购固定资产的成本，包括购买价款、相关税费、使固定资产达到预定可使用状态前所发生的可归属于该项资产的运输费、装卸费、安装费和专业人员服务费等。以一笔款项购入多项没有单独标价的固定资产，应当按照各项固定资产公允价值比例对总成本进行分配，分别确定各项固定资产的成本。购买固定资产的价款超过正常信用条件延期支付，实质上具有融资性质的，固定资产的成本以购买价款的现值为基础确定。实际支付的价款与购买价款的现值之间的差额，除按照《企业会计准则第17号──借款费用》应予资本化的以外，应当在信用期间内计入当期损益。

第九条　自行建造固定资产的成本，由建造该项资产达到预定可使用状态前所发生的必要支出构成。

第十条　应计入固定资产成本的借款费用，按照《企业会计准则第17号──借款费用》处理。

第十一条　投资者投入固定资产的成本，应当按照投资合同或协议约定的价值确定，但合同或协议约定价值不公允的除外。

第十二条　非货币性资产交换、债务重组、企业合并和融资租赁取得的固定资产的成本，应当分别按照《企业会计准则第7号──非货币性资产交换》、《企业会计准则第12号──债务重组》、《企业会计准则第20号──企业合并》和《企业会计准则第21号──租赁》确定。

第十三条　确定固定资产成本时，应当考虑预计弃置费用因素。

** 第四章 后续计量

第十四条　企业应当对所有固定资产计提折旧。但是，已提足折旧仍继续使用的固定资产和单独计价入账的土地除外。折旧，是指在固定资产使用寿命内，按照确定的方法对应计折旧额进行系统分摊。应计折旧额，是指应当计提折旧的固定资产的原价扣除其预计净残值后的金额。已计提减值准备的固定资产，还应当扣除已计提的固定资产减值准备累计金额。预计净残值，是指假定固定资产预计使用寿命已满并处于使用寿命终了时的预期状态，企业目前从该项资产处置中获得的扣除预计处置费用后的金额。

第十五条　企业应当根据固定资产的性质和使用情况，合理确定固定资产的使用寿命和预计净残值。固定资产的使用寿命、预计净残值一经确定，不得随意变更。但是，符合本准则第十九条规定的除外。

第十六条　企业确定固定资产使用寿命，应当考虑下列因素：

（一）预计生产能力或实物产量；

（二）预计有形损耗和无形损耗；

（三）法律或者类似规定对资产使用的限制。

第十七条　企业应当根据与固定资产有关的经济利益的预期实现方式，合理选择固定资产折旧方法。可选用的折旧方法包括年限平均法、工作量法、双倍余额递减法和年数总和法等。固定资产的折旧方法一经确定，不得随意变更。但是，符合本准则第十九条规定的除外。

第十八条　固定资产应当按月计提折旧，并根据用途计入相关资产的成本或者当期损益。

第十九条　企业至少应当于每年年度终了，对固定资产的使用寿命、预计净残值和折旧方法进行复核。使用寿命预计数与原先估计数有差异的，应当调整固定资产使用寿命。预计净残值预计数与原先估计数有差异的，应当调整预计净残值。与固定资产有关的经济利益预期实现方式有重大改变的，应当改变固定资产折旧方法。固定资产使用寿命、预计净残值和折旧方法的改变应当作为会计估计变更。

第二十条　固定资产的减值，应当按照《企业会计准则第8号──资产减值》处理。

** 第五章 处置

第二十一条　固定资产满足下列条件之一的，应当予以终止确认：

（一）该固定资产处于处置状态。

（二）该固定资产预期通过使用或处置不能产生经济利益。

第二十二条　企业持有待售的固定资产，应当对其预计净残值进行调整。

第二十三条　企业出售、转让、报废固定资产或发生固定资产毁损，应当将处置收入扣除账面价值和相关税费后的金额计入当期损益。固定资产的账面价值是固定资产成本扣减累计折旧和累计减值准备后的金额。固定资产盘亏造成的损失，应当计入当期损益。

第二十四条　企业根据本准则第六条的规定，将发生的固定资产后续支出计入固定资产成本的，应当终止确认被替换部分的账面价值。

** 第六章 披露

第二十五条　企业应当在附注中披露与固定资产有关的下列信息：

（一）固定资产的确认条件、分类、计量基础和折旧方法。

（二）各类固定资产的使用寿命、预计净残值和折旧率。

（三）各类固定资产的期初和期末原价、累计折旧额及固定资产减值准备累计金额。

（四）当期确认的折旧费用。

（五）对固定资产所有权的限制及其金额和用于担保的固定资产账面价值。

（六）准备处置的固定资产名称、账面价值、公允价值、预计处置费用和预计处置时间等。

* 企05 生物资产

（2006）财会[2006]3号

** 第一章 总则

第一条　为了规范与农业生产相关的生物资产的确认、计量和相关信息的披露，根据《企业会计准则──基本准则》，制定本准则。

第二条　生物资产，是指有生命的动物和植物。

第三条　生物资产分为消耗性生物资产、生产性生物资产和公益性生物资产。消耗性生物资产，是指为出售而持有的、或在将来收获为农产品的生物资产，包括生长中的大田作物、蔬菜、用材林以及存栏待售的牲畜等。生产性生物资产，是指为产出农产品、提供劳务或出租等目的而持有的生物资产，包括经济林、薪炭林、产畜和役畜等。公益性生物资产，是指以防护、环境保护为主要目的的生物资产，包括防风固沙林、水土保持林和水源涵养林等。

第四条　下列各项适用其他相关会计准则：

（一）收获后的农产品，适用《企业会计准则第1号──存货》。

（二）与生物资产相关的政府补助，适用《企业会计准则第16号──政府补助》。

** 第二章 确认和初始计量

第五条　生物资产同时满足下列条件的，才能予以确认：

（一）企业因过去的交易或者事项而拥有或者控制该生物资产；

（二）与该生物资产有关的经济利益或服务潜能很可能流入企业；

（三）该生物资产的成本能够可靠地计量。

第六条　生物资产应当按照成本进行初始计量。

第七条　外购生物资产的成本，包括购买价款、相关税费、运输费、保险费以及可直接归属于购买该资产的其他支出。

第八条　自行栽培、营造、繁殖或养殖的消耗性生物资产的成本，应当按照下列规定确定：

（一）自行栽培的大田作物和蔬菜的成本，包括在收获前耗用的种子、肥料、农药等材料费、人工费和应分摊的间接费用等必要支出。

（二）自行营造的林木类消耗性生物资产的成本，包括郁闭前发生的造林费、抚育费、营林设施费、良种试验费、调查设计费和应分摊的间接费用等必要支出。

（三）自行繁殖的育肥畜的成本，包括出售前发生的饲料费、人工费和应分摊的间接费用等必要支出。

（四）水产养殖的动物和植物的成本，包括在出售或入库前耗用的苗种、饲料、肥料等材料费、人工费和应分摊的间接费用等必要支出。

第九条　自行营造或繁殖的生产性生物资产的成本，应当按照下列规定确定：

（一）自行营造的林木类生产性生物资产的成本，包括达到预定生产经营目的前发生的造林费、抚育费、营林设施费、良种试验费、调查设计费和应分摊的间接费用等必要支出。

（二）自行繁殖的产畜和役畜的成本，包括达到预定生产经营目的（成龄）前发生的饲料费、人工费和应分摊的间接费用等必要支出。达到预定生产经营目的，是指生产性生物资产进入正常生产期，可以多年连续稳定产出农产品、提供劳务或出租。

第十条　自行营造的公益性生物资产的成本，应当按照郁闭前发生的造林费、抚育费、森林保护费、营林设施费、良种试验费、调查设计费和应分摊的间接费用等必要支出确定。

第十一条　应计入生物资产成本的借款费用，按照《企业会计准则第17号──借款费用》处理。消耗性林木类生物资产发生的借款费用，应当在郁闭时停止资本化。

第十二条　投资者投入生物资产的成本，应当按照投资合同或协议约定的价值确定，但合同或协议约定价值不公允的除外。

第十三条　天然起源的生物资产的成本，应当按照名义金额确定。

第十四条　非货币性资产交换、债务重组和企业合并取得的生物资产的成本，应当分别按照《企业会计准则第7号──非货币性资产交换》、《企业会计准则第12号──债务重组》和《企业会计准则第20号──企业合并》确定。

第十五条　因择伐、间伐或抚育更新性质采伐而补植林木类生物资产发生的后续支出，应当计入林木类生物资产的成本。生物资产在郁闭或达到预定生产经营目的后发生的管护、饲养费用等后续支出，应当计入当期损益。

** 第三章 后续计量

第十六条　企业应当按照本准则第十七条至第二十一条的规定对生物资产进行后续计量，但本准则第二十二条规定的除外。

第十七条　企业对达到预定生产经营目的的生产性生物资产，应当按期计提折旧，并根据用途分别计入相关资产的成本或当期损益。

第十八条　企业应当根据生产性生物资产的性质、使用情况和有关经济利益的预期实现方式，合理确定其使用寿命、预计净残值和折旧方法。可选用的折旧方法包括年限平均法、工作量法、产量法等。生产性生物资产的使用寿命、预计净残值和折旧方法一经确定，不得随意变更。但是，符合本准则第二十条规定的除外。

第十九条　企业确定生产性生物资产的使用寿命，应当考虑下列因素：

（一）该资产的预计产出能力或实物产量；

（二）该资产的预计有形损耗，如产畜和役畜衰老、经济林老化等；

（三）该资产的预计无形损耗，如因新品种的出现而使现有的生产性生物资产的产出能力和产出农产品的质量等方面相对下降、市场需求的变化使生产性生物资产产出的农产品相对过时等。

第二十条　企业至少应当于每年年度终了对生产性生物资产的使用寿命、预计净残值和折旧方法进行复核。使用寿命或预计净残值的预期数与原先估计数有差异的，或者有关经济利益预期实现方式有重大改变的，应当作为会计估计变更，按照《企业会计准则第28号──会计政策、会计估计变更和差错更正》处理，调整生产性生物资产的使用寿命或预计净残值或者改变折旧方法。

第二十一条　企业至少应当于每年年度终了对消耗性生物资产和生产性生物资产进行检查，有确凿证据表明由于遭受自然灾害、病虫害、动物疫病侵袭或市场需求变化等原因，使消耗性生物资产的可变现净值或生产性生物资产的可收回金额低于其账面价值的，应当按照可变现净值或可收回金额低于账面价值的差额，计提生物资产跌价准备或减值准备，并计入当期损益。上述可变现净值和可收回金额，应当分别按照《企业会计准则第1号──存货》和《企业会计准则第8号──资产减值》确定。消耗性生物资产减值的影响因素已经消失的，减记金额应当予以恢复，并在原已计提的跌价准备金额内转回，转回的金额计入当期损益。生产性生物资产减值准备一经计提，不得转回。公益性生物资产不计提减值准备。

第二十二条　有确凿证据表明生物资产的公允价值能够持续可靠取得的，应当对生物资产采用公允价值计量。采用公允价值计量的，应当同时满足下列条件：

（一）生物资产有活跃的交易市场；

（二）能够从交易市场上取得同类或类似生物资产的市场价格及其他相关信息，从而对生物资产的公允价值作出合理估计。

** 第四章 收获与处置

第二十三条　对于消耗性生物资产，应当在收获或出售时，按照其账面价值结转成本。结转成本的方法包括加权平均法、个别计价法、蓄积量比例法、轮伐期年限法等。

第二十四条　生产性生物资产收获的农产品成本，按照产出或采收过程中发生的材料费、人工费和应分摊的间接费用等必要支出计算确定，并采用加权平均法、个别计价法、蓄积量比例法、轮伐期年限法等方法，将其账面价值结转为农产品成本。收获之后的农产品，应当按照《企业会计准则第1号──存货》处理。

第二十五条　生物资产改变用途后的成本，应当按照改变用途时的账面价值确定。

第二十六条　生物资产出售、盘亏或死亡、毁损时，应当将处置收入扣除其账面价值和相关税费后的余额计入当期损益。

** 第五章 披露

第二十七条　企业应当在附注中披露与生物资产有关的下列信息：

（一）生物资产的类别以及各类生物资产的实物数量和账面价值。

（二）各类消耗性生物资产的跌价准备累计金额，以及各类生产性生物资产的使用寿命、预计净残值、折旧方法、累计折旧和减值准备累计金额。

（三）天然起源生物资产的类别、取得方式和实物数量。

（四）用于担保的生物资产的账面价值。

（五）与生物资产相关的风险情况与管理措施。

第二十八条　企业应当在附注中披露与生物资产增减变动有关的下列信息：

（一）因购买而增加的生物资产；

（二）因自行培育而增加的生物资产；

（三）因出售而减少的生物资产；

（四）因盘亏或死亡、毁损而减少的生物资产；

（五）计提的折旧及计提的跌价准备或减值准备；

（六）其他变动。

* 企06 无形资产

（2006）财会[2006]3号

** 第一章 总则

第一条　为了规范无形资产的确认、计量和相关信息的披露，根据《企业会计准则──基本准则》，制定本准则。

第二条　下列各项适用其他相关会计准则：

（一）作为投资性房地产的土地使用权，适用《企业会计准则第3号──投资性房地产》。

（二）企业合并中形成的商誉，适用《企业会计准则第8号──资产减值》和《企业会计准则第20号──企业合并》。

（三）石油天然气矿区权益，适用《企业会计准则第27号──石油天然气开采》。

** 第二章 确认

第三条　无形资产，是指企业拥有或者控制的没有实物形态的可辨认非货币性资产。资产满足下列条件之一的，符合无形资产定义中的可辨认性标准：

（一）能够从企业中分离或者划分出来，并能单独或者与相关合同、资产或负债一起，用于出售、转移、授予许可、租赁或者交换。

（二）源自合同性权利或其他法定权利，无论这些权利是否可以从企业或其他权利和义务中转移或者分离。

第四条　无形资产同时满足下列条件的，才能予以确认：

（一）与该无形资产有关的经济利益很可能流入企业；

（二）该无形资产的成本能够可靠地计量。

第五条　企业在判断无形资产产生的经济利益是否很可能流入时，应当对无形资产在预计使用寿命内可能存在的各种经济因素作出合理估计，并且应当有明确证据支持。

第六条　企业无形项目的支出，除下列情形外，均应于发生时计入当期损益：

（一）符合本准则规定的确认条件、构成无形资产成本的部分；

（二）非同一控制下企业合并中取得的、不能单独确认为无形资产、构成购买日确认的商誉的部分。

第七条　企业内部研究开发项目的支出，应当区分研究阶段支出与开发阶段支出。研究是指为获取并理解新的科学或技术知识而进行的独创性的有计划调查。开发是指在进行商业性生产或使用前，将研究成果或其他知识应用于某项计划或设计，以生产出新的或具有实质性改进的材料、装置、产品等。

第八条　企业内部研究开发项目研究阶段的支出，应当于发生时计入当期损益。

第九条　企业内部研究开发项目开发阶段的支出，同时满足下列条件的，才能确认为无形资产：

（一）完成该无形资产以使其能够使用或出售在技术上具有可行性；

（二）具有完成该无形资产并使用或出售的意图；

（三）无形资产产生经济利益的方式，包括能够证明运用该无形资产生产的产品存在市场或无形资产自身存在市场，无形资产将在内部使用的，应当证明其有用性；

（四）有足够的技术、财务资源和其他资源支持，以完成该无形资产的开发，并有能力使用或出售该无形资产；

（五）归属于该无形资产开发阶段的支出能够可靠地计量。

第十条　企业取得的已作为无形资产确认的正在进行中的研究开发项目，在取得后发生的支出应当按照本准则第七条至第九条的规定处理。

第十一条　企业自创商誉以及内部产生的品牌、报刊名等，不应确认为无形资产。

** 第三章 初始计量

第十二条　无形资产应当按照成本进行初始计量。外购无形资产的成本，包括购买价款、相关税费以及直接归属于使该项资产达到预定用途所发生的其他支出。购买无形资产的价款超过正常信用条件延期支付，实质上具有融资性质的，无形资产的成本以购买价款的现值为基础确定。实际支付的价款与购买价款的现值之间的差额，除按照《企业会计准则第17号──借款费用》应予资本化的以外，应当在信用期间内计入当期损益。

第十三条　自行开发的无形资产，其成本包括自满足本准则第四条和第九条规定后至达到预定用途前所发生的支出总额，但是对于以前期间已经费用化的支出不再调整。

第十四条　投资者投入无形资产的成本，应当按照投资合同或协议约定的价值确定，但合同或协议约定价值不公允的除外。

第十五条　非货币性资产交换、债务重组、政府补助和企业合并取得的无形资产的成本，应当分别按照《企业会计准则第7号──非货币性资产交换》、《企业会计准则第12号──债务重组》、《企业会计准则第16号──政府补助》和《企业会计准则第20号──企业合并》确定。

** 第四章 后续计量

第十六条　企业应当于取得无形资产时分析判断其使用寿命。无形资产的使用寿命为有限的，应当估计该使用寿命的年限或者构成使用寿命的产量等类似计量单位数量；无法预见无形资产为企业带来经济利益期限的，应当视为使用寿命不确定的无形资产。

第十七条　使用寿命有限的无形资产，其应摊销金额应当在使用寿命内系统合理摊销。企业摊销无形资产，应当自无形资产可供使用时起，至不再作为无形资产确认时止。企业选择的无形资产摊销方法，应当反映与该项无形资产有关的经济利益的预期实现方式。无法可靠确定预期实现方式的，应当采用直线法摊销。无形资产的摊销金额一般应当计入当期损益，其他会计准则另有规定的除外。

第十八条　无形资产的应摊销金额为其成本扣除预计残值后的金额。已计提减值准备的无形资产，还应扣除已计提的无形资产减值准备累计金额。使用寿命有限的无形资产，其残值应当视为零，但下列情况除外：

（一）有第三方承诺在无形资产使用寿命结束时购买该无形资产。

（二）可以根据活跃市场得到预计残值信息，并且该市场在无形资产使用寿命结束时很可能存在。

第十九条　使用寿命不确定的无形资产不应摊销。

第二十条　无形资产的减值，应当按照《企业会计准则第8号──资产减值》处理。

第二十一条　企业至少应当于每年年度终了，对使用寿命有限的无形资产的使用寿命及摊销方法进行复核。无形资产的使用寿命及摊销方法与以前估计不同的，应当改变摊销期限和摊销方法。企业应当在每个会计期间对使用寿命不确定的无形资产的使用寿命进行复核。如果有证据表明无形资产的使用寿命是有限的，应当估计其使用寿命，并按本准则规定处理。

** 第五章 处置和报废

第二十二条　企业出售无形资产，应当将取得的价款与该无形资产账面价值的差额计入当期损益。

第二十三条　无形资产预期不能为企业带来经济利益的，应当将该无形资产的账面价值予以转销。

** 第六章 披露

第二十四条　企业应当按照无形资产的类别在附注中披露与无形资产有关的下列信息：

（一）无形资产的期初和期末账面余额、累计摊销额及减值准备累计金额。

（二）使用寿命有限的无形资产，其使用寿命的估计情况；使用寿命不确定的无形资产，其使用寿命不确定的判断依据。

（三）无形资产的摊销方法。

（四）用于担保的无形资产账面价值、当期摊销额等情况。

（五）计入当期损益和确认为无形资产的研究开发支出金额。

第二十五条　企业应当披露当期确认为费用的研究开发支出总额。

* 企07 非货币性资产交换

（2019修订）

** 第一章总则

第一条　为了规范非货币性资产交换的确认、计量和相关信息的披露，根据《企业会计准则──基本准则》，制定本准则。

第二条　非货币性资产交换，是指企业主要以固定资产、无形资产、投资性房地产和长期股权投资等非货币性资产进行的交换。该交换不涉及或只涉及少量的货币性资产（即补价）。

货币性资产，是指企业持有的货币资金和收取固定或可确定金额的货币资金的权利。非货币性资产，是指货币性资产以外的资产。

第三条　本准则适用于所有非货币性资产交换，但下列各项适用其他相关会计准则：

（一）企业以存货换取客户的非货币性资产的，适用《企业会计准则第14号──收入》。

（二）非货币性资产交换中涉及企业合并的，适用《企业会计准则第20号──企业合并》《企业会计准则第2号──长期股权投资》和《企业会计准则第33号──合并财务报表》。

（三）非货币性资产交换中涉及由《企业会计准则第22号──金融工具确认和计量》规范的金融资产的，金融资产的确认、终止确认和计量适用《企业会计准则第22号──金融工具确认和计量》和《企业会计准则第23号──金融资产转移》。

（四）非货币性资产交换中涉及由《企业会计准则第21号──租赁》规范的使用权资产或应收融资租赁款等的，相关资产的确认、终止确认和计量适用《企业会计准则第

  21 号──租赁》。
（五）非货币性资产交换的一方直接或间接对另一方持股且以股东身份进行交易的，或者非货币性资产交换的双方均受同一方或相同的多方终控制，且该非货币性资产交换的交易实质是交换的一方向另一方进行了权益性分配或交换的一方接受了另一方权益性投入的，适用权益性交易的有关会计处理规定。

** 第二章确认

第四条　企业应当分别按照下列原则对非货币性资产交换中的换入资产进行确认，对换出资产终止确认：

（一）对于换入资产，企业应当在换入资产符合资产定义并满足资产确认条件时予以确认；

（二）对于换出资产，企业应当在换出资产满足资产终止确认条件时终止确认。

第五条　换入资产的确认时点与换出资产的终止确认时点存在不一致的，企业在资产负债表日应当按照下列原则进行处理：

（一）换入资产满足资产确认条件，换出资产尚未满足终止确认条件的，在确认换入资产的同时将交付换出资产的义务确认为一项负债。

（二）换入资产尚未满足资产确认条件，换出资产满足终止确认条件的，在终止确认换出资产的同时将取得换入资产的权利确认为一项资产。

** 第三章以公允价值为基础计量

第六条　非货币性资产交换同时满足下列条件的，应当以公允价值为基础计量：

（一）该项交换具有商业实质；

（二）换入资产或换出资产的公允价值能够可靠地计量。换入资产和换出资产的公允价值均能够可靠计量的，应当以换出资产的公允价值为基础计量，但有确凿证据表明换入资产的公允价值更加可靠的除外。

第七条　满足下列条件之一的非货币性资产交换具有商业实质：

（一）换入资产的未来现金流量在风险、时间分布或金额方面与换出资产显著不同。

（二）使用换入资产所产生的预计未来现金流量现值与继续使用换出资产不同，且其差额与换入资产和换出资产的公允价值相比是重大的。

第八条　以公允价值为基础计量的非货币性资产交换，对于换入资产，应当以换出资产的公允价值和应支付的相关税费作为换入资产的成本进行初始计量；对于换出资产，应当在终止确认时，将换出资产的公允价值与其账面价值之间的差额计入当期损益。有确凿证据表明换入资产的公允价值更加可靠的，对于换入资产，应当以换入资产的公允价值和应支付的相关税费作为换入资产的初始计量金额；对于换出资产，应当在终止确认时，将换入资产的公允价值与换出资产账面价值之间的差额计入当期损益。

第九条　以公允价值为基础计量的非货币性资产交换，涉及补价的，应当按照下列规定进行处理：

（一）支付补价的，以换出资产的公允价值，加上支付补价的公允价值和应支付的相关税费，作为换入资产的成本，换出资产的公允价值与其账面价值之间的差额计入当期损益。有确凿证据表明换入资产的公允价值更加可靠的，以换入资产的公允价值和应支付的相关税费作为换入资产的初始计量金额，换入资产的公允价值减去支付补价的公允价值，与换出资产账面价值之间的差额计入当期损益。

（二）收到补价的，以换出资产的公允价值，减去收到补价的公允价值，加上应支付的相关税费，作为换入资产的成本，换出资产的公允价值与其账面价值之间的差额计入当期损益。有确凿证据表明换入资产的公允价值更加可靠的，以换入资产的公允价值和应支付的相关税费作为换入资产的初始计量金额，换入资产的公允价值加上收到补价的公允价值，与换出资产账面价值之间的差额计入当期损益。

第十条　以公允价值为基础计量的非货币性资产交换，同时换入或换出多项资产的，应当按照下列规定进行处理：

（一）对于同时换入的多项资产，按照换入的金融资产以外的各项换入资产公允价值相对比例，将换出资产公允价值总额（涉及补价的，加上支付补价的公允价值或减去收到补价的公允价值）扣除换入金融资产公允价值后的净额进行分摊，以分摊至各项换入资产的金额，加上应支付的相关税费，作为各项换入资产的成本进行初始计量。有确凿证据表明换入资产的公允价值更加可靠的，以各项换入资产的公允价值和应支付的相关税费作为各项换入资产的初始计量金额。

（二）对于同时换出的多项资产，将各项换出资产的公允价值与其账面价值之间的差额，在各项换出资产终止确认时计入当期损益。有确凿证据表明换入资产的公允价值更加可靠的，按照各项换出资产的公允价值的相对比例，将换入资产的公允价值总额（涉及补价的，减去支付补价的公允价值或加上收到补价的公允价值）分摊至各项换出资产，分摊至各项换出资产的金额与各项换出资产账面价值之间的差额，在各项换出资产终止确认时计入当期损益。

** 第四章以账面价值为基础计量

第十一条　不满足本准则第六条规定条件的非货币性资产交换，应当以账面价值为基础计量。对于换入资产，企业应当以换出资产的账面价值和应支付的相关税费作为换入资产的初始计量金额；对于换出资产，终止确认时不确认损益。

第十二条　以账面价值为基础计量的非货币性资产交换，涉及补价的，应当按照下列规定进行处理：

（一）支付补价的，以换出资产的账面价值，加上支付补价的账面价值和应支付的相关税费，作为换入资产的初始计量金额，不确认损益。

（二）收到补价的，以换出资产的账面价值，减去收到补价的公允价值，加上应支付的相关税费，作为换入资产的初始计量金额，不确认损益。

第十三条　以账面价值为基础计量的非货币性资产交换，同时换入或换出多项资产的，应当按照下列规定进行处理：

（一）对于同时换入的多项资产，按照各项换入资产的公允价值的相对比例，将换出资产的账面价值总额（涉及补价的，加上支付补价的账面价值或减去收到补价的公允价值）分摊至各项换入资产，加上应支付的相关税费，作为各项换入资产的初始计量金额。换入资产的公允价值不能够可靠计量的，可以按照各项换入资产的原账面价值的相对比例或其他合理的比例对换出资产的账面价值进行分摊。

（二）对于同时换出的多项资产，各项换出资产终止确认时均不确认损益。

** 第五章披露

第十四条　企业应当在附注中披露与非货币性资产交换有关的下列信息：

（一）非货币性资产交换是否具有商业实质及其原因。

（二）换入资产、换出资产的类别。

（三）换入资产初始计量金额的确定方式。

（四）换入资产、换出资产的公允价值以及换出资产的账面价值。

（五）非货币性资产交换确认的损益。

** 第六章衔接规定

第十五条　企业对2019年1月1日至本准则施行日之间发生的非货币性资产交换，应根据本准则进行调整。企业对2019年1月1日之前发生的非货币性资产交换，不需要按照本准则的规定进行追溯调整。

** 第七章附则

第十六条　本准则自2019年6月10日起施行。

第十七条　2006年2月15日财政部印发的《财政部关于印发<企业会计准则第1号──存货>等38项具体准则的通知》（财会﹝2006﹞3号）中的《企业会计准则第7号──非货币性资产交换》同时废止。财政部此前发布的有关非货币性资产交换会计处理规定与本准则不一致的，以本准则为准。

* 企08 资产减值

（2006）财会[2006]3号

** 第一章 总则

第一条　为了规范资产减值的确认、计量和相关信息的披露，根据《企业会计准则──基本准则》，制定本准则。

第二条　资产减值，是指资产的可收回金额低于其账面价值。本准则中的资产，除了特别规定外，包括单项资产和资产组。资产组，是指企业可以认定的小资产组合，其产生的现金流入应当基本上独立于其他资产或者资产组产生的现金流入。

第三条　下列各项适用其他相关会计准则：

（一）存货的减值，适用《企业会计准则第1号──存货》。

（二）采用公允价值模式计量的投资性房地产的减值，适用《企业会计准则第3号──投资性房地产》。

（三）消耗性生物资产的减值，适用《企业会计准则第5号──生物资产》。

（四）建造合同形成的资产的减值，适用《企业会计准则第15号──建造合同》。

（五）递延所得税资产的减值，适用《企业会计准则第18号──所得税》。

（六）融资租赁中出租人未担保余值的减值，适用《企业会计准则第21号──租赁》。

（七）《企业会计准则第22号──金融工具确认和计量》规范的金融资产的减值，适用《企业会计准则第22号──金融工具确认和计量》。

（八）未探明石油天然气矿区权益的减值，适用《企业会计准则第27号──石油天然气开采》。

** 第二章 可能发生减值资产的认定

第四条　企业应当在资产负债表日判断资产是否存在可能发生减值的迹象。因企业合并所形成的商誉和使用寿命不确定的无形资产，无论是否存在减值迹象，每年都应当进行减值测试。

第五条　存在下列迹象的，表明资产可能发生了减值：

（一）资产的市价当期大幅度下跌，其跌幅明显高于因时间的推移或者正常使用而预计的下跌。

（二）企业经营所处的经济、技术或者法律等环境以及资产所处的市场在当期或者将在近期发生重大变化，从而对企业产生不利影响。

（三）市场利率或者其他市场投资报酬率在当期已经提高，从而影响企业计算资产预计未来现金流量现值的折现率，导致资产可收回金额大幅度降低。

（四）有证据表明资产已经陈旧过时或者其实体已经损坏。

（五）资产已经或者将被闲置、终止使用或者计划提前处置。

（六）企业内部报告的证据表明资产的经济绩效已经低于或者将低于预期，如资产所创造的净现金流量或者实现的营业利润（或者亏损）远远低于（或者高于）预计金额等。

（七）其他表明资产可能已经发生减值的迹象。

** 第三章 资产可收回金额的计量

第六条　资产存在减值迹象的，应当估计其可收回金额。可收回金额应当根据资产的公允价值减去处置费用后的净额与资产预计未来现金流量的现值两者之间较高者确定。处置费用包括与资产处置有关的法律费用、相关税费、搬运费以及为使资产达到可销售状态所发生的直接费用等。

第七条　资产的公允价值减去处置费用后的净额与资产预计未来现金流量的现值，只要有一项超过了资产的账面价值，就表明资产没有发生减值，不需再估计另一项金额。

第八条　资产的公允价值减去处置费用后的净额，应当根据公平交易中销售协议价格减去可直接归属于该资产处置费用的金额确定。不存在销售协议但存在资产活跃市场的，应当按照该资产的市场价格减去处置费用后的金额确定。资产的市场价格通常应当根据资产的买方出价确定。在不存在销售协议和资产活跃市场的情况下，应当以可获取的最佳信息为基础，估计资产的公允价值减去处置费用后的净额，该净额可以参考同行业类似资产的近交易价格或者结果进行估计。企业按照上述规定仍然无法可靠估计资产的公允价值减去处置费用后的净额的，应当以该资产预计未来现金流量的现值作为其可收回金额。

第九条　资产预计未来现金流量的现值，应当按照资产在持续使用过程中和终处置时所产生的预计未来现金流量，选择恰当的折现率对其进行折现后的金额加以确定。预计资产未来现金流量的现值，应当综合考虑资产的预计未来现金流量、使用寿命和折现率等因素。

第十条　预计的资产未来现金流量应当包括下列各项：

（一）资产持续使用过程中预计产生的现金流入。

（二）为实现资产持续使用过程中产生的现金流入所必需的预计现金流出（包括为使资产达到预定可使用状态所发生的现金流出）。该现金流出应当是可直接归属于或者可通过合理和一致的基础分配到资产中的现金流出。

（三）资产使用寿命结束时，处置资产所收到或者支付的净现金流量。该现金流量应当是在公平交易中，熟悉情况的交易双方自愿进行交易时，企业预期可从资产的处置中获取或者支付的、减去预计处置费用后的金额。

第十一条　预计资产未来现金流量时，企业管理层应当在合理和有依据的基础上对资产剩余使用寿命内整个经济状况进行最佳估计。预计资产的未来现金流量，应当以经企业管理层批准的近财务预算或者预测数据，以及该预算或者预测期之后年份稳定的或者递减的增长率为基础。企业管理层如能证明递增的增长率是合理的，可以以递增的增长率为基础。建立在预算或者预测基础上的预计现金流量多涵盖5年，企业管理层如能证明更长的期间是合理的，可以涵盖更长的期间。在对预算或者预测期之后年份的现金流量进行预计时，所使用的增长率除了企业能够证明更高的增长率是合理的之外，不应当超过企业经营的产品、市场、所处的行业或者所在国家或者地区的长期平均增长率，或者该资产所处市场的长期平均增长率。

第十二条　预计资产的未来现金流量，应当以资产的当前状况为基础，不应当包括与将来可能会发生的、尚未作出承诺的重组事项或者与资产改良有关的预计未来现金流量。预计资产的未来现金流量也不应当包括筹资活动产生的现金流入或者流出以及与所得税收付有关的现金流量。企业已经承诺重组的，在确定资产的未来现金流量的现值时，预计的未来现金流入和流出数，应当反映重组所能节约的费用和由重组所带来的其他利益，以及因重组所导致的估计未来现金流出数。其中重组所能节约的费用和由重组所带来的其他利益，通常应当根据企业管理层批准的近财务预算或者预测数据进行估计；因重组所导致的估计未来现金流出数应当根据《企业会计准则第13号――或有事项》所确认的因重组所发生的预计负债金额进行估计。

第十三条　折现率是反映当前市场货币时间价值和资产特定风险的税前利率。该折现率是企业在购置或者投资资产时所要求的必要报酬率。在预计资产的未来现金流量时已经对资产特定风险的影响作了调整的，估计折现率不需要考虑这些特定风险。如果用于估计折现率的基础是税后的，应当将其调整为税前的折现率。

第十四条　预计资产的未来现金流量涉及外币的，应当以该资产所产生的未来现金流量的结算货币为基础，按照该货币适用的折现率计算资产的现值；然后将该外币现值按照计算资产未来现金流量现值当日的即期汇率进行折算。

** 第四章 资产减值损失的确定

第十五条　可收回金额的计量结果表明，资产的可收回金额低于其账面价值的，应当将资产的账面价值减记至可收回金额，减记的金额确认为资产减值损失，计入当期损益，同时计提相应的资产减值准备。

第十六条　资产减值损失确认后，减值资产的折旧或者摊销费用应当在未来期间作相应调整，以使该资产在剩余使用寿命内，系统地分摊调整后的资产账面价值（扣除预计净残值）。

第十七条　资产减值损失一经确认，在以后会计期间不得转回。

** 第五章 资产组的认定及减值处理

第十八条　有迹象表明一项资产可能发生减值的，企业应当以单项资产为基础估计其可收回金额。企业难以对单项资产的可收回金额进行估计的，应当以该资产所属的资产组为基础确定资产组的可收回金额。资产组的认定，应当以资产组产生的主要现金流入是否独立于其他资产或者资产组的现金流入为依据。同时，在认定资产组时，应当考虑企业管理层管理生产经营活动的方式（如是按照生产线、业务种类还是按照地区或者区域等）和对资产的持续使用或者处置的决策方式等。几项资产的组合生产的产品（或者其他产出）存在活跃市场的，即使部分或者所有这些产品（或者其他产出）均供内部使用，也应当在符合前款规定的情况下，将这几项资产的组合认定为一个资产组。如果该资产组的现金流入受内部转移价格的影响，应当按照企业管理层在公平交易中对未来价格的最佳估计数来确定资产组的未来现金流量。资产组一经确定，各个会计期间应当保持一致，不得随意变更。如需变更，企业管理层应当证明该变更是合理的，并根据本准则第二十七条的规定在附注中作相应说明。

第十九条　资产组账面价值的确定基础应当与其可收回金额的确定方式相一致。资产组的账面价值包括可直接归属于资产组与可以合理和一致地分摊至资产组的资产账面价值，通常不应当包括已确认负债的账面价值，但如不考虑该负债金额就无法确定资产组可收回金额的除外。资产组的可收回金额应当按照该资产组的公允价值减去处置费用后的净额与其预计未来现金流量的现值两者之间较高者确定。资产组在处置时如要求购买者承担一项负债（如环境恢复负债等）、该负债金额已经确认并计入相关资产账面价值，而且企业只能取得包括上述资产和负债在内的单一公允价值减去处置费用后的净额的，为了比较资产组的账面价值和可收回金额，在确定资产组的账面价值及其预计未来现金流量的现值时，应当将已确认的负债金额从中扣除。

第二十条　企业总部资产包括企业集团或其事业部的办公楼、电子数据处理设备等资产。总部资产的显著特征是难以脱离其他资产或者资产组产生独立的现金流入，而且其账面价值难以完全归属于某一资产组。有迹象表明某项总部资产可能发生减值的，企业应当计算确定该总部资产所归属的资产组或者资产组组合的可收回金额，然后将其与相应的账面价值相比较，据以判断是否需要确认减值损失。资产组组合，是指由若干个资产组组成的小资产组组合，包括资产组或者资产组组合，以及按合理方法分摊的总部资产部分。

第二十一条　企业对某一资产组进行减值测试，应当先认定所有与该资产组相关的总部资产，再根据相关总部资产能否按照合理和一致的基础分摊至该资产组分别下列情况处理。

（一）对于相关总部资产能够按照合理和一致的基础分摊至该资产组的部分，应当将该部分总部资产的账面价值分摊至该资产组，再据以比较该资产组的账面价值（包括已分摊的总部资产的账面价值部分）和可收回金额，并按照本准则第二十二条的规定处理。

（二）对于相关总部资产中有部分资产难以按照合理和一致的基础分摊至该资产组的，应当按照下列步骤处理：首先，在不考虑相关总部资产的情况下，估计和比较资产组的账面价值和可收回金额，并按照本准则第二十二条的规定处理。其次，认定由若干个资产组组成的小的资产组组合，该资产组组合应当包括所测试的资产组与可以按照合理和一致的基础将该部分总部资产的账面价值分摊其上的部分。后，比较所认定的资产组组合的账面价值（包括已分摊的总部资产的账面价值部分）和可收回金额，并按照本准则第二十二条的规定处理。

第二十二条　资产组或者资产组组合的可收回金额低于其账面价值的（总部资产和商誉分摊至某资产组或者资产组组合的，该资产组或者资产组组合的账面价值应当包括相关总部资产和商誉的分摊额），应当确认相应的减值损失。减值损失金额应当先抵减分摊至资产组或者资产组组合中商誉的账面价值，再根据资产组或者资产组组合中除商誉之外的其他各项资产的账面价值所占比重，按比例抵减其他各项资产的账面价值。以上资产账面价值的抵减，应当作为各单项资产（包括商誉）的减值损失处理，计入当期损益。抵减后的各资产的账面价值不得低于以下三者之中高者：该资产的公允价值减去处置费用后的净额（如可确定的）、该资产预计未来现金流量的现值（如可确定的）和零。因此而导致的未能分摊的减值损失金额，应当按照相关资产组或者资产组组合中其他各项资产的账面价值所占比重进行分摊。

** 第六章 商誉减值的处理

第二十三条　企业合并所形成的商誉，至少应当在每年年度终了进行减值测试。商誉应当结合与其相关的资产组或者资产组组合进行减值测试。相关的资产组或者资产组组合应当是能够从企业合并的协同效应中受益的资产组或者资产组组合，不应当大于按照《企业会计准则第35号──分部报告》所确定的报告分部。

第二十四条　企业进行资产减值测试，对于因企业合并形成的商誉的账面价值，应当自购买日起按照合理的方法分摊至相关的资产组；难以分摊至相关的资产组的，应当将其分摊至相关的资产组组合。在将商誉的账面价值分摊至相关的资产组或者资产组组合时，应当按照各资产组或者资产组组合的公允价值占相关资产组或者资产组组合公允价值总额的比例进行分摊。公允价值难以可靠计量的，按照各资产组或者资产组组合的账面价值占相关资产组或者资产组组合账面价值总额的比例进行分摊。企业因重组等原因改变了其报告结构，从而影响到已分摊商誉的一个或者若干个资产组或者资产组组合构成的，应当按照与本条前款规定相似的分摊方法，将商誉重新分摊至受影响的资产组或者资产组组合。

第二十五条　在对包含商誉的相关资产组或者资产组组合进行减值测试时，如与商誉相关的资产组或者资产组组合存在减值迹象的，应当先对不包含商誉的资产组或者资产组组合进行减值测试，计算可收回金额，并与相关账面价值相比较，确认相应的减值损失。再对包含商誉的资产组或者资产组组合进行减值测试，比较这些相关资产组或者资产组组合的账面价值（包括所分摊的商誉的账面价值部分）与其可收回金额，如相关资产组或者资产组组合的可收回金额低于其账面价值的，应当确认商誉的减值损失，按照本准则第二十二条的规定处理。

** 第七章 披露

第二十六条　企业应当在附注中披露与资产减值有关的下列信息：

（一）当期确认的各项资产减值损失金额。

（二）计提的各项资产减值准备累计金额。

（三）提供分部报告信息的，应当披露每个报告分部当期确认的减值损失金额。

第二十七条　发生重大资产减值损失的，应当在附注中披露导致每项重大资产减值损失的原因和当期确认的重大资产减值损失的金额。

（一）发生重大减值损失的资产是单项资产的，应当披露该单项资产的性质。提供分部报告信息的，还应披露该项资产所属的主要报告分部。

（二）发生重大减值损失的资产是资产组（或者资产组组合，下同）的，应当披露：

  1. 资产组的基本情况。
  2. 资产组中所包括的各项资产于当期确认的减值损失金额。
  3. 资产组的组成与前期相比发生变化的，应当披露变化的原因以及前期和当期资产组组成情况。

第二十八条　对于重大资产减值，应当在附注中披露资产（或者资产组，下同）可收回金额的确定方法。

（一）可收回金额按资产的公允价值减去处置费用后的净额确定的，还应当披露公允价值减去处置费用后的净额的估计基础。

（二）可收回金额按资产预计未来现金流量的现值确定的，还应当披露估计其现值时所采用的折现率，以及该资产前期可收回金额也按照其预计未来现金流量的现值确定的情况下，前期所采用的折现率。

第二十九条　第二十六条（一）、（二）和第二十七条（二）第2项信息应当按照资产类别予以披露。资产类别应当以资产在企业生产经营活动中的性质或者功能是否相同或者相似为基础确定。

第三十条　分摊到某资产组的商誉（或者使用寿命不确定的无形资产，下同）的账面价值占商誉账面价值总额的比例重大的，应当在附注中披露下列信息：

（一）分摊到该资产组的商誉的账面价值。

（二）该资产组可收回金额的确定方法。

  1. 可收回金额按照资产组公允价值减去处置费用后的净额确定的，还应当披露确定公允价值减去处置费用后的净额的方法。资产组的公允价值减去处置费用后的净额不是按照市场价格确定的，应当披露：

   
（1）企业管理层在确定公允价值减去处置费用后的净额时所采用的各关键假设及其依据。
   
（2）企业管理层在确定各关键假设相关的价值时，是否与企业历史经验或者外部信息来源相一致；如不一致，应当说明理由。

  2. 可收回金额按照资产组预计未来现金流量的现值确定的，应当披露：

   
（1）企业管理层预计未来现金流量的各关键假设及其依据。
   
（2）企业管理层在确定各关键假设相关的价值时，是否与企业历史经验或者外部信息来源相一致；如不一致，应当说明理由。
   
（3）估计现值时所采用的折现率。

第三十一条　商誉的全部或者部分账面价值分摊到多个资产组、且分摊到每个资产组的商誉的账面价值占商誉账面价值总额的比例不重大的，企业应当在附注中说明这一情况以及分摊到上述资产组的商誉合计金额。商誉账面价值按照相同的关键假设分摊到上述多个资产组、且分摊的商誉合计金额占商誉账面价值总额的比例重大的，企业应当在附注中说明这一情况，并披露下列信息：

（一）分摊到上述资产组的商誉的账面价值合计。

（二）采用的关键假设及其依据。

（三）企业管理层在确定各关键假设相关的价值时，是否与企业历史经验或者外部信息来源相一致；如不一致，应当说明理由。

* 企09 职工薪酬

（2014修订）

** 第一章 总则

第一条　为了规范职工薪酬的确认、计量和相关信息的披露，根据《企业会计准则──基本准则》，制定本准则。

第二条　职工薪酬，是指企业为获得职工提供的服务或解除劳动关系而给予的各种形式的报酬或补偿。职工薪酬包括短期薪酬、离职后福利、辞退福利和其他长期职工福利。企业提供给职工配偶、子女、受赡养人、已故员工遗属及其他受益人等的福利，也属于职工薪酬。

短期薪酬，是指企业在职工提供相关服务的年度报告期间结束后十二个月内需要全部予以支付的职工薪酬，因解除与职工的劳动关系给予的补偿除外。短期薪酬具体包括：职工工资、奖金、津贴和补贴，职工福利费，医疗保险费、工伤保险费和生育保险费等社会保险费，住房公积金，工会经费和职工教育经费，短期带薪缺勤，短期利润分享计划，非货币性福利以及其他短期薪酬。带薪缺勤，是指企业支付工资或提供补偿的职工缺勤，包括年休假、病假、短期伤残、婚假、产假、丧假、探亲假等。利润分享计划，是指因职工提供服务而与职工达成的基于利润或其他经营成果提供薪酬的协议。

离职后福利，是指企业为获得职工提供的服务而在职工退休或与企业解除劳动关系后，提供的各种形式的报酬和福利，短期薪酬和辞退福利除外。

辞退福利，是指企业在职工劳动合同到期之前解除与职工的劳动关系，或者为鼓励职工自愿接受裁减而给予职工的补偿。

其他长期职工福利，是指除短期薪酬、离职后福利、辞退福利之外所有的职工薪酬，包括长期带薪缺勤、长期残疾福利、长期利润分享计划等。

第三条　本准则所称职工，是指与企业订立劳动合同的所有人员，含全职、兼职和临时职工，也包括虽未与企业订立劳动合同但由企业正式任命的人员。未与企业订立劳动合同或未由其正式任命，但向企业所提供服务与职工所提供服务类似的人员，也属于职工的范畴，包括通过企业与劳务中介公司签订用工合同而向企业提供服务的人员。

第四条　下列各项适用其他相关会计准则：

（一）企业年金基金，适用《企业会计准则第10号──企业年金基金》。

（二）以股份为基础的薪酬，适用《企业会计准则第11号──股份支付》。

** 第二章 短期薪酬

第五条　企业应当在职工为其提供服务的会计期间，将实际发生的短期薪酬确认为负债，并计入当期损益，其他会计准则要求或允许计入资产成本的除外。

第六条　企业发生的职工福利费，应当在实际发生时根据实际发生额计入当期损益或相关资产成本。职工福利费为非货币性福利的，应当按照公允价值计量。

第七条　企业为职工缴纳的医疗保险费、工伤保险费、生育保险费等社会保险费和住房公积金，以及按规定提取的工会经费和职工教育经费，应当在职工为其提供服务的会计期间，根据规定的计提基础和计提比例计算确定相应的职工薪酬金额，并确认相应负债，计入当期损益或相关资产成本。

第八条　带薪缺勤分为累积带薪缺勤和非累积带薪缺勤。企业应当在职工提供服务从而增加了其未来享有的带薪缺勤权利时，确认与累积带薪缺勤相关的职工薪酬，并以累积未行使权利而增加的预期支付金额计量。企业应当在职工实际发生缺勤的会计期间确认与非累积带薪缺勤相关的职工薪酬。

累积带薪缺勤，是指带薪缺勤权利可以结转下期的带薪缺勤，本期尚未用完的带薪缺勤权利可以在未来期间使用。

非累积带薪缺勤，是指带薪缺勤权利不能结转下期的带薪缺勤，本期尚未用完的带薪缺勤权利将予以取消，并且职工离开企业时也无权获得现金支付。

第九条　利润分享计划同时满足下列条件的，企业应当确认相关的应付职工薪酬：

（一） 企业因过去事项导致现在具有支付职工薪酬的法定义务或推定义务；

（二）因利润分享计划所产生的应付职工薪酬义务金额能够可靠估计。属于下列三种情形之一的，视为义务金额能够可靠估计：

  1. 在财务报告批准报出之前企业已确定应支付的薪酬金额。
  2. 该短期利润分享计划的正式条款中包括确定薪酬金额的方式。
  3. 过去的惯例为企业确定推定义务金额提供了明显证据。

第十条　职工只有在企业工作一段特定期间才能分享利润的，企业在计量利润分享计划产生的应付职工薪酬时，应当反映职工因离职而无法享受利润分享计划福利的可能性。如果企业在职工为其提供相关服务的年度报告期间结束后十二个月内，不需要全部支付利润分享计划产生的应付职工薪酬，该利润分享计划应当适用本准则其他长期职工福利的有关规定。

** 第三章 离职后福利

第十一条　企业应当将离职后福利计划分类为设定提存计划和设定受益计划。离职后福利计划，是指企业与职工就离职后福利达成的协议，或者企业为向职工提供离职后福利制定的规章或办法等。其中，设定提存计划，是指向独立的基金缴存固定费用后，企业不再承担进一步支付义务的离职后福利计划；设定受益计划，是指除设定提存计划以外的离职后福利计划。

第十二条　企业应当在职工为其提供服务的会计期间，将根据设定提存计划计算的应缴存金额确认为负债，并计入当期损益或相关资产成本。根据设定提存计划，预期不会在职工提供相关服务的年度报告期结束后十二个月内支付全部应缴存金额的，企业应当参照本准则第十五条规定的折现率，将全部应缴存金额以折现后的金额计量应付职工薪酬。

第十三条　企业对设定受益计划的会计处理通常包括下列四个步骤：

（一）根据预期累计福利单位法，采用无偏且相互一致的精算假设对有关人口统计变量和财务变量等做出估计，计量设定受益计划所产生的义务，并确定相关义务的归属期间。企业应当按照本准则第十五条规定的折现率将设定受益计划所产生的义务予以折现，以确定设定受益计划义务的现值和当期服务成本。

（二）设定受益计划存在资产的，企业应当将设定受益计划义务现值减去设定受益计划资产公允价值所形成的赤字或盈余确认为一项设定受益计划净负债或净资产。设定受益计划存在盈余的，企业应当以设定受益计划的盈余和资产上限两项的孰低者计量设定受益计划净资产。其中，资产上限，是指企业可从设定受益计划退款或减少未来对设定受益计划缴存资金而获得的经济利益的现值。

（三）根据本准则第十六条的有关规定，确定应当计入当期损益的金额。

（四）根据本准则第十六条和第十七条的有关规定，确定应当计入其他综合收益的金额。在预期累计福利单位法下，每一服务期间会增加一个单位的福利权利，并且需对每一个单位单独计量，以形成终义务。企业应当将福利归属于提供设定受益计划的义务发生的期间。这一期间是指从职工提供服务以获取企业在未来报告期间预计支付的设定受益计划福利开始，至职工的继续服务不会导致这一福利金额显著增加之日为止。

第十四条　企业应当根据预期累计福利单位法确定的公式将设定受益计划产生的福利义务归属于职工提供服务的期间，并计入当期损益或相关资产成本。当职工后续年度的服务将导致其享有的设定受益计划福利水平显著高于以前年度时，企业应当按照直线法将累计设定受益计划义务分摊确认于职工提供服务而导致企业第一次产生设定受益计划福利义务至职工提供服务不再导致该福利义务显著增加的期间。在确定该归属期间时，不应考虑仅因未来工资水平提高而导致设定受益计划义务显著增加的情况。

第十五条　企业应当对所有设定受益计划义务予以折现，包括预期在职工提供服务的年度报告期间结束后的十二个月内支付的义务。折现时所采用的折现率应当根据资产负债表日与设定受益计划义务期限和币种相匹配的国债或活跃市场上的高质量公司债券的市场收益率确定。

第十六条　报告期末，企业应当将设定受益计划产生的职工薪酬成本确认为下列组成部分：

（一）服务成本，包括当期服务成本、过去服务成本和结算利得或损失。其中，当期服务成本，是指职工当期提供服务所导致的设定受益计划义务现值的增加额；过去服务成本，是指设定受益计划修改所导致的与以前期间职工服务相关的设定受益计划义务现值的增加或减少。

（二）设定受益计划净负债或净资产的利息净额，包括计划资产的利息收益、设定受益计划义务的利息费用以及资产上限影响的利息。

（三）重新计量设定受益计划净负债或净资产所产生的变动。除非其他会计准则要求或允许职工福利成本计入资产成本，上述第（一）项和第（二）项应计入当期损益；第（三）项应计入其他综合收益，并且在后续会计期间不允许转回至损益，但企业可以在权益范围内转移这些在其他综合收益中确认的金额。

第十七条　重新计量设定受益计划净负债或净资产所产生的变动包括下列部分：

（一）精算利得或损失，即由于精算假设和经验调整导致之前所计量的设定受益计划义务现值的增加或减少。

（二）计划资产回报，扣除包括在设定受益计划净负债或净资产的利息净额中的金额。

（三）资产上限影响的变动，扣除包括在设定受益计划净负债或净资产的利息净额中的金额。

第十八条　在设定受益计划下，企业应当在下列日期孰早日将过去服务成本确认为当期费用：

（一）修改设定受益计划时。

（二）企业确认相关重组费用或辞退福利时。

第十九条　企业应当在设定受益计划结算时，确认一项结算利得或损失。设定受益计划结算，是指企业为了消除设定受益计划所产生的部分或所有未来义务进行的交易，而不是根据计划条款和所包含的精算假设向职工支付福利。设定受益计划结算利得或损失是下列两项的差额：

（一）在结算日确定的设定受益计划义务现值。

（二）结算价格，包括转移的计划资产的公允价值和企业直接发生的与结算相关的支付。

** 第四章 辞退福利

第二十条　企业向职工提供辞退福利的，应当在下列两者孰早日确认辞退福利产生的职工薪酬负债，并计入当期损益：

（一）企业不能单方面撤回因解除劳动关系计划或裁减建议所提供的辞退福利时。

（二）企业确认与涉及支付辞退福利的重组相关的成本或费用时。

第二十一条　企业应当按照辞退计划条款的规定，合理预计并确认辞退福利产生的应付职工薪酬。辞退福利预期在其确认的年度报告期结束后十二个月内完全支付的，应当适用短期薪酬的相关规定；辞退福利预期在年度报告期结束后十二个月内不能完全支付的，应当适用本准则关于其他长期职工福利的有关规定。

** 第五章 其他长期职工福利

第二十二条　企业向职工提供的其他长期职工福利，符合设定提存计划条件的，应当适用本准则第十二条关于设定提存计划的有关规定进行处理。

第二十三条　除上述第二十二条规定的情形外，企业应当适用本准则关于设定受益计划的有关规定，确认和计量其他长期职工福利净负债或净资产。在报告期末，企业应当将其他长期职工福利产生的职工薪酬成本确认为下列组成部分：

（一）服务成本。

（二）其他长期职工福利净负债或净资产的利息净额。

（三）重新计量其他长期职工福利净负债或净资产所产生的变动。为简化相关会计处理，上述项目的总净额应计入当期损益或相关资产成本。

第二十四条　长期残疾福利水平取决于职工提供服务期间长短的，企业应当在职工提供服务的期间确认应付长期残疾福利义务，计量时应当考虑长期残疾福利支付的可能性和预期支付的期限；长期残疾福利与职工提供服务期间长短无关的，企业应当在导致职工长期残疾的事件发生的当期确认应付长期残疾福利义务。

** 第六章 披露

第二十五条　企业应当在附注中披露与短期职工薪酬有关的下列信息：

（一）应当支付给职工的工资、奖金、津贴和补贴及其期末应付未付金额。

（二）应当为职工缴纳的医疗保险费、工伤保险费和生育保险费等社会保险费及其期末应付未付金额。

（三）应当为职工缴存的住房公积金及其期末应付未付金额。

（四）为职工提供的非货币性福利及其计算依据。

（五）依据短期利润分享计划提供的职工薪酬金额及其计算依据。

（六）其他短期薪酬。

第二十六条　企业应当披露所设立或参与的设定提存计划的性质、计算缴费金额的公式或依据，当期缴费金额以及期末应付未付金额。

第二十七条　企业应当披露与设定受益计划有关的下列信息：

（一）设定受益计划的特征及与之相关的风险。

（二）设定受益计划在财务报表中确认的金额及其变动。

（三）设定受益计划对企业未来现金流量金额、时间和不确定性的影响。

（四）设定受益计划义务现值所依赖的重大精算假设及有关敏感性分析的结果。

第二十八条　企业应当披露支付的因解除劳动关系所提供辞退福利及其期末应付未付金额。

第二十九条　企业应当披露提供的其他长期职工福利的性质、金额及其计算依据。

** 第七章 衔接规定

第三十条　对于本准则施行日存在的离职后福利计划、辞退福利、其他长期职工福利，除本准则三十一条规定外，应当按照《企业会计准则第28号──会计政策、会计估计变更和差错更正》的规定采用追溯调整法处理。

第三十一条　企业比较财务报表中披露的本准则施行之前的信息与本准则要求不一致的，不需要按照本准则的规定进行调整。

** 第八章 附则

第三十二条　本准则自2014年7月1日起施行。

* 企业会计准则第10号──企业年金基金
** （2006）财会[2006]3号
** 第一章 总则
:PROPERTIES:
:heading: true
:END:
*** 第一条　为了规范企业年金基金的确认、计量和财务报表列报，根据《企业会计准则──基本准则》，制定本准则。
*** 第二条　[[企业年金基金]]，是指根据依法制定的企业年金计划筹集的资金及其投资运营收益形成的企业补充养老保险基金。
*** 第三条　企业年金基金应当作为独立的会计主体进行确认、计量和列报。
**** 委托人、受托人、托管人、账户管理人、投资管理人和其他为企业年金基金管理提供服务的主体，应当将企业年金基金与其固有资产和其他资产严格区分，确保企业年金基金的安全。
** 第二章 确认和计量
:PROPERTIES:
:heading: true
:END:
*** 第四条　企业年金基金应当分别*资产、负债、收入、费用和净资产*进行确认和计量。
*** 第五条　企业年金基金缴费及其运营形成的各项资产包括：货币资金、*应收证券清算款*、应收利息、*买入返售证券*、其他应收款、债券投资、基金投资、股票投资、其他投资等。
*** 第六条　企业年金基金在运营中根据国家规定的投资范围取得的国债、信用等级在投资级以上的金融债和企业债、可转换债、*投资性保险产品*、证券投资基金、股票等具有良好流动性的金融产品，其初始取得和后续估值应当以公允价值计量：
**** （一）初始取得投资时，应当以交易日支付的成交价款作为其公允价值。发生的交易费用直接计入当期损益。
**** （二）估值日对投资进行估值时，应当以其公允价值调整原账面价值，公允价值与原账面价值的差额计入当期损益。
**** 投资公允价值的确定，适用《[[企业会计准则第22号──金融工具确认和计量]]》。
*** 第七条　企业年金基金运营形成的各项负债包括：应付证券清算款、应付受益人待遇、应付受托人管理费、应付托管人管理费、应付投资管理人管理费、应交税金、卖出回购证券款、应付利息、应付佣金和其他应付款等。
*** 第八条　企业年金基金运营形成的各项收入包括：*存款利息收入、买入返售证券收入、公允价值变动收益、投资处置收益和其他收入*。
*** 第九条　收入应当按照下列规定确认和计量：
**** （一）存款利息收入，按照本金和适用的利率确定。
**** （二）*买入返售证券收入，在融券期限内按照买入返售证券价款和协议约定的利率确定*。
**** （三）公允价值变动收益，在估值日按照当日投资公允价值与原账面价值（即上一估值日投资公允价值）的差额确定。
**** （四）投资处置收益，在交易日按照卖出投资所取得的价款与其账面价值的差额确定。
**** （五）风险准备金补亏等其他收入，按照实际发生的金额确定。
*** 第十条　企业年金基金运营发生的各项费用包括：交易费用、受托人管理费、托管人管理费、投资管理人管理费、卖出回购证券支出和其他费用。
*** 第十一条　费用应当按照下列规定确认和计量：
**** （一）交易费用，包括支付给代理机构、咨询机构、券商的手续费和佣金及其他必要支出，按照实际发生的金额确定。
**** （二）受托人管理费、托管人管理费和投资管理人管理费，根据相关规定按实际计提的金额确定。
**** （三）*卖出回购证券支出，在融资期限内按照卖出回购证券价款和协议约定的利率确定*。
**** （四）其他费用，按照实际发生的金额确定。
*** 第十二条　企业年金基金的净资产，是指企业年金基金的资产减去负债后的余额。资产负债表日，应当将当期各项收入和费用结转至净资产。
**** 净资产应当分别企业和职工个人设置账户，根据企业年金计划按期将运营收益分配计入各账户。
*** 第十三条　净资产应当按照下列规定确认和计量：
**** （一）向企业和职工个人收取的缴费，按照收到的金额增加净资产。
**** （二）向受益人支付的待遇，按照应付的金额减少净资产。
**** （三）因职工调入企业而发生的个人账户转入金额，增加净资产。
**** （四）因职工调离企业而发生的个人账户转出金额，减少净资产。
** 第三章 列报
:PROPERTIES:
:heading: true
:END:
*** 第十四条　企业年金基金的财务报表包括*资产负债表、净资产变动表和附注*。
*** 第十五条　资产负债表反映企业年金基金在某一特定日期的财务状况，应当按照*资产、负债和净资产*分类列示。
*** 第十六条　资产类项目至少应当列示下列信息：
**** （一）货币资金；
**** （二）*应收证券清算款*；
**** （三）应收利息；
**** （四）*买入返售证券*；
**** （五）其他应收款；
**** （六）债券投资；
**** （七）基金投资；
**** （八）股票投资；
**** （九）其他投资；
**** （十）其他资产。
*** 第十七条　负债类项目至少应当列示下列信息：
**** （一）*应付证券清算款*；
**** （二）*应付受益人待遇*；
**** （三）应付受托人管理费；
**** （四）应付托管人管理费；
**** （五）应付投资管理人管理费；
**** （六）应交税金；
**** （七）*卖出回购证券款*；
**** （八）应付利息；
**** （九）应付佣金；
**** （十）其他应付款。
*** 第十八条　净资产类项目列示企业年金基金净值。
*** 第十九条　净资产变动表反映企业年金基金在一定会计期间的净资产增减变动情况，应当列示下列信息：
**** （一）期初净资产。
**** （二）本期净资产增加数，包括本期收入、收取企业缴费、收取职工个人缴费、个人账户转入。
**** （三）本期净资产减少数，包括本期费用、支付受益人待遇、个人账户转出。
**** （四）期末净资产。
*** 第二十条　附注应当披露下列信息：
**** （一）企业年金计划的主要内容及重大变化。
**** （二）投资种类、金额及公允价值的确定方法。
**** （三）各类投资占投资总额的比例。
**** （四）可能使投资价值受到重大影响的其他事项。
* 企11 股份支付

（2006）财会[2006]3号

** 第一章 总则

第一条　为了规范股份支付的确认、计量和相关信息的披露，根据《企业会计准则──基本准则》，制定本准则。

第二条　股份支付，是指企业为获取职工和其他方提供服务而授予权益工具或者承担以权益工具为基础确定的负债的交易。股份支付分为以权益结算的股份支付和以现金结算的股份支付。以权益结算的股份支付，是指企业为获取服务以股份或其他权益工具作为对价进行结算的交易。以现金结算的股份支付，是指企业为获取服务承担以股份或其他权益工具为基础计算确定的交付现金或其他资产义务的交易。本准则所指的权益工具是企业自身权益工具。

第三条　下列各项适用其他相关会计准则：

（一）企业合并中发行权益工具取得其他企业净资产的交易，适用《企业会计准则第20号──企业合并》。

（二）以权益工具作为对价取得其他金融工具等交易，适用《企业会计准则第22号──金融工具确认和计量》。

** 第二章 以权益结算的股份支付

第四条　以权益结算的股份支付换取职工提供服务的，应当以授予职工权益工具的公允价值计量。权益工具的公允价值，应当按照《企业会计准则第22号──金融工具确认和计量》确定。

第五条　授予后立即可行权的换取职工服务的以权益结算的股份支付，应当在授予日按照权益工具的公允价值计入相关成本或费用，相应增加资本公积。

授予日，是指股份支付协议获得批准的日期。

第六条　完成等待期内的服务或达到规定业绩条件才可行权的换取职工服务的以权益结算的股份支付，在等待期内的每个资产负债表日，应当以对可行权权益工具数量的最佳估计为基础，按照权益工具授予日的公允价值，将当期取得的服务计入相关成本或费用和资本公积。在资产负债表日，后续信息表明可行权权益工具的数量与以前估计不同的，应当进行调整，并在可行权日调整至实际可行权的权益工具数量。

等待期，是指可行权条件得到满足的期间。对于可行权条件为规定服务期间的股份支付，等待期为授予日至可行权日的期间；对于可行权条件为规定业绩的股份支付，应当在授予日根据可能的业绩结果预计等待期的长度。

可行权日，是指可行权条件得到满足、职工和其他方具有从企业取得权益工具或现金的权利的日期。

第七条　企业在可行权日之后不再对已确认的相关成本或费用和所有者权益总额进行调整。

第八条　以权益结算的股份支付换取其他方服务的，应当分别下列情况处理：

（一）其他方服务的公允价值能够可靠计量的，应当按照其他方服务在取得日的公允价值，计入相关成本或费用，相应增加所有者权益。

（二）其他方服务的公允价值不能可靠计量但权益工具公允价值能够可靠计量的，应当按照权益工具在服务取得日的公允价值，计入相关成本或费用，相应增加所有者权益。

第九条　在行权日，企业根据实际行权的权益工具数量，计算确定应转入实收资本或股本的金额，将其转入实收资本或股本。行权日，是指职工和其他方行使权利、获取现金或权益工具的日期。

** 第三章 以现金结算的股份支付

第十条　以现金结算的股份支付，应当按照企业承担的以股份或其他权益工具为基础计算确定的负债的公允价值计量。

第十一条　授予后立即可行权的以现金结算的股份支付，应当在授予日以企业承担负债的公允价值计入相关成本或费用，相应增加负债。

第十二条　完成等待期内的服务或达到规定业绩条件以后才可行权的以现金结算的股份支付，在等待期内的每个资产负债表日，应当以对可行权情况的最佳估计为基础，按照企业承担负债的公允价值金额，将当期取得的服务计入成本或费用和相应的负债。在资产负债表日，后续信息表明企业当期承担债务的公允价值与以前估计不同的，应当进行调整，并在可行权日调整至实际可行权水平。

第十三条　企业应当在相关负债结算前的每个资产负债表日以及结算日，对负债的公允价值重新计量，其变动计入当期损益。

** 第四章 披露

第十四条　企业应当在附注中披露与股份支付有关的下列信息：

（一）当期授予、行权和失效的各项权益工具总额。

（二）期末发行在外的股份期权或其他权益工具行权价格的范围和合同剩余期限。

（三）当期行权的股份期权或其他权益工具以其行权日价格计算的加权平均价格。

（四）权益工具公允价值的确定方法。企业对性质相似的股份支付信息可以合并披露。

第十五条　企业应当在附注中披露股份支付交易对当期财务状况和经营成果的影响，至少包括下列信息：

（一）当期因以权益结算的股份支付而确认的费用总额。

（二）当期因以现金结算的股份支付而确认的费用总额。

（三）当期以股份支付换取的职工服务总额及其他方服务总额。

* 企业会计准则第25号──保险合同

（财会〔2020〕20号）

** 关于修订印发《企业会计准则第25号──保险合同》的通知
:PROPERTIES:
:collapsed: true
:END:
*** 财会〔2020〕20号国务院有关部委、有关直属机构，各省、自治区、直辖市、计划单列市财政厅（局），新疆生产建设兵团财政局，有关中央管理企业：为了适应社会主义市场经济发展需要，规范保险合同的会计处理，提高会计信息质量，根据《企业会计准则──基本准则》，我部对《企业会计准则第25号──原保险合同》进行了修订，现予印发。有关事项通知如下：
*** 一、在境内外同时上市的企业以及在境外上市并采用国际财务报告准则或企业会计准则编制财务报表的企业，自2023年1月1日起执行；其他执行企业会计准则的企业自2026年1月1日起执行。同时，允许企业提前执行。\\
二、执行本准则的企业，不再执行我部于2006年2月印发的《财政部关于印发〈企业会计准则第1号──存货〉等38项具体准则的通知》（财会〔2006〕3号）中的《企业会计准则第25号──原保险合同》和《企业会计准则第26号──再保险合同》，以及我部于2009年12月印发的《保险合同相关会计处理规定》（财会〔2009〕15号）。执行中有何问题，请及时反馈我部。
** 第一章 总则
:PROPERTIES:
:heading: true
:collapsed: true
:END:
*** 第一条　为了规范保险合同的确认、计量和相关信息的列报，根据《企业会计准则──基本准则》，制定本准则。
*** 第二条　[[保险合同]]，是指企业（合同签发人）与保单持有人约定，在特定保险事项对保单持有人产生不利影响时给予其赔偿，并因此承担源于保单持有人重大保险风险的合同。[[保险事项]]，是指保险合同所承保的、产生保险风险的不确定未来事项。[[保险风险]]，是指从保单持有人转移至合同签发人的除金融风险之外的风险。
*** 第三条　本准则适用于下列保险合同：
**** （一）企业签发的保险合同（含分入的再保险合同）；
**** （二）企业分出的再保险合同；
**** （三）企业在合同转让或非同一控制下企业合并中取得的上述保险合同。签发保险合同的企业所签发的具有相机参与分红特征的投资合同适用本准则。[[再保险合同]]，是指再保险分入人（再保险合同签发人）与再保险分出人约定，对再保险分出人由对应的保险合同所引起的赔付等进行补偿的保险合同。具有相机参与分红特征的投资合同，是指赋予特定投资者合同权利以收取保证金额和附加金额的金融工具。附加金额由企业（合同签发人）基于特定项目回报相机决定，且预计构成合同利益的重要部分。
*** 第四条　下列各项适用其他相关会计准则：
**** （一）由《企业会计准则第6号──无形资产》、《企业会计准则第14号──收入》和《企业会计准则第21号──租赁》规范的基于非金融项目未来使用情况等形成的合同权利或义务，分别适用《企业会计准则第6号──无形资产》、《企业会计准则第14号──收入》和《企业会计准则第21号──租赁》。
**** （二）由《企业会计准则第9号──职工薪酬》和《企业会计准则第11号──股份支付》规范的职工薪酬计划、股份支付等形成的权利或义务，分别适用《企业会计准则第9号──职工薪酬》和《企业会计准则第11号──股份支付》。
**** （三）由《企业会计准则第14号──收入》规范的附有质量保证条款的销售，适用《企业会计准则第14号──收入》。
**** （四）生产商、经销商和零售商提供的余值担保，以及租赁合同中由承租方提供的余值担保，分别适用《企业会计准则第14号──收入》和《企业会计准则第21号──租赁》。
**** （五）企业合并中的或有对价，适用《企业会计准则第20号──企业合并》。
**** （六）财务担保合同，适用《企业会计准则第22号──金融工具确认和计量》、《企业会计准则第23号──金融资产转移》、《企业会计准则第24号──套期会计》和《企业会计准则第37号──金融工具列报》（以下统称金融工具相关会计准则）。企业明确表明将此类合同视作保险合同，并且已按照保险合同相关会计准则进行会计处理的，应当基于单项合同选择适用本准则或金融工具相关会计准则。选择一经作出，不得撤销。
**** （七）符合保险合同定义的信用卡合同或类似合同，如果定价时未单独评估和反映单一保单持有人的保险风险，合同条款中除保险保障服务以外的部分，适用金融工具相关会计准则或其他相关会计准则。
*** 第五条　符合保险合同定义但主要以固定收费方式提供服务的合同，同时符合下列条件的，企业可以选择适用《企业会计准则第14号──收入》或本准则：
**** （一）合同定价不反映对单个保单持有人的风险评估；
**** （二）合同通过提供服务而非支付现金补偿保单持有人；
**** （三）合同转移的保险风险主要源于保单持有人对服务的使用而非服务成本的不确定性。该选择应当基于单项合同，一经作出，不得撤销。
*** 第六条　符合保险合同定义但对保险事项的赔偿金额仅限于清算保单持有人因该合同而产生的支付义务的合同（如包含死亡豁免条款的贷款合同），企业可以选择适用金融工具相关会计准则或本准则。该选择应当基于保险合同组合，一经作出，不得撤销。
** 第二章 保险合同的识别、合并和分拆
:PROPERTIES:
:heading: true
:collapsed: true
:END:
*** 第七条　企业应当评估各单项合同的保险风险是否重大，据此判断该合同是否为保险合同。对于合同开始日经评估符合保险合同定义的合同，后续不再重新评估。
*** 第八条　企业基于整体商业目的而与同一或相关联的多个合同对方订立的多份保险合同，应当合并为一份合同进行会计处理，以反映其商业实质。
*** 第九条　保险合同中包含多个组成部分的，企业应当将下列组成部分予以分拆，并分别适用相关会计准则：
**** （一）符合《企业会计准则第22号──金融工具确认和计量》分拆条件的嵌入衍生工具，适用金融工具相关会计准则。
**** （二）可明确区分的投资成分，适用金融工具相关会计准则，但与投资成分相关的合同条款符合具有相机参与分红特征的投资合同定义的，应当适用本准则。
**** （三）可明确区分的商品或非保险合同服务的承诺，适用《企业会计准则第14号──收入》。保险合同经上述分拆后的剩余组成部分，适用本准则。投资成分，是指无论保险事项是否发生均须偿还给保单持有人的金额。保险合同服务，是指企业为保险事项提供的保险保障服务、为不具有直接参与分红特征的保险合同持有人提供的投资回报服务，以及代具有直接参与分红特征的保险合同持有人管理基础项目的投资相关服务。
*** 第十条　企业应当根据保险合同分拆情况分摊合同现金流量。合同现金流量扣除已分拆嵌入衍生工具和可明确区分的投资成分的现金流量后，在保险成分（含未分拆嵌入衍生工具、不可明确区分的投资成分和不可明确区分的商品或非保险合同服务的承诺，下同）和可明确区分的商品或非保险合同服务的承诺之间进行分摊，分摊至保险成分的现金流量适用本准则。
** 第三章 保险合同的分组
:PROPERTIES:
:heading: true
:collapsed: true
:END:
*** 第十一条　企业应当将具有相似风险且统一管理的保险合同归为同一保险合同组合。
*** 第十二条　企业应当将同一合同组合至少分为下列合同组：
**** （一）初始确认时存在亏损的合同组；
**** （二）初始确认时无显著可能性在未来发生亏损的合同组；
**** （三）该组合中剩余合同组成的合同组。企业不得将签发时间间隔超过一年的合同归入同一合同组。
*** 第十三条　企业可以按照获利水平、亏损程度或初始确认后在未来发生亏损的可能性等，对合同组作进一步细分。
*** 第十四条　企业应当以合同组合中单项合同为基础，逐项评估其归属的合同组。但有合理可靠的信息表明多项合同属于同一合同组的，企业可以多项合同为基础评估其归属的合同组。
*** 第十五条　企业针对不同特征保单持有人设定不同价格或承诺不同利益水平的实际能力因法律法规或监管要求而受到限制，并将因此限制而导致合同组合中的合同被归入不同合同组的，企业可以不考虑相关限制的影响，将这些合同归入同一合同组。
** 第四章 确认
:PROPERTIES:
:heading: true
:collapsed: true
:END:
*** 第十六条　企业应当在下列时点中的早时点确认其签发的合同组：
**** （一）责任期开始日；
**** （二）保单持有人首付款到期日，或者未约定首付款到期日时企业实际收到首付款日；
**** （三）发生亏损时。合同组合中的合同符合上述时点要求时，企业应当根据本准则第三章相关规定评估其归属的合同组，后续不再重新评估。[[责任期]]，是指企业向保单持有人提供保险合同服务的期间。
*** 第十七条　企业应当将合同组确认前已付或应付的、系统合理分摊至相关合同组的保险获取现金流量，确认为保险获取现金流量资产。[[保险获取现金流量]]，是指因销售、核保和承保已签发或预计签发的合同组而产生的，可直接归属于其对应合同组合的现金流量。
*** 第十八条　合同组合中的合同归入其所属合同组时，企业应当终止确认该合同对应的保险获取现金流量资产。
*** 第十九条　资产负债表日，如果事实和情况表明保险获取现金流量资产可能存在减值迹象，企业应当估计其可收回金额。保险获取现金流量资产的可收回金额低于其账面价值的，企业应当计提资产减值准备，确认减值损失，计入当期损益。*导致以前期间减值因素已经消失的，应当转回原已计提的资产减值准备，计入当期损益。*
** 第五章 计量
:PROPERTIES:
:heading: true
:END:
*** 第一节 一般规定
:PROPERTIES:
:heading: true
:END:
**** 第二十条　企业应当以合同组作为计量单元。企业应当在合同组初始确认时按照履约现金流量与合同服务边际之和对保险合同负债进行初始计量。[[合同服务边际]]，是指企业因在未来提供保险合同服务而将于未来确认的未赚利润。本准则第六章对分出的再保险合同组确认和计量另有规定的，从其规定。
**** 第二十一条　[[履约现金流量]]包括下列各项：
***** （一）与履行保险合同直接相关的未来现金流量的估计；
***** （二）货币时间价值及金融风险调整；
***** （三）非金融风险调整。[[非金融风险调整]]，是指企业在履行保险合同时，因承担非金融风险导致的未来现金流量在金额和时间方面的不确定性而要求得到的补偿。履约现金流量的估计不考虑企业自身的不履约风险。
**** 第二十二条　企业可以在高于合同组或合同组合的汇总层面估计履约现金流量，并采用系统合理的方法分摊至合同组。
**** 第二十三条　未来现金流量的估计应当符合下列要求：
***** （一）未来现金流量估计值为无偏的概率加权平均值；
***** （二）有关市场变量的估计应当与可观察市场数据一致；
***** （三）以当前可获得的信息为基础，反映计量时存在的情况和假设；
***** （四）与货币时间价值及金融风险调整分别估计，估计技术适合合并估计的除外。
**** 第二十四条　企业估计未来现金流量时应当考虑合同组内各单项合同边界内的现金流量，不得将合同边界外的未来现金流量用于合同组的计量。企业有权要求保单持有人支付保费或者有实质性义务向保单持有人提供保险合同服务的，该权利或义务所产生的现金流量在保险合同边界内。存在下列情形之一的，表明企业无实质性义务向保单持有人提供保险合同服务：
***** （一）企业有实际能力重新评估该保单持有人的风险，并据此可重新设定价格或承诺利益水平以充分反映该风险。
***** （二）企业有实际能力重新评估该合同所属合同组合的风险，并据此可重新设定价格或承诺利益水平以充分反映该风险，且重新评估日前对应保费在定价时未考虑重新评估日后的风险。
**** 第二十五条　企业应当采用适当的折现率对履约现金流量进行货币时间价值及金融风险调整，以反映货币时间价值及未包含在未来现金流量估计中的有关金融风险。适当的折现率应当同时符合下列要求：
***** （一）反映货币时间价值、保险合同现金流量特征以及流动性特征；
***** （二）基于与保险合同具有一致现金流量特征的金融工具当前可观察市场数据确定，且不考虑与保险合同现金流量无关但影响可观察市场数据的其他因素。
**** 第二十六条　企业在估计履约现金流量时应当考虑非金融风险调整，以反映非金融风险对履约现金流量的影响。企业应当单独估计非金融风险调整，不得在未来现金流量和折现率的估计中隐含非金融风险调整。
**** 第二十七条　企业应当在合同组初始确认时计算下列各项之和：
***** （一）履约现金流量；
***** （二）在该日终止确认保险获取现金流量资产以及其他相关资产或负债对应的现金流量；
***** （三）合同组内合同在该日产生的现金流量。
***** *上述各项之和反映为现金净流入的，企业应当将其确认为合同服务边际；反映为现金净流出的，企业应当将其作为首日亏损计入当期损益。*
**** 第二十八条　企业应当在资产负债表日按照未到期责任负债与已发生赔款负债之和对保险合同负债进行后续计量。[[未到期责任负债]]包括资产负债表日分摊至保险合同组的、与未到期责任有关的履约现金流量和当日该合同组的合同服务边际。[[已发生赔款负债]]包括资产负债表日分摊至保险合同组的、与已发生赔案及其他相关费用有关的履约现金流量。
**** 第二十九条　对于不具有直接参与分红特征的保险合同组，资产负债表日合同组的合同服务边际账面价值应当以期初账面价值为基础，经下列各项调整后予以确定：
***** （一）当期归入该合同组的合同对合同服务边际的影响金额；
***** （二）合同服务边际在当期计提的利息，计息利率为该合同组内合同确认时、不随基础项目回报变动的现金流量所适用的加权平均利率；
***** （三）与未来服务相关的履约现金流量的变动金额，但履约现金流量增加额超过合同服务边际账面价值所导致的亏损部分，以及履约现金流量减少额抵销的未到期责任负债的亏损部分除外；
***** （四）合同服务边际在当期产生的汇兑差额；
***** （五）合同服务边际在当期的摊销金额。
**** 第三十条　企业应当按照提供保险合同服务的模式，合理确定合同组在责任期内各个期间的责任单元，并据此对根据本准则第二十九条（一）至（四）调整后的合同服务边际账面价值进行摊销，计入当期及以后期间保险服务收入。
**** 第三十一条　企业因当期提供保险合同服务导致未到期责任负债账面价值的减少额，应当确认为保险服务收入；因当期发生赔案及其他相关费用导致已发生赔款负债账面价值的增加额，以及与之相关的履约现金流量的后续变动额，应当确认为保险服务费用。企业在确认保险服务收入和保险服务费用时，不得包含保险合同中的投资成分。
**** 第三十二条　企业应当将合同组内的保险获取现金流量，随时间流逝进行系统摊销，计入责任期内各个期间的保险服务费用，同时确认为保险服务收入，以反映该类现金流量所对应的保费的收回。
**** 第三十三条　企业应当将货币时间价值及金融风险的影响导致的未到期责任负债和已发生赔款负债账面价值变动额，作为保险合同金融变动额。企业可以选择将货币时间价值及金融风险的影响导致的非金融风险调整变动额不作为保险合同金融变动额。
**** 第三十四条　企业应当考虑持有的相关资产及其会计处理，在合同组合层面对保险合同金融变动额的会计处理做出下列会计政策选择：
***** （一）将保险合同金融变动额全额计入当期保险财务损益。
***** （二）将保险合同金融变动额分解计入当期保险财务损益和其他综合收益。选择该会计政策的，企业应当在合同组剩余期限内，采用系统合理的方法确定计入各个期间保险财务损益的金额，其与保险合同金融变动额的差额计入其他综合收益。[[保险财务损益]]，是指计入当期及以后期间损益的保险合同金融变动额。保险财务损益包括企业签发的保险合同的承保财务损益和分出的再保险合同的分出再保险财务损益。
**** 第三十五条　企业应当将非金融风险调整账面价值变动中除保险合同金融变动额以外的金额计入当期及以后期间损益。
**** 第三十六条　对于本准则适用范围内的具有相机参与分红特征的投资合同，企业应当按照本准则有关保险合同的规定进行会计处理，但下列各项特殊规定除外：
***** （一）初始确认的时点为企业成为合同一方的日期。
***** （二）企业有支付现金的实质性义务的，该义务所产生的现金流量在合同边界内。企业有实际能力对其支付现金的承诺进行重新定价以充分反映其承诺支付现金的金额及相关风险的，表明企业无支付现金的实质性义务。
***** （三）企业应当按照投资服务的提供模式，在合同组期限内采用系统合理的方法对合同服务边际进行摊销，计入当期及以后期间损益。
**** 第三十七条　对于中期财务报表中根据本准则作出的相关会计估计处理结果，企业应当就是否在本年度以后中期财务报表和年度财务报表中进行调整做出会计政策选择，并一致应用于本准则适用范围内的合同组。
**** 第三十八条　企业对产生外币现金流量的合同组进行计量时，应当将保险合同负债视为货币性项目，根据《企业会计准则第19号──外币折算》有关规定处理。资产负债表日，产生外币现金流量的合同组的汇兑差额应当计入当期损益。企业根据本准则第三十四条规定选择将保险合同金融变动额分解计入当期保险财务损益和其他综合收益的，与计入其他综合收益的金额相关的汇兑差额，应当计入其他综合收益。
*** 第二节 具有直接参与分红特征的保险合同组计量的特殊规定
:PROPERTIES:
:heading: true
:collapsed: true
:END:
**** 第三十九条　企业应当在合同开始日评估一项合同是否为具有直接参与分红特征的保险合同，后续不再重新评估。
**** 第四十条　具有直接参与分红特征的保险合同，是指在合同开始日同时符合下列条件的保险合同：

（一）合同条款规定保单持有人参与分享清晰可辨认的基础项目；

（二）企业预计将基础项目公允价值变动回报中的相当大部分支付给保单持有人；

（三）预计应付保单持有人金额变动中的相当大部分将随基础项目公允价值的变动而变动。
**** 第四十一条　企业应当按照基础项目公允价值扣除浮动收费的差额，估计具有直接参与分红特征的保险合同组的履约现金流量。浮动收费，是指企业因代保单持有人管理基础项目并提供投资相关服务而取得的对价，等于基础项目公允价值中企业享有份额减去不随基础项目回报变动的履约现金流量。
**** 第四十二条　对于具有直接参与分红特征的保险合同组，资产负债表日合同组的合同服务边际账面价值应当以期初账面价值为基础，经下列调整后予以确定：

（一）当期归入该合同组的合同对合同服务边际的影响金额。

（二）基础项目公允价值中企业享有份额的变动金额，但以下情形除外：1．企业使用衍生工具或分出再保险合同管理与该金额变动相关金融风险时，对符合本准则规定条件的，可以选择将该金额变动中由货币时间价值及金融风险的影响导致的部分计入当期保险财务损益。但企业将分出再保险合同的保险合同金融变动额分解计入当期保险财务损益和其他综合收益的，该金额变动中的相应部分也应予以分解。2．基础项目公允价值中企业享有份额的减少额超过合同服务边际账面价值所导致的亏损部分。3．基础项目公允价值中企业享有份额的增加额抵销的未到期责任负债的亏损部分。

（三）与未来服务相关且不随基础项目回报变动的履约现金流量的变动金额，但以下情形除外：1．企业使用衍生工具、分出再保险合同或以公允价值计量且其变动计入当期损益的非衍生金融工具管理与该履约现金流量变动相关金融风险时，对符合本准则规定条件的，可以选择将该履约现金流量变动中由货币时间价值及金融风险的影响导致的部分计入当期保险财务损益。但企业将分出再保险合同的保险合同金融变动额分解计入当期保险财务损益和其他综合收益的，该履约现金流量变动中的相应部分也应予以分解。2．该履约现金流量的增加额超过合同服务边际账面价值所导致的亏损部分。3．该履约现金流量的减少额抵销的未到期责任负债的亏损部分。

（四）合同服务边际在当期产生的汇兑差额。

（五）合同服务边际在当期的摊销金额。企业应当按照提供保险合同服务的模式，合理确定合同组在责任期内各个期间的责任单元，并据此对根据本条（一）至（四）调整后的合同服务边际账面价值进行摊销，计入当期及以后期间保险服务收入。企业可以对本条（二）和（三）中的变动金额进行合并调整。
**** 第四十三条　企业采用风险管理措施对具有直接参与分红特征的保险合同产生的金融风险予以缓释时，同时符合下列条件的，对于本准则第四十二条（二）和（三）相关金额变动中由货币时间价值及金融风险的影响导致的部分，可以选择不调整合同服务边际：

（一）企业制定了关于风险管理目标和策略的书面文件；

（二）保险合同与用于风险管理的衍生工具、分出再保险合同或以公允价值计量且其变动计入当期损益的非衍生金融工具之间存在经济抵销关系；

（三）经济抵销关系产生的价值变动中，信用风险的影响不占主导地位。企业不再符合上述条件时，应当自不符合之日起，将本准则第四十二条（二）和

（三）相关金额变动中由货币时间价值及金融风险的影响导致的部分调整合同服务边际，之前已经计入保险财务损益的金额不予调整。
**** 第四十四条　对于企业不持有基础项目的具有直接参与分红特征的保险合同组，企业应当根据本准则第三十四条规定，对保险合同金额变动额进行会计处理。对于企业持有基础项目的具有直接参与分红特征的保险合同组，企业根据本准则第三十四条规定，选择将保险合同金融变动额分解计入当期保险财务损益和其他综合收益的，计入当期保险财务损益的金额应当等于其持有的基础项目按照相关会计准则规定计入当期损益的金额。本准则第四十二条对保险合同金融变动额的会计处理另有规定的，从其规定。
**** 第四十五条　分入和分出的再保险合同不适用本节规定。
*** 第三节 亏损保险合同组计量的特殊规定
:PROPERTIES:
:heading: true
:collapsed: true
:END:
**** 第四十六条　合同组在初始确认时发生首日亏损的，或合同组合中的合同归入其所属亏损合同组而新增亏损的，企业应当确认亏损并计入当期保险服务费用，同时将该亏损部分增加未到期责任负债账面价值。初始确认时，亏损合同组的保险合同负债账面价值等于其履约现金流量。
**** 第四十七条　发生下列情形之一导致合同组在后续计量时发生亏损的，企业应当确认亏损并计入当期保险服务费用，同时将该亏损部分增加未到期责任负债账面价值：

（一）因与未来服务相关的未来现金流量或非金融风险调整的估计发生变更，导致履约现金流量增加额超过合同服务边际账面价值。

（二）对于具有直接参与分红特征的保险合同组，其基础项目公允价值中企业享有份额的减少额超过合同服务边际账面价值。
**** 第四十八条　企业在确认合同组的亏损后，应当将未到期责任负债账面价值的下列变动额，采用系统合理的方法分摊至未到期责任负债中的亏损部分和其他部分：

（一）因发生保险服务费用而减少的未来现金流量的现值；

（二）因相关风险释放而计入当期损益的非金融风险调整的变动金额；

（三）保险合同金融变动额。分摊至亏损部分的金额不得计入当期保险服务收入。
**** 第四十九条　企业在确认合同组的亏损后，应当按照下列规定进行后续计量：

（一）将因与未来服务相关的未来现金流量或非金融风险调整的估计变更所导致的履约现金流量增加额，以及具有直接参与分红特征的保险合同组的基础项目公允价值中企业享有份额的减少额，确认为新增亏损并计入当期保险服务费用，同时将该亏损部分增加未到期责任负债账面价值。

（二）将因与未来服务相关的未来现金流量或非金融风险调整的估计变更所导致的履约现金流量减少额，以及具有直接参与分红特征的保险合同组的基础项目公允价值中企业享有份额的增加额，减少未到期责任负债的亏损部分，冲减当期保险服务费用；超出亏损部分的金额，确认为合同服务边际。
*** 第四节 保险合同组计量的简化处理规定
:PROPERTIES:
:heading: true
:collapsed: true
:END:
**** 第五十条　符合下列条件之一的，企业可以采用保费分配法简化合同组的计量：

（一）企业能够合理预计采用本节简化处理规定与根据本准则前述章节规定计量合同组未到期责任负债的结果无重大差异。企业预计履约现金流量在赔案发生前将发生重大变化的，表明该合同组不符合本条件。

（二）该合同组内各项合同的责任期不超过一年。
**** 第五十一条　企业对其签发的保险合同采用保费分配法时，应当假设初始确认时该合同所属合同组合内不存在亏损合同，该假设与相关事实和情况不符的除外。
**** 第五十二条　企业采用保费分配法时，合同组内各项合同初始确认时的责任期均不超过一年的，可以选择在保险获取现金流量发生时将其确认为费用，计入当期损益。
**** 第五十三条　企业采用保费分配法计量合同组时，初始确认时未到期责任负债账面价值等于已收保费减去初始确认时发生的保险获取现金流量（根据本准则第五十二条规定选择在发生时计入当期损益的除外），减去（或加上）在合同组初始确认时终止确认的保险获取现金流量资产以及其他相关资产或负债的金额。资产负债表日未到期责任负债账面价值等于期初账面价值加上当期已收保费，减去当期发生的保险获取现金流量（根据本准则第五十二条规定选择在发生时计入当期损益的除外），加上当期确认为保险服务费用的保险获取现金流量摊销金额和针对融资成分的调整金额，减去因当期提供保险合同服务而确认为保险服务收入的金额和当期已付或转入已发生赔款负债中的投资成分。
**** 第五十四条　合同组内的合同中存在重大融资成分的，企业应当按照合同组初始确认时确定的折现率，对未到期责任负债账面价值进行调整，以反映货币时间价值及金融风险的影响。合同组初始确认时，如果企业预计提供保险合同服务每一部分服务的时点与相关保费到期日之间的间隔不超过一年，可以不考虑合同中存在的重大融资成分。
**** 第五十五条　相关事实和情况表明合同组在责任期内存在亏损时，企业应当将该日与未到期责任相关的履约现金流量超过按照本准则第五十三条确定的未到期责任负债账面价值的金额，计入当期保险服务费用，同时增加未到期责任负债账面价值。
**** 第五十六条　企业应当根据与已发生赔案及其他相关费用有关的履约现金流量计量已发生赔款负债。相关履约现金流量预计在赔案发生后一年内支付或收取的，企业可以不考虑货币时间价值及金融风险的影响，且一致应用于本准则第五十五条规定的相关履约现金流量的计算。
**** 第五十七条　企业应当将已收和预计收取的保费，在扣除投资成分并根据本准则第五十四条规定对重大融资成分进行调整后，分摊至当期的金额确认为保险服务收入。企业应当随时间流逝在责任期内分摊经调整的已收和预计收取的保费；保险合同的风险在责任期内不随时间流逝为主释放的，应当以保险服务费用预计发生时间为基础进行分摊。
** 第六章 分出的再保险合同组的确认和计量
:PROPERTIES:
:heading: true
:collapsed: true
:END:
*** 第五十八条　企业对分出的再保险合同组进行确认和计量，除本章另有规定外，应当按照本准则有关保险合同的其他相关规定进行处理，但本准则第五章关于亏损合同组计量的相关规定不适用于分出的再保险合同组。
*** 第五十九条　企业应当将同一分出的再保险合同组合至少分为下列合同组：

（一）初始确认时存在净利得的合同组；

（二）初始确认时无显著可能性在未来产生净利得的合同组；

（三）该组合中剩余合同组成的合同组。企业可以按照净成本或净利得水平以及初始确认后在未来产生净利得的可能性等，对分出的再保险合同组作进一步细分。企业不得将分出时间间隔超过一年的合同归入同一分出的再保险合同组。
*** 第六十条　企业应当在下列时点中的早时点确认其分出的再保险合同组：

（一）分出的再保险合同组责任期开始日；

（二）分出的再保险合同组所对应的保险合同组确认为亏损合同组时。
*** 第六十一条　分出的再保险合同组分出成比例责任的，企业应当在下列时点中的早时点确认该合同组：

（一）分出的再保险合同组责任期开始日和任一对应的保险合同初始确认时点中较晚的时点；

（二）分出的再保险合同组所对应的保险合同组确认为亏损合同组时。
*** 第六十二条　企业在初始确认其分出的再保险合同组时，应当按照履约现金流量与合同服务边际之和对分出再保险合同资产进行初始计量。分出再保险合同组的合同服务边际，是指企业为在未来获得再保险分入人提供的保险合同服务而产生的净成本或净利得。
*** 第六十三条　企业在估计分出的再保险合同组的未来现金流量现值时，采用的相关假设应当与计量所对应的保险合同组保持一致，并考虑再保险分入人的不履约风险。
*** 第六十四条　企业应当根据分出的再保险合同组转移给再保险分入人的风险，估计非金融风险调整。
*** 第六十五条　企业应当在分出的再保险合同组初始确认时计算下列各项之和：

（一） 履约现金流量；

（二） 在该日终止确认的相关资产或负债对应的现金流量；

（三） 分出再保险合同组内合同在该日产生的现金流量；

（四）\\

  分保摊回未到期责任资产亏损摊回部分的金额。企业应当将上述各项之和所反映的净成本或净利得，确认为合同服务边际。净成本与分出前发生的事项相关的，企业应当将其确认为费用并计入当期损益。
*** 第六十六条　企业应当在资产负债表日按照分保摊回未到期责任资产与分保摊回已发生赔款资产之和对分出再保险合同资产进行后续计量。分保摊回未到期责任资产包括资产负债表日分摊至分出的再保险合同组的、与未到期责任有关的履约现金流量和当日该合同组的合同服务边际。分保摊回已发生赔款资产包括资产负债表日分摊至分出的再保险合同组的、与已发生赔款及其他相关费用的摊回有关的履约现金流量。
*** 第六十七条　对于订立时点不晚于对应的保险合同确认时点的分出的再保险合同，企业在初始确认对应的亏损合同组或者将对应的亏损保险合同归入合同组而确认亏损时，应当根据下列两项的乘积确定分出再保险合同组分保摊回未到期责任资产亏损摊回部分的金额：

（一）对应的保险合同确认的亏损；

（二）预计从分出再保险合同组摊回的对应的保险合同赔付的比例。企业应当按照上述亏损摊回部分的金额调整分出再保险合同组的合同服务边际，同时确认为摊回保险服务费用，计入当期损益。企业在对分出的再保险合同组进行后续计量时，应当调整亏损摊回部分的金额以反映对应的保险合同亏损部分的变化，调整后的亏损摊回部分的金额不应超过企业预计从分出再保险合同组摊回的对应的保险合同亏损部分的相应金额。
*** 第六十八条　资产负债表日分出的再保险合同组的合同服务边际账面价值应当以期初账面价值为基础，经下列各项调整后予以确定：

（一）当期归入该合同组的合同对合同服务边际的影响金额；

（二）合同服务边际在当期计提的利息，计息利率为该合同组内合同确认时、不随基础项目回报变动的现金流量所适用的加权平均利率；

（三）根据本准则第六十七条第一款计算的分保摊回未到期责任资产亏损摊回部分的金额，以及与分出再保险合同组的履约现金流量变动无关的分保摊回未到期责任资产亏损摊回部分的转回；

（四）与未来服务相关的履约现金流量的变动金额，但分摊至对应的保险合同组且不调整其合同服务边际的履约现金流量变动而导致的变动，以及对应的保险合同组采用保费分配法计量时因确认或转回亏损而导致的变动除外；

（五）合同服务边际在当期产生的汇兑差额；

（六）合同服务边际在当期的摊销金额。企业应当按照取得保险合同服务的模式，合理确定分出再保险合同组在责任期内各个期间的责任单元，并据此对根据本条（一）至（五）调整后的合同服务边际账面价值进行摊销，计入当期及以后期间损益。
*** 第六十九条　再保险分入人不履约风险导致的履约现金流量变动金额与未来服务无关，企业不应当因此调整分出再保险合同组的合同服务边际。
*** 第七十条　企业因当期取得再保险分入人提供的保险合同服务而导致分保摊回未到期责任资产账面价值的减少额，应当确认为分出保费的分摊；因当期发生赔款及其他相关费用的摊回导致分保摊回已发生赔款资产账面价值的增加额，以及与之相关的履约现金流量的后续变动额，应当确认为摊回保险服务费用。企业应当将预计从再保险分入人收到的不取决于对应的保险合同赔付的金额，作为分出保费的分摊的减项。企业在确认分出保费的分摊和摊回保险服务费用时，不得包含分出再保险合同中的投资成分。
*** 第七十一条　符合下列条件之一的，企业可以采用保费分配法简化分出的再保险合同组的计量：

（一）企业能够合理预计采用保费分配法与不采用保费分配法计量分出再保险合同组的结果无重大差异。企业预计履约现金流量在赔案发生前将发生重大变化的，表明该合同组不符合本条件。

（二）该分出的再保险合同组内各项合同的责任期不超过一年。
*** 第七十二条　企业采用保费分配法计量分出的再保险合同组时，根据本准则第六十七条第一款计算的亏损摊回部分的金额应当调整分出再保险合同组的分保摊回未到期责任资产账面价值，同时确认为摊回保险服务费用，计入当期损益。
** 第七章 合同转让或非同一控制下企业合并中取得的保险合同的确认和计量
:PROPERTIES:
:heading: true
:collapsed: true
:END:
*** 第七十三条　企业对合同转让或非同一控制下企业合并中取得的保险合同进行确认和计量，除本章另有规定外，应当适用本准则其他相关规定。
*** 第七十四条　企业在合同转让或非同一控制下企业合并中取得的保险合同，应当视为在转让日（或购买日）订立该合同，并根据本准则相关规定将该合同归入其所属合同组。
*** 第七十五条　企业在合同转让或非同一控制下企业合并中为取得保险合同而收到或支付的对价，应当视为收取或支付的保费。
*** 第七十六条　企业在合同转让或非同一控制下企业合并中取得保险合同的会计处理适用《企业会计准则第20号──企业合并》等其他会计准则的，应当根据相关会计准则进行处理。
** 第八章 保险合同的修改和终止确认
:PROPERTIES:
:heading: true
:collapsed: true
:END:
*** 第七十七条　保险合同条款的修改符合下列条件之一的，企业应当终止确认原合同，并按照修改后的合同条款确认一项新合同：

（一）假设修改后的合同条款自合同开始日适用，出现下列情形之一的：1．修改后的合同不属于本准则的适用范围。2．修改后的合同应当予以分拆且分拆后适用本准则的组成部分发生变化。3．修改后的合同的合同边界发生实质性变化。4．修改后的合同归属于不同的合同组。

（二）原合同与修改后的合同仅有其一符合具有直接参与分红特征的保险合同的定义。

（三）原合同采用保费分配法，修改后的合同不符合采用保费分配法的条件。保险合同条款的修改不符合上述条件的，企业应当将合同条款修改导致的现金流量变动作为履约现金流量的估计变更进行处理。
*** 第七十八条　保险合同约定的义务因履行、取消或到期而解除的，企业应当终止确认保险合同。
*** 第七十九条　企业终止确认一项保险合同，应当按照下列规定进行处理：

（一）调整该保险合同所属合同组的履约现金流量，扣除与终止确认的权利义务相关的未来现金流量现值和非金融风险调整。

（二）调整合同组的合同服务边际。

（三）调整合同组在当期及以后期间的责任单元。
*** 第八十条　企业修改原合同并确认新合同时，应当按照下列两项的差额调整原合同所属合同组的合同服务边际：

（一）因终止确认原合同所导致的合同组履约现金流量变动金额；

（二）修改日订立与新合同条款相同的合同预计将收取的保费减去因修改原合同而收取的额外保费后的保费净额。企业在计量新合同所属合同组时，应当假设于修改日收到本条（二）中的保费净额。
*** 第八十一条　企业因合同转让而终止确认一项保险合同的，应当按照因终止确认该合同所导致的合同组履约现金流量变动金额与受让方收取的保费之间的差额，调整该合同所属合同组的合同服务边际。
*** 第八十二条　企业因合同修改或转让而终止确认一项保险合同时，应当将与该合同相关的、由于会计政策选择而在以前期间确认为其他综合收益的余额转入当期损益；但对于企业持有基础项目的具有直接参与分红特征的保险合同，企业不得仅因终止确认该保险合同而进行上述会计处理。
** 第九章 列报
:PROPERTIES:
:heading: true
:collapsed: true
:END:
*** 第一节 资产负债表和利润表相关项目的列示及披露
*** 第八十三条　企业应当根据自身实际情况，合理确定列报保险合同的详细程度，避免列报大量不重要信息或不恰当汇总实质性不同信息。企业可以按照合同类型、地理区域或报告分部等对保险合同的信息披露进行恰当汇总。
*** 第八十四条　企业应当在资产负债表中分别列示与保险合同有关的下列项目：

（一）保险合同资产；

（二）保险合同负债；

（三）分出再保险合同资产；

（四）分出再保险合同负债。企业签发的保险合同组合账面价值为借方余额的，列示为保险合同资产；分出的再保险合同组合账面价值为贷方余额的，列示为分出再保险合同负债。保险获取现金流量资产于资产负债表日的账面价值应当计入保险合同组合账面价值。
*** 第八十五条　企业应当在利润表中分别列示与保险合同有关的下列项目：

（一）保险服务收入；

（二）保险服务费用；

（三）分出保费的分摊；

（四）摊回保险服务费用；

（五）承保财务损益；

（六）分出再保险财务损益。
*** 第八十六条　企业应当在附注中分别就签发的保险合同和分出的再保险合同，单独披露未到期责任负债（或分保摊回未到期责任资产）和已发生赔款负债（或分保摊回已发生赔款资产）余额调节表，以反映与保险合同账面价值变动有关的下列信息：

（一）保险合同负债和保险合同资产（或分出再保险合同资产和分出再保险合同负债）的期初和期末余额及净额，及净额调节情况；

（二）未到期责任负债（或分保摊回未到期责任资产）当期变动情况，亏损部分

（或亏损摊回部分）应单独披露；

（三）已发生赔款负债（或分保摊回已发生赔款资产）当期变动情况，采用保费分配法的保险合同应分别披露未来现金流量现值和非金融风险调整；

（四）当期保险服务收入；

（五）当期保险服务费用，包括当期发生赔款及其他相关费用、保险获取现金流量的摊销、亏损部分的确认及转回和已发生赔款负债相关履约现金流量变动；

（六）当期分出保费的分摊；

（七）当期摊回保险服务费用，包括摊回当期发生赔款及其他相关费用、亏损摊回部分的确认及转回和分保摊回已发生赔款资产相关履约现金流量变动；

（八）不计入当期损益的投资成分，保费返还可以在此项合并披露；

（九）与当期服务无关但影响保险合同账面价值的金额，包括当期现金流量、再保险分入人不履约风险变动额、保险合同金融变动额、其他与保险合同账面价值变动有关的金额。当期现金流量应分别披露收到保费（或支付分出保费）、支付保险获取现金流量、支付赔款及其他相关费用（或收到摊回赔款及其他相关费用）。
*** 第八十七条　对于未采用保费分配法的保险合同，企业应当在附注中分别就签发的保险合同和分出的再保险合同，单独披露履约现金流量和合同服务边际余额调节表，以反映与保险合同账面价值变动有关的下列信息：

（一）保险合同负债和保险合同资产（或分出再保险合同资产和分出再保险合同负债）的期初和期末余额及净额，及净额调节情况；

（二）未来现金流量现值当期变动情况；

（三）非金融风险调整当期变动情况；

（四）合同服务边际当期变动情况；

（五）与当期服务相关的变动情况，包括合同服务边际的摊销、非金融风险调整的变动、当期经验调整；

（六）与未来服务相关的变动情况，包括当期初始确认的保险合同影响金额、调整合同服务边际的估计变更、不调整合同服务边际的估计变更；

（七）与过去服务相关的变动情况，包括已发生赔款负债（或分保摊回已发生赔款资产）相关履约现金流量变动；

（八）与当期服务无关但影响保险合同账面价值的金额，包括当期现金流量、再保险分入人不履约风险变动额、保险合同金融变动额、其他与保险合同账面价值变动有关的金额。当期现金流量应分别披露收到保费（或支付分出保费）、支付保险获取现金流量、支付赔款及其他相关费用（或收到摊回赔款及其他相关费用）。
*** 第八十八条　企业应当在附注中披露关于保险获取现金流量资产的下列定量信息：

（一）保险获取现金流量资产的期初和期末余额及其调节情况；

（二）保险获取现金流量资产减值准备当期计提和当期转回情况；

（三）期末保险获取现金流量资产预计在未来按适当的时间段终止确认的相关信息。
*** 第八十九条　对于未采用保费分配法的保险合同，企业应当在附注中分别就签发的保险合同和分出的再保险合同，披露当期初始确认的保险合同对资产负债表影响的下列信息：

（一）未来现金流出现值，保险获取现金流量的金额应单独披露；

（二）未来现金流入现值；

（三）非金融风险调整；

（四）合同服务边际。对于当期初始确认的亏损合同组以及在合同转让或非同一控制下企业合并中取得的保险合同，企业应当分别披露其对资产负债表影响的上述信息。
*** 第九十条　对于未采用保费分配法的签发的保险合同，企业应当在附注中披露与本期确认保险服务收入相关的下列定量信息：

（一）与未到期责任负债变动相关的保险服务收入，分别披露期初预计当期发生的保险服务费用、非金融风险调整的变动、合同服务边际的摊销、其他金额（如与当期服务或过去服务相关的保费经验调整）；

（二）保险获取现金流量的摊销。
*** 第九十一条　对于未采用保费分配法的保险合同，企业应当在附注中分别就签发的保险合同和分出的再保险合同，披露期末合同服务边际在剩余期限内按适当的时间段摊销计入利润表的定量信息。
*** 第九十二条　企业应当披露当期保险合同金融变动额的定量信息及其解释性说明，包括对保险合同金融变动额与相关资产投资回报关系的说明。
*** 第九十三条　企业应当披露与具有直接参与分红特征的保险合同相关的下列信息：

（一）基础项目及其公允价值；

（二）根据本准则第四十二条和第四十三条规定，将货币时间价值及金融风险的影响金额计入当期保险财务损益或其他综合收益对当期合同服务边际的影响。
*** 第九十四条　对于具有直接参与分红特征的保险合同组，企业选择将保险合同金融变动额分解计入当期保险财务损益和其他综合收益的，根据本准则第四十四条规定，因是否持有基础项目的情况发生变动导致计入当期保险财务损益的计量方法发生变更的，应当披露变更原因和对财务报表项目的影响金额，以及相关合同组在变更日的账面价值。
*** 第二节 与保险合同计量相关的披露
*** 第九十五条　企业应当披露与保险合同计量所采用的方法、输入值和假设等相关的下列信息：

（一）保险合同计量所采用的方法以及估计相关输入值的程序。企业应当披露相关输入值的定量信息，不切实可行的除外。

（二）本条（一）中所述方法和程序的变更及其原因，以及受影响的合同类型。

（三）与保险合同计量有关的下列信息：1．对于不具有直接参与分红特征的保险合同，区分相机抉择与其他因素导致未来现金流量估计变更的方法；2．确定非金融风险调整的计量方法及计量结果所对应的置信水平，以及非金融风险调整变动额根据本准则第三十三条在利润表中的列示方法；3．确定折现率的方法，以及用于不随基础项目回报变动的现金流量折现的收益率曲线

（或收益率曲线范围）；4．确定投资成分的方法；5．确定责任单元组成部分及相对权重的方法。
*** 第九十六条　企业选择将保险合同金融变动额分解计入当期保险财务损益和其他综合收益的，应当披露确定保险财务损益金额的方法及其说明。
*** 第九十七条　对于采用保费分配法计量的保险合同组，企业应当披露下列信息：

（一）合同组适用保费分配法的判断依据；

（二）未到期责任负债（或分保摊回未到期责任资产）和已发生赔款负债（或分保摊回已发生赔款资产）的计量是否反映货币时间价值及金融风险的影响；

（三）是否在保险获取现金流量发生时将其确认为费用。
*** 第三节 与风险相关的披露
*** 第九十八条　企业应当披露与保险合同产生的保险风险和金融风险等相关的定性和定量信息。金融风险包括市场风险、信用风险、流动性风险等。
*** 第九十九条　对于保险合同产生的各类风险，企业应当按类别披露下列信息：

（一）风险敞口及其形成原因，以及在本期发生的变化。

（二）风险管理的目标、政策和程序以及计量风险的方法及其在本期发生的变化。

（三）期末风险敞口的汇总数据。该数据应当以向内部关键管理人员提供的相关信息为基础。期末风险敞口不能反映企业本期风险敞口变动情况的，企业应当进一步提供相关信息。

（四）风险集中度信息，包括企业确定风险集中度的说明和参考因素（如保险事项类型、行业特征、地理区域、货币种类等）。
*** 第一百条　企业应当披露相关监管要求（如低资本要求、保证利率等）对本准则适用范围内的合同的影响。保险合同分组时应用本准则第十五条规定的，企业应当披露这一事实。
*** 第一百零一条　企业应当对保险风险和市场风险进行敏感性分析并披露下列信息：

（一）资产负债表日保险风险变量和各类市场风险变量发生合理、可能的变动时，将对企业损益和所有者权益产生的影响。对于保险风险，敏感性分析应当反映对企业签发的保险合同及其经分出的再保险合同进行风险缓释后的影响。对于各类市场风险，敏感性分析应当反映保险合同所产生的风险变量与企业持有的金融资产所产生的风险变量之间的关联性。

（二）本期进行敏感性分析所使用的方法和假设，以及在本期发生的变化及其原因。
*** 第一百零二条　企业为管理保险合同所产生的风险，采用不同于本准则第一百零一条中所述方法进行敏感性分析的，应当披露下列信息：

（一）用于敏感性分析的方法、选用的主要参数和假设；

（二）所用方法的目的，以及该方法提供信息的局限性。
*** 第一百零三条　企业应当披露索赔进展情况，以反映已发生赔款的实际赔付金额与未经折现的预计赔付金额的比较信息，及其与资产负债表日已发生赔款负债账面价值的调节情况。索赔进展情况的披露应当从赔付时间和金额在资产负债表日仍存在不确定性的重大赔付早发生期间开始，但长披露期限可不超过十年。赔付时间和金额的不确定性在未来一年内将消除的索赔进展信息可以不披露。
*** 第一百零四条　企业应当披露与保险合同所产生的信用风险相关的下列信息：

（一）签发的保险合同和分出的再保险合同分别于资产负债表日的大信用风险敞口；

（二）与分出再保险合同资产的信用质量相关的信息。
*** 第一百零五条　企业应当披露与保险合同所产生的流动性风险相关的下列信息：

（一）对管理流动性风险的说明。

（二）对资产负债表日保险合同负债和分出再保险合同负债的到期期限分析。到期期限分析应当基于合同组合，所使用的时间段至少应当为资产负债表日后一年以内、一年至两年以内、两年至三年以内、三年至四年以内、四年至五年以内、五年以上。列入各时间段内的金额可以是未来现金流量现值或者未经折现的合同剩余净现金流量。到期期限分析可以不包括采用保费分配法计量的保险合同负债和分出再保险合同负债中与未到期责任相关的部分。

（三）保单持有人可随时要求偿还的金额。企业应当说明该金额与相关保险合同组合账面价值之间的关联性。
** 第十章 衔接规定
:PROPERTIES:
:heading: true
:collapsed: true
:END:
*** 第一百零六条　首次执行日之前的保险合同会计处理与本准则规定不一致的，企业应当按照《企业会计准则第28号──会计政策、会计估计变更和差错更正》的规定采用追溯调整法处理，但本准则另有规定的除外。企业进行追溯调整的，无须披露当期和各个列报前期财务报表受影响项目和每股收益的调整金额。
*** 第一百零七条　企业采用追溯调整法时，应当在过渡日按照下列规定进行衔接处理：
**** （一）假设一直按照本准则要求识别、确认和计量保险合同组；
**** （二）假设一直按照本准则要求识别、确认和计量保险获取现金流量资产，但无须估计该资产于过渡日前的可收回金额；
**** （三）确认追溯调整对所有者权益的累积影响数；
**** （四）不得在过渡日前运用本准则第四十三条规定的风险管理缓释选择权。过渡日是指本准则首次执行日前近一个会计年度的期初，企业列报经调整的更早期间的比较信息的，过渡日是更早比较期间的期初。
*** 第一百零八条　对合同组采用追溯调整法不切实可行的，企业应当采用修正追溯调整法或公允价值法。对合同组采用修正追溯调整法也不切实可行的，企业应当采用公允价值法。修正追溯调整法，是指企业在对本章所涉及相关事项采用追溯调整法不切实可行时，使用在过渡日无须付出不必要的额外成本或努力即可获得的合理可靠的信息，以获得接近追溯调整法结果为目标，在衔接处理上按本准则规定进行简化的方法。公允价值法，是指以过渡日合同组公允价值与履约现金流量的差额确定合同组在该日的合同服务边际或未到期责任负债亏损部分，以及在衔接处理上按本准则规定进行简化的方法。企业在过渡日前符合本准则第四十三条规定条件，使用衍生工具、分出的再保险合同或以公允价值计量且其变动计入当期损益的非衍生金融工具管理合同组产生的金融风险，并自过渡日起采用未来适用法运用风险管理缓释选择权进行会计处理的，企业可以对该合同组采用公允价值法进行衔接处理。
*** 第一百零九条　企业采用修正追溯调整法时，应当在过渡日根据本准则规定识别下列事项并进行衔接处理：
**** （一）保险合同组，但在按照本准则规定进行保险合同分组时无法获得合理可靠的信息的，企业可以将签发或分出时间间隔超过一年的合同归入同一合同组；
**** （二）具有直接参与分红特征的保险合同；
**** （三）不具有直接参与分红特征的保险合同中的相机抉择现金流量；
**** （四）具有相机参与分红特征的投资合同。企业采用修正追溯调整法时，对于在合同转让或非同一控制下企业合并中取得的保险合同，应当将该类合同在转让日或购买日前已发生的赔付义务确认为已发生赔款负债。
*** 第一百一十条　对不具有直接参与分红特征的保险合同组在过渡日的合同服务边际或未到期责任负债亏损部分采用修正追溯调整法时，企业应当按照下列规定进行衔接处理：
**** （一）以过渡日或更早日期（如适用）估计的未来现金流量为基础，根据合同组初始确认时至过渡日或更早日期（如适用）发生的现金流量进行调整，确定合同组在初始确认时的未来现金流量；
**** （二）基于过渡日前近至少三个会计年度可观察数据，考虑该数据与本准则第二十五条规定的折现率的相似性或差异，采用适当方法确定合同组在初始确认时或以后的折现率；
**** （三）以过渡日估计的非金融风险调整金额为基础，根据在过渡日签发或分出的类似保险合同的相关风险释放方式，估计过渡日之前合同组非金融风险调整的变动金额，确定合同组在初始确认时的非金融风险调整金额；
**** （四）采用与过渡日后一致的方法将过渡日前已付或应付的保险获取现金流量系统合理地分摊至过渡日确认和预计将于过渡日后确认的合同组，分别调整过渡日合同服务边际和确认为保险获取现金流量资产。企业无法获得合理可靠的信息进行上述处理的，则不应调整合同服务边际或确认保险获取现金流量资产；
**** （五）合同组在初始确认时根据本条（一）至（四）确认合同服务边际的，应当按照本条（二）确定的初始确认时折现率计提利息，并基于过渡日合同组中的剩余责任单元和该日前的责任单元，确定过渡日前计入损益的合同服务边际；
**** （六）合同组在初始确认时根据本条（一）至（四）确认未到期责任负债亏损部分的，应当采用系统合理的方法，确定分摊至过渡日前的亏损部分；
**** （七）对于订立时点不晚于对应的亏损保险合同确认时点的分出的再保险合同，应当根据过渡日对应的亏损保险合同的未到期责任负债亏损部分乘以预计从分出的再保险合同组摊回的对应的保险合同赔付的比例，计算分出再保险合同组分保摊回未到期责任资产在过渡日的亏损摊回部分金额，企业无法获得合理可靠的信息确定该亏损摊回部分金额的，则不应确认亏损摊回部分。
*** 第一百一十一条　对具有直接参与分红特征的保险合同组在过渡日的合同服务边际或未到期责任负债亏损部分采用修正追溯调整法时，企业应当按照下列规定进行衔接处理：

（一）以过渡日基础项目公允价值减去该日履约现金流量的金额为基础，根据过渡日前相关现金流量以及非金融风险调整的变动进行恰当调整；

（二）采用与过渡日后一致的方法将过渡日前已付或应付的保险获取现金流量系统合理地分摊至过渡日确认和预计将于过渡日后确认的合同组，分别调整过渡日合同服务边际和确认为保险获取现金流量资产。企业无法获得合理可靠的信息进行上述处理的，则不应调整合同服务边际或确认保险获取现金流量资产；

（三）合同组根据本条（一）和（二）确认合同服务边际的，应当基于过渡日合同组中的剩余责任单元和该日前的责任单元，确定过渡日前计入损益的合同服务边际；

（四）合同组根据本条（一）和（二）确认未到期责任负债亏损部分的，应当将该亏损部分调整为零，同时将该亏损部分增加过渡日未到期责任负债账面价值。
*** 第一百一十二条　企业对过渡日保险合同金融变动额采用修正追溯调整法时，应当按照下列规定进行衔接处理：

（一）根据本准则第一百零九条（一）规定将签发或分出时间相隔超过一年的合同归入同一合同组的，可以在过渡日确定合同组初始确认时或以后适用的折现率。企业根据本准则第三十四条选择将保险合同金融变动额分解计入保险财务损益和其他综合收益的，应当采用适当方法确定过渡日计入其他综合收益的累计金额。

（二）未将签发或分出时间相隔超过一年的合同归入同一合同组的，应当按照本准则第一百一十条（二）估计合同组初始确认时或以后适用的折现率。企业根据本准则第三十四条选择将保险合同金融变动额分解计入保险财务损益和计入其他综合收益的，应当采用适当方法确定过渡日计入其他综合收益的累计金额。
*** 第一百一十三条　企业根据本准则第三十七条规定选择不调整中期财务报表有关会计估计处理结果的会计政策的，应当在过渡日对该会计政策采用追溯调整法处理。采用追溯调整法不切实可行的，企业可以采用修正追溯调整法，对保险合同金融变动额和不具有直接参与分红特征的保险合同的合同服务边际或未到期责任负债亏损部分进行衔接处理时，视同过渡日前未编制中期财务报表。
*** 第一百一十四条　企业采用公允价值法时，可以使用在合同开始日或初始确认时根据合同条款和市场状况可确定的合理可靠的信息，或使用在过渡日可获得的合理可靠的信息，根据本准则规定识别下列事项并进行衔接处理：

（一）保险合同组，企业可以将签发或分出时间间隔超过一年的合同归入同一合同组；

（二）具有直接参与分红特征的保险合同；

（三）不具有直接参与分红特征的保险合同中的相机抉择现金流量；

（四）具有相机参与分红特征的投资合同。企业采用公允价值法时，对于在合同转让或非同一控制下企业合并中取得的保险合同，可以将该类合同在转让日或购买日前已发生的赔付义务确认为已发生赔款负债。
*** 第一百一十五条　企业采用公允价值法时，按照下列规定进行衔接处理：

（一）企业可以在过渡日确定合同组初始确认时或以后适用的折现率；

（二）对于分出的再保险合同组对应亏损保险合同的，应当根据过渡日对应的亏损保险合同的未到期责任负债亏损部分乘以预计从分出的再保险合同组摊回的对应的保险合同赔付的比例，计算分出再保险合同组分保摊回未到期责任资产在过渡日的亏损摊回部分金额；

（三）企业根据本准则第三十四条选择将保险合同金融变动额分解计入保险财务损益和其他综合收益的，应当采用适当方法确定过渡日计入其他综合收益的累计金额；

（四）对保险获取现金流量资产采用追溯调整法不切实可行时，企业应当采用适当方法确定过渡日的保险获取现金流量资产。
*** 第一百一十六条　企业应当在附注中披露与衔接处理相关的下列信息：

（一）在采用修正追溯调整法和公允价值法的保险合同的存续期间，说明该类保险合同在过渡日的衔接处理；

（二）在本准则第八十六条和第八十七条规定的调节表中，分别就过渡日采用修正追溯调整法和公允价值法的保险合同，在该类保险合同存续期间单独披露其对保险服务收入和合同服务边际的影响；

（三）企业根据本准则第一百一十二条和第一百一十五条（三）的规定，采用修正追溯调整法或公允价值法确定过渡日计入其他综合收益的累计金额的，在该金额减计为零之前的期间，应当披露以公允价值计量且其变动计入其他综合收益的相关金融资产计入其他综合收益的累计金额自期初至期末的调节情况。
*** 第一百一十七条　企业无须披露比首次执行日前近一个会计年度更早期间的信息。企业选择披露未经调整的更早期间的比较信息的，应当列示该类信息并说明其编制基础。企业可以选择不披露未公开的、比首次执行日前四个会计年度更早期间发生的索赔进展情况，但应当披露这一选择。
*** 第一百一十八条　企业在本准则首次执行日前执行金融工具相关会计准则的，应当在本准则首次执行日对金融资产进行下列处理：

（一）企业可以对管理金融资产的业务模式进行重新评估并确定金融资产分类，但为了与本准则适用范围内合同无关的活动而持有的金融资产除外；

（二）在首次执行日前被指定为以公允价值计量且其变动计入当期损益的金融资产，因企业执行本准则而不再符合指定条件时，应当撤销之前的指定；

（三）金融资产因企业执行本准则而符合指定条件的，可以指定为以公允价值计量且其变动计入当期损益的金融资产；

（四）企业可以将非交易性权益工具投资指定为以公允价值计量且其变动计入其他综合收益的金融资产或撤销之前的指定。企业应当以本准则首次执行日的事实和情况为基础进行上述处理，并追溯调整首次执行本准则当年年初留存收益或权益的其他部分。企业无须调整可比期间信息。企业选择调整可比期间信息的，应当以前期事实和情况为基础，以反映金融工具相关会计准则的要求。
*** 第一百一十九条　企业根据本准则第一百一十八条规定进行处理的，应当披露下列信息：

（一）根据本准则第一百一十八条（一）对管理相关金融资产的业务模式进行重新评估并确定金融资产分类的标准；

（二）相关金融资产列报类型和账面价值的变化；

（三）撤销之前指定为以公允价值计量且其变动计入当期损益的金融资产的期末账面价值；

（四）指定或撤销指定以公允价值计量且其变动计入当期损益的相关金融资产的原因。
** 第十一章 附则
:PROPERTIES:
:heading: true
:END:
*** 第一百二十条　本准则自2023年1月1日起施行。
